# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Request param TypedDicts for termix_sdk.resources.audit."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import TypedDict


class AuditExportParams(TypedDict, total=False):
    format: str


class AuditListParams(TypedDict, total=False):
    page: str
    limit: str
