# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Request param TypedDicts for termix_sdk.resources.guacamole."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import TypedDict


class GuacamoleConnectHostParams(TypedDict, total=False):
    protocol: Any
    promptedUsername: Any
    promptedPassword: Any
    promptedDomain: Any


class GuacamoleCreateTokenParams(TypedDict, total=False):
    type: Literal["rdp"] | Literal["vnc"] | Literal["telnet"]
    hostname: Any
    port: Any
    username: Any
    password: Any
    domain: Any
    rawOptions: Any
