# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Request param TypedDicts for termix_sdk.resources.homepage."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import TypedDict


class HomepageGetFaviconParams(TypedDict, total=False):
    url: str


class HomepageUpdateItemParams(TypedDict, total=False):
    title: str | None
    config: dict[str, Any]


class HomepageCreateItemParams(TypedDict, total=False):
    typeId: str
    title: str | None
    config: dict[str, Any]


class HomepageSetLayoutParams(TypedDict, total=False):
    entries: list[dict[str, Any]]
    pan: dict[str, Any]
    zoom: float


class HomepagePingParams(TypedDict, total=False):
    url: str
    ttl: int


class HomepageProxyParams(TypedDict, total=False):
    url: str
    ttl: int


class HomepageRssParams(TypedDict, total=False):
    url: str
    max: int
