# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Request param TypedDicts for termix_sdk.resources.hosts."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import TypedDict


class HostsEnableAutostartParams(TypedDict, total=False):
    sshConfigId: float


class HostsBulkUpdateParams(TypedDict, total=False):
    hostIds: list[Any]
    updates: int


class HostsReorderParams(TypedDict, total=False):
    positions: list[Any]


class HostsBulkImportParams(TypedDict, total=False):
    hosts: list[dict[str, Any]]
    overwrite: bool
    credentials: list[dict[str, Any]]


class HostsSshConfigImportParams(TypedDict, total=False):
    content: str
    overwrite: bool


class HostsUpdateFolderMetadataParams(TypedDict, total=False):
    name: str
    color: str | None
    icon: str | None
    credentialId: int


class HostsReorderFoldersParams(TypedDict, total=False):
    positions: list[Any]


class HostsRenameFolderParams(TypedDict, total=False):
    oldName: str
    newName: str


class HostsTestProxyParams(TypedDict, total=False):
    singleProxy: dict[str, Any]
    proxyChain: list[dict[str, Any]]
    testTarget: dict[str, Any]


class HostsGetPasswordParams(TypedDict, total=False):
    field: str


class HostsExportAllParams(TypedDict, total=False):
    share: bool


class HostsGetRecentTransferParams(TypedDict, total=False):
    sourceHostId: str


class HostsRecordRecentTransferParams(TypedDict, total=False):
    sourceHostId: int
    destHostId: int
    destPath: str
    destPathLabel: str


class HostsQuickConnectParams(TypedDict, total=False):
    ip: str
    port: int
    username: str
    authType: str
    password: str | None
    key: str | None
    keyPassword: str | None
    keyType: str | None
    credentialId: int
    overrideCredentialUsername: bool | None
