# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Request param TypedDicts for termix_sdk.resources.hosts."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import TypedDict


class HostsEnableAutostartParams(TypedDict, total=False):
    sshConfigId: float


class HostsBulkUpdateParams(TypedDict, total=False):
    hostIds: list[Any]
    updates: int


class HostsReorderParams(TypedDict, total=False):
    positions: list[Any]


class HostsBulkImportParams(TypedDict, total=False):
    hosts: list[dict[str, Any]]
    overwrite: bool
    credentials: list[dict[str, Any]]


class HostsSshConfigImportParams(TypedDict, total=False):
    content: str
    overwrite: bool


class HostsUpdateFolderMetadataParams(TypedDict, total=False):
    name: str
    color: str | None
    icon: str | None
    credentialId: int


class HostsReorderFoldersParams(TypedDict, total=False):
    positions: list[Any]


class HostsRenameFolderParams(TypedDict, total=False):
    oldName: str
    newName: str


class HostsTestProxyParams(TypedDict, total=False):
    singleProxy: dict[str, Any]
    proxyChain: list[dict[str, Any]]
    testTarget: dict[str, Any]


class HostsGetPasswordParams(TypedDict, total=False):
    field: str


class HostsExportAllParams(TypedDict, total=False):
    share: bool


class HostsGetRecentTransferParams(TypedDict, total=False):
    sourceHostId: str


class HostsRecordRecentTransferParams(TypedDict, total=False):
    sourceHostId: int
    destHostId: int
    destPath: str
    destPathLabel: str


class HostsQuickConnectParams(TypedDict, total=False):
    ip: str
    port: int
    username: str
    authType: (
        Literal["password"]
        | Literal["key"]
        | Literal["credential"]
        | Literal["none"]
        | Literal["opkssh"]
        | Literal["stepca"]
        | Literal["tailscale"]
        | Literal["agent"]
        | Literal["vault"]
    )
    password: str
    key: Any
    keyPassword: str
    keyType: str
    credentialId: int
    overrideCredentialUsername: bool


class HostsCreateParams(TypedDict, total=False):
    connectionType: str
    name: str | None
    folder: str | None
    parentHostId: int
    tags: list[Any]
    ip: str
    port: int
    username: str
    password: str | None
    authMethod: Any
    authType: str
    useWarpgate: bool
    shareSshAuth: bool
    credentialId: int | None
    vaultProfileId: int | None
    key: str
    keyPassword: str
    keyType: str | None
    sudoPassword: str | None
    pin: bool
    enableTerminal: bool
    enableCommandHistory: bool
    enableTunnel: bool
    enableFileManager: bool
    scpLegacy: bool
    enableDocker: bool
    enableWebUi: bool
    enableProxmox: bool
    enableTmuxMonitor: bool
    enableTerminalToolbar: bool
    enableAiAssistant: bool
    allowSessionSharing: bool
    showTerminalInSidebar: bool
    showFileManagerInSidebar: bool
    showTunnelInSidebar: bool
    showDockerInSidebar: bool
    showServerStatsInSidebar: bool
    defaultPath: str | None
    tunnelConnections: list[Any]
    jumpHosts: list[Any]
    quickActions: list[Any]
    statsConfig: str
    dockerConfig: str
    webUiConfig: str
    proxmoxConfig: str
    enableProxmoxStats: bool
    proxmoxStatsConfig: str
    terminalConfig: str
    forceKeyboardInteractive: bool
    domain: str | None
    security: str | None
    ignoreCert: bool
    guacamoleConfig: Any
    notes: str | None
    useSocks5: bool
    socks5Host: str | None
    socks5Port: int | None
    socks5Username: str | None
    socks5Password: str | None
    socks5ProxyChain: list[Any]
    connectionOrigin: Literal["local"] | Literal["remote"]
    portKnockSequence: list[Any]
    overrideCredentialUsername: bool
    macAddress: str | None
    wolBroadcastAddress: str | None
    enableSsh: bool
    enableRdp: bool
    enableVnc: bool
    enableTelnet: bool
    sshPort: int | None
    rdpPort: int | None
    vncPort: int | None
    telnetPort: int | None
    rdpAuthType: str | None
    rdpCredentialId: int | None
    rdpUser: str | None
    rdpPassword: str | None
    rdpDomain: str | None
    rdpSecurity: str | None
    rdpIgnoreCert: bool
    vncAuthType: str | None
    vncCredentialId: int | None
    vncPassword: str | None
    vncUser: str | None
    telnetAuthType: str | None
    telnetCredentialId: int | None
    telnetUser: str | None
    telnetPassword: str | None
    data: Any


class HostsEnrollParams(TypedDict, total=False):
    connectionType: str
    name: str | None
    folder: str | None
    parentHostId: int
    tags: list[Any]
    ip: str
    port: int
    username: str
    password: str | None
    authMethod: Any
    authType: str
    useWarpgate: bool
    shareSshAuth: bool
    credentialId: int | None
    vaultProfileId: int | None
    key: str
    keyPassword: str
    keyType: str | None
    sudoPassword: str | None
    pin: bool
    enableTerminal: bool
    enableCommandHistory: bool
    enableTunnel: bool
    enableFileManager: bool
    scpLegacy: bool
    enableDocker: bool
    enableWebUi: bool
    enableProxmox: bool
    enableTmuxMonitor: bool
    enableTerminalToolbar: bool
    enableAiAssistant: bool
    allowSessionSharing: bool
    showTerminalInSidebar: bool
    showFileManagerInSidebar: bool
    showTunnelInSidebar: bool
    showDockerInSidebar: bool
    showServerStatsInSidebar: bool
    defaultPath: str | None
    tunnelConnections: list[Any]
    jumpHosts: list[Any]
    quickActions: list[Any]
    statsConfig: str
    dockerConfig: str
    webUiConfig: str
    proxmoxConfig: str
    enableProxmoxStats: bool
    proxmoxStatsConfig: str
    terminalConfig: str
    forceKeyboardInteractive: bool
    domain: str | None
    security: str | None
    ignoreCert: bool
    guacamoleConfig: Any
    notes: str | None
    useSocks5: bool
    socks5Host: str | None
    socks5Port: int | None
    socks5Username: str | None
    socks5Password: str | None
    socks5ProxyChain: list[Any]
    connectionOrigin: Literal["local"] | Literal["remote"]
    portKnockSequence: list[Any]
    overrideCredentialUsername: bool
    macAddress: str | None
    wolBroadcastAddress: str | None
    enableSsh: bool
    enableRdp: bool
    enableVnc: bool
    enableTelnet: bool
    sshPort: int | None
    rdpPort: int | None
    vncPort: int | None
    telnetPort: int | None
    rdpAuthType: str | None
    rdpCredentialId: int | None
    rdpUser: str | None
    rdpPassword: str | None
    rdpDomain: str | None
    rdpSecurity: str | None
    rdpIgnoreCert: bool
    vncAuthType: str | None
    vncCredentialId: int | None
    vncPassword: str | None
    vncUser: str | None
    telnetAuthType: str | None
    telnetCredentialId: int | None
    telnetUser: str | None
    telnetPassword: str | None
    data: Any


class HostsUpdateParams(TypedDict, total=False):
    connectionType: str
    name: str | None
    folder: str | None
    parentHostId: int
    tags: list[Any]
    ip: str
    port: int
    username: str
    password: str | None
    authMethod: Any
    authType: str
    useWarpgate: bool
    shareSshAuth: bool
    credentialId: int | None
    vaultProfileId: int | None
    key: str
    keyPassword: str
    keyType: str | None
    sudoPassword: str | None
    pin: bool
    enableTerminal: bool
    enableCommandHistory: bool
    enableTunnel: bool
    enableFileManager: bool
    scpLegacy: bool
    enableDocker: bool
    enableWebUi: bool
    enableProxmox: bool
    enableTmuxMonitor: bool
    enableTerminalToolbar: bool
    enableAiAssistant: bool
    allowSessionSharing: bool
    showTerminalInSidebar: bool
    showFileManagerInSidebar: bool
    showTunnelInSidebar: bool
    showDockerInSidebar: bool
    showServerStatsInSidebar: bool
    defaultPath: str | None
    tunnelConnections: list[Any]
    jumpHosts: list[Any]
    quickActions: list[Any]
    statsConfig: str
    dockerConfig: str
    webUiConfig: str
    proxmoxConfig: str
    enableProxmoxStats: bool
    proxmoxStatsConfig: str
    terminalConfig: str
    forceKeyboardInteractive: bool
    domain: str | None
    security: str | None
    ignoreCert: bool
    guacamoleConfig: Any
    notes: str | None
    useSocks5: bool
    socks5Host: str | None
    socks5Port: int | None
    socks5Username: str | None
    socks5Password: str | None
    socks5ProxyChain: list[Any]
    connectionOrigin: Literal["local"] | Literal["remote"]
    portKnockSequence: list[Any]
    overrideCredentialUsername: bool
    macAddress: str | None
    wolBroadcastAddress: str | None
    enableSsh: bool
    enableRdp: bool
    enableVnc: bool
    enableTelnet: bool
    sshPort: int | None
    rdpPort: int | None
    vncPort: int | None
    telnetPort: int | None
    rdpAuthType: str | None
    rdpCredentialId: int | None
    rdpUser: str | None
    rdpPassword: str | None
    rdpDomain: str | None
    rdpSecurity: str | None
    rdpIgnoreCert: bool
    vncAuthType: str | None
    vncCredentialId: int | None
    vncPassword: str | None
    vncUser: str | None
    telnetAuthType: str | None
    telnetCredentialId: int | None
    telnetUser: str | None
    telnetPassword: str | None
    data: Any


class HostsUpdateTerminalConfigParams(TypedDict, total=False):
    autoTmux: bool
