# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Request param TypedDicts for termix_sdk.resources.sync."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import TypedDict


class SyncPullParams(TypedDict, total=False):
    since: str


class SyncPushParams(TypedDict, total=False):
    row: Any


class SyncPushTombstonesParams(TypedDict, total=False):
    entityType: str
    syncId: str


class SyncPullTombstonesParams(TypedDict, total=False):
    since: str
