# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Request param TypedDicts for termix_sdk.resources.tmux."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import TypedDict


class TmuxFocusParams(TypedDict, total=False):
    paneId: str


class TmuxListSessionsParams(TypedDict, total=False):
    name: str


class TmuxListWindowsParams(TypedDict, total=False):
    sessionName: str


class TmuxRenameParams(TypedDict, total=False):
    sessionName: str
    newName: str


class TmuxKillParams(TypedDict, total=False):
    sessionName: str


class TmuxKillWindowParams(TypedDict, total=False):
    sessionName: str
    windowIndex: float


class TmuxKillPaneParams(TypedDict, total=False):
    paneId: str


class TmuxSplitParams(TypedDict, total=False):
    paneId: str
    direction: Literal["v"] | Literal["h"]


class TmuxSearchParams(TypedDict, total=False):
    q: str


class TmuxSetTagsParams(TypedDict, total=False):
    sessionName: str
    tags: list[Any]
