# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.ai."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class AiCreateProviderResult(TermixObject):
    provider: dict[str, Any]


class AiListProvidersResult(TermixObject):
    providers: list[dict[str, Any]]


class AiUpdateProviderResult(TermixObject):
    provider: dict[str, Any]


class AiDeleteProviderResult(TermixObject):
    success: Literal[True]


class AiListProviderModelsResult(TermixObject):
    models: list[str]


class AiListConversationsResult(TermixObject):
    conversations: list[dict[str, Any]]


class AiGetConversationResult(TermixObject):
    conversation: dict[str, Any]
    messages: list[dict[str, Any]]
    proposals: list[dict[str, Any]]


class AiDeleteConversationResult(TermixObject):
    success: Literal[True]


class AiGetStatusResult(TermixObject):
    globallyEnabled: bool
    enabled: bool
    allowReadOnlyCommands: bool


class AiApplyProposalResult(TermixObject):
    success: bool
    summary: str


class AiRejectProposalResult(TermixObject):
    success: Literal[True]
