# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.alerts."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class AlertsDeleteChannelResult(TermixObject):
    success: Literal[True]


class AlertsListRulesItem(TermixObject):
    channels: list[float]
    id: float
    user_id: str
    host_id: float
    name: str
    enabled: float
    trigger_type: str
    threshold_value: float
    threshold_duration_seconds: float
    cooldown_minutes: float
    created_at: str
    updated_at: str


class AlertsCreateRuleResult(TermixObject):
    channels: list[float]
    id: float
    user_id: str
    host_id: float
    name: str
    enabled: float
    trigger_type: str
    threshold_value: float
    threshold_duration_seconds: float
    cooldown_minutes: float
    created_at: str
    updated_at: str


class AlertsUpdateRuleResult(TermixObject):
    channels: list[float]
    id: float
    user_id: str
    host_id: float
    name: str
    enabled: float
    trigger_type: str
    threshold_value: float
    threshold_duration_seconds: float
    cooldown_minutes: float
    created_at: str
    updated_at: str


class AlertsDeleteRuleResult(TermixObject):
    success: Literal[True]


class AlertsListChannelsItem(TermixObject):
    id: float
    user_id: str
    name: str
    type: str
    config: str
    enabled: float
    created_at: str


class AlertsCreateChannelResult(TermixObject):
    id: float
    user_id: str
    name: str
    type: str
    config: str
    enabled: float
    created_at: str


class AlertsListFiringsResult(TermixObject):
    firings: list[dict[str, Any]]
    total: float


class AlertsAcknowledgeFiringResult(TermixObject):
    success: Literal[True]


class AlertsAcknowledgeAllFiringsResult(TermixObject):
    success: Literal[True]


class AlertsListResult(TermixObject):
    alerts: list[dict[str, Any]]
    cached: bool
    total_count: float


class AlertsDismissResult(TermixObject):
    message: Literal["Alert dismissed successfully"]


class AlertsClearDismissedResult(TermixObject):
    message: Literal["Alert undismissed successfully"]


class AlertsListDismissedResult(TermixObject):
    dismissed_alerts: list[dict[str, Any]]
    total_count: float
