# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.api_keys."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class ApiKeysListResult(TermixObject):
    apiKeys: list[dict[str, Any]]


class ApiKeysCreateResult(TermixObject):
    id: str
    name: str
    userId: str
    username: str
    tokenPrefix: str
    createdAt: str
    expiresAt: Any
    token: str


class ApiKeysDeleteResult(TermixObject):
    success: Literal[True]
