# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.guacamole."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class GuacamoleConnectHostResult(TermixObject):
    token: str
    termixConnectId: Any
    guacamoleConnectionId: Any


class GuacamoleGetStatusResult(TermixObject):
    guacd: dict[str, Any]
    websocket: dict[str, Any]


class GuacamoleCreateTokenResult(TermixObject):
    token: str


class GuacamoleGetConnectionResult(TermixObject):
    guacamoleConnectionId: str
