# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.rbac."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class RbacListRolesResult(TermixObject):
    roles: list[dict[str, Any]]


class RbacCreateRoleResult(TermixObject):
    success: Literal[True]
    roleId: float
    message: Literal["Role created successfully"]


class RbacUpdateRoleResult(TermixObject):
    success: Literal[True]
    message: Literal["Role updated successfully"]


class RbacDeleteRoleResult(TermixObject):
    success: Literal[True]
    message: Literal["Role deleted successfully"]


class RbacPermissionsCatalogResult(TermixObject):
    catalog: list[dict[str, Any]]


class RbacAssignRoleResult(TermixObject):
    success: Literal[True]
    message: Literal["Role assigned successfully"]


class RbacListUserRolesResult(TermixObject):
    roles: list[dict[str, Any]]


class RbacRevokeRoleResult(TermixObject):
    success: Literal[True]
    message: Literal["Role removed successfully"]


class RbacShareSnippetResult(TermixObject):
    success: Literal[True]
    message: Any
    expiresAt: str


class RbacShareHostResult(TermixObject):
    success: Literal[True]
    message: Literal["Host shared successfully"]
    permissionLevel: Literal["manage"] | Literal["connect"] | Literal["view"] | Literal["edit"]
    expiresAt: str
    results: list[dict[str, Any]]


class RbacDeleteSnippetAccessResult(TermixObject):
    success: Literal[True]
    message: Literal["Snippet access revoked"]


class RbacListSnippetAccessResult(TermixObject):
    accessList: list[dict[str, Any]]


class RbacListSharedSnippetsResult(TermixObject):
    sharedSnippets: list[dict[str, Any]]


class RbacShareFolderResult(TermixObject):
    success: Literal[True]
    message: Literal["Folder shared successfully"]
    permissionLevel: Literal["manage"] | Literal["connect"] | Literal["view"] | Literal["edit"]
    expiresAt: str
    hostsShared: float
    hostsTotal: float
    hostResults: list[dict[str, Any]]


class RbacUpdateHostAccessResult(TermixObject):
    success: Literal[True]
    message: Literal["Access updated"]
    expiresAt: str


class RbacDeleteHostAccessResult(TermixObject):
    success: Literal[True]
    message: Literal["Access revoked"]


class RbacListHostAccessResult(TermixObject):
    accessList: list[dict[str, Any]]
    isOwner: bool


class RbacListSharedHostsResult(TermixObject):
    sharedHosts: list[dict[str, Any]]
