# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.session_logs."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class SessionLogsListResult(TermixObject):
    logs: list[dict[str, Any]]


class SessionLogsGetRetentionResult(TermixObject):
    retentionDays: float


class SessionLogsSetRetentionResult(TermixObject):
    retentionDays: float


class SessionLogsRetrieveResult(TermixObject):
    log: dict[str, Any]


class SessionLogsDeleteResult(TermixObject):
    success: Literal[True]
