# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.system."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class SystemHealthResult(TermixObject):
    status: Literal["ok"]


class SystemListReleasesResult(TermixObject):
    feed: dict[str, Any]
    items: list[dict[str, Any]]
    total_count: float
    cached: bool
    cache_age: float
