# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.termix_id."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class TermixIdGetCaResult(TermixObject):
    ca: dict[str, Any]


class TermixIdCreateCaResult(TermixObject):
    publicKey: str
    validityDays: float
    resolverPath: Any


class TermixIdDeleteCaResult(TermixObject):
    success: Literal[True]


class TermixIdRotateCaResult(TermixObject):
    publicKey: str
    validityDays: float
    resolverPath: Any


class TermixIdIssueCertificateResult(TermixObject):
    certificate: str
    keyId: str
    validBefore: float
    principals: Any
    validityDays: float


class TermixIdListLinkedCredentialsResult(TermixObject):
    credentialIds: list[float]


class TermixIdGetMeResult(TermixObject):
    identity: dict[str, Any]
    keys: list[dict[str, Any]]


class TermixIdCheckHandleResult(TermixObject):
    available: bool
    valid: Literal[True]


class TermixIdCreateResult(TermixObject):
    """POST /termix-id."""

    pass


class TermixIdUpdateResult(TermixObject):
    """PUT /termix-id."""

    pass


class TermixIdDeleteResult(TermixObject):
    success: Literal[True]


class TermixIdCreateKeyResult(TermixObject):
    """POST /termix-id/keys."""

    pass


class TermixIdGenerateKeyResult(TermixObject):
    key: dict[str, Any]
    privateKey: str
    publicKey: str
    credentialId: float


class TermixIdUpdateKeyResult(TermixObject):
    """PATCH /termix-id/keys/{id}."""

    pass


class TermixIdDeleteKeyResult(TermixObject):
    success: Literal[True]
