# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Response models for termix_sdk.resources.tunnel."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from .._object import TermixObject


class TunnelGetStatusByNameResult(TermixObject):
    name: str
    status: dict[str, Any]


class TunnelConnectResult(TermixObject):
    message: Literal["Connection request received"]
    tunnelName: str


class TunnelDisconnectResult(TermixObject):
    message: Literal["Disconnect request received"]
    tunnelName: Any


class TunnelGetStatusResult(TermixObject):
    """GET /ssh/tunnel/status."""

    pass


class TunnelCancelResult(TermixObject):
    message: Literal["Cancel request received"]
    tunnelName: Any


class TunnelOpenWebEndpointResult(TermixObject):
    port: float
