"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.users."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_get_me_contract(client, mock_http_client):
    """Generated from GET /users/me in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "userId": "x",
            "username": "x",
            "is_admin": True,
            "is_oidc": True,
            "is_dual_auth": "x",
            "totp_enabled": True,
            "show_donation_modal": True,
        },
    )
    result = client.users.get_me()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/me")
    assert result.to_dict() == {
        "userId": "x",
        "username": "x",
        "is_admin": True,
        "is_oidc": True,
        "is_dual_auth": "x",
        "totp_enabled": True,
        "show_donation_modal": True,
    }


def test_logout_contract(client, mock_http_client):
    """Generated from POST /users/logout in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Logged out successfully"}
    )
    result = client.users.logout()
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/logout")
    assert result.to_dict() == {"success": True, "message": "Logged out successfully"}


def test_get_token_contract(client, mock_http_client):
    """Generated from GET /users/me/token in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"token": "x"})
    result = client.users.get_token()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/me/token")
    assert result.to_dict() == {"token": "x"}


def test_dismiss_donation_modal_contract(client, mock_http_client):
    """Generated from POST /users/me/dismiss-donation-modal in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.users.dismiss_donation_modal()
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/me/dismiss-donation-modal")
    assert result.to_dict() == {"success": True}


def test_change_password_contract(client, mock_http_client):
    """Generated from POST /users/change-password in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"message": "Password changed successfully. Please log in again."}
    )
    result = client.users.change_password(oldPassword="x", newPassword="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/change-password")
    assert sent.json == {"oldPassword": "x", "newPassword": "x"}
    assert result.to_dict() == {"message": "Password changed successfully. Please log in again."}


def test_delete_account_contract(client, mock_http_client):
    """Generated from DELETE /users/delete-account in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"message": "Account deleted successfully"}
    )
    result = client.users.delete_account()
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/users/delete-account")
    assert result.to_dict() == {"message": "Account deleted successfully"}


def test_unlock_data_contract(client, mock_http_client):
    """Generated from POST /users/unlock-data in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Data unlocked successfully"}
    )
    result = client.users.unlock_data(password="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/unlock-data")
    assert sent.json == {"password": "x"}
    assert result.to_dict() == {"success": True, "message": "Data unlocked successfully"}


def test_get_data_status_contract(client, mock_http_client):
    """Generated from GET /users/data-status in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"unlocked": True, "message": "Data is unlocked"}
    )
    result = client.users.get_data_status()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/data-status")
    assert result.to_dict() == {"unlocked": True, "message": "Data is unlocked"}


def test_setup_totp_contract(client, mock_http_client):
    """Generated from POST /users/totp/setup in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"secret": "x", "qr_code": "x"})
    result = client.users.setup_totp()
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/setup")
    assert result.to_dict() == {"secret": "x", "qr_code": "x"}


def test_enable_totp_contract(client, mock_http_client):
    """Generated from POST /users/totp/enable in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"message": "TOTP enabled successfully", "backup_codes": ["x"]}
    )
    result = client.users.enable_totp(totp_code="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/enable")
    assert sent.json == {"totp_code": "x"}
    assert result.to_dict() == {"message": "TOTP enabled successfully", "backup_codes": ["x"]}


def test_disable_totp_contract(client, mock_http_client):
    """Generated from POST /users/totp/disable in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"message": "TOTP disabled successfully"})
    result = client.users.disable_totp(password="x", totp_code="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/disable")
    assert sent.json == {"password": "x", "totp_code": "x"}
    assert result.to_dict() == {"message": "TOTP disabled successfully"}


def test_get_totp_backup_codes_contract(client, mock_http_client):
    """Generated from POST /users/totp/backup-codes in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"backup_codes": ["x"]})
    result = client.users.get_totp_backup_codes(password="x", totp_code="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/backup-codes")
    assert sent.json == {"password": "x", "totp_code": "x"}
    assert result.to_dict() == {"backup_codes": ["x"]}


def test_proxy_login_contract(client, mock_http_client):
    """Generated from POST /users/proxy-login in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"enabled": False})
    result = client.users.proxy_login()
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/proxy-login")
    assert result.to_dict() == {"enabled": False}


def test_unlink_oidc_from_password_contract(client, mock_http_client):
    """Generated from POST /users/unlink-oidc-from-password in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True, "message": "x"})
    result = client.users.unlink_oidc_from_password(userId="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/unlink-oidc-from-password")
    assert sent.json == {"userId": "x"}
    assert result.to_dict() == {"success": True, "message": "x"}


def test_link_oidc_to_password_contract(client, mock_http_client):
    """Generated from POST /users/link-oidc-to-password in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True, "message": "x"})
    result = client.users.link_oidc_to_password(oidcUserId="x", targetUsername="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/link-oidc-to-password")
    assert sent.json == {"oidcUserId": "x", "targetUsername": "x"}
    assert result.to_dict() == {"success": True, "message": "x"}


def test_initiate_reset_contract(client, mock_http_client):
    """Generated from POST /users/initiate-reset in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "message": "Password reset code has been generated and logged. Check docker logs for the code."
        },
    )
    result = client.users.initiate_reset(username="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/initiate-reset")
    assert sent.json == {"username": "x"}
    assert result.to_dict() == {
        "message": "Password reset code has been generated and logged. Check docker logs for the code."
    }


def test_verify_reset_code_contract(client, mock_http_client):
    """Generated from POST /users/verify-reset-code in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"message": "Reset code verified", "tempToken": "x"}
    )
    result = client.users.verify_reset_code(username="x", resetCode="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/verify-reset-code")
    assert sent.json == {"username": "x", "resetCode": "x"}
    assert result.to_dict() == {"message": "Reset code verified", "tempToken": "x"}


def test_complete_reset_contract(client, mock_http_client):
    """Generated from POST /users/complete-reset in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"message": "Password has been successfully reset", "dataWiped": True}
    )
    result = client.users.complete_reset(
        username="x", tempToken="x", newPassword="x", confirmDataWipe=True
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/complete-reset")
    assert sent.json == {
        "username": "x",
        "tempToken": "x",
        "newPassword": "x",
        "confirmDataWipe": True,
    }
    assert result.to_dict() == {
        "message": "Password has been successfully reset",
        "dataWiped": True,
    }


def test_list_sessions_contract(client, mock_http_client):
    """Generated from GET /users/sessions in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "sessions": [
                {
                    "id": "x",
                    "userId": "x",
                    "deviceType": "x",
                    "deviceInfo": "x",
                    "createdAt": "x",
                    "expiresAt": "x",
                    "lastActiveAt": "x",
                    "isRevoked": "x",
                    "isCurrentSession": True,
                }
            ]
        },
    )
    result = client.users.list_sessions()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/sessions")
    assert result.to_dict() == {
        "sessions": [
            {
                "id": "x",
                "userId": "x",
                "deviceType": "x",
                "deviceInfo": "x",
                "createdAt": "x",
                "expiresAt": "x",
                "lastActiveAt": "x",
                "isRevoked": "x",
                "isCurrentSession": True,
            }
        ]
    }


def test_revoke_session_contract(client, mock_http_client):
    """Generated from DELETE /users/sessions/{sessionId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Session revoked successfully"}
    )
    result = client.users.revoke_session("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/users/sessions/x")
    assert result.to_dict() == {"success": True, "message": "Session revoked successfully"}


def test_revoke_all_sessions_contract(client, mock_http_client):
    """Generated from POST /users/sessions/revoke-all in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"message": "x", "count": 1.0})
    result = client.users.revoke_all_sessions(targetUserId="x", exceptCurrent=True)
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/sessions/revoke-all")
    assert sent.json == {"targetUserId": "x", "exceptCurrent": True}
    assert result.to_dict() == {"message": "x", "count": 1.0}


def test_get_terminal_image_storage_settings_contract(client, mock_http_client):
    """Generated from GET /users/terminal-image-storage-settings in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.users.get_terminal_image_storage_settings()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/terminal-image-storage-settings")
    assert result is not None


def test_update_terminal_image_storage_settings_contract(client, mock_http_client):
    """Generated from PATCH /users/terminal-image-storage-settings in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.users.update_terminal_image_storage_settings(
        mode="local", localDir="x", hostPath="x", ttlMs=1.0, maxCount=1.0, maxBytes=1.0
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/users/terminal-image-storage-settings")
    assert sent.json == {
        "mode": "local",
        "localDir": "x",
        "hostPath": "x",
        "ttlMs": 1.0,
        "maxCount": 1.0,
        "maxBytes": 1.0,
    }
    assert result is not None


def test_test_terminal_image_storage_settings_contract(client, mock_http_client):
    """Generated from POST /users/terminal-image-storage-settings/test in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "mode": "local",
            "connected": True,
            "remoteSftpAvailable": True,
            "localHostVisible": True,
            "selectedMode": "local",
            "localMappingConfigured": True,
        },
    )
    result = client.users.test_terminal_image_storage_settings(instanceId="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/terminal-image-storage-settings/test")
    assert sent.json == {"instanceId": "x"}
    assert result.to_dict() == {
        "mode": "local",
        "connected": True,
        "remoteSftpAvailable": True,
        "localHostVisible": True,
        "selectedMode": "local",
        "localMappingConfigured": True,
    }


def test_register_contract(client, mock_http_client):
    """Generated from POST /users/create in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "message": "User created",
            "is_admin": True,
            "toast": {"type": "success", "message": "x"},
        },
    )
    result = client.users.register(username="x", password="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/create")
    assert sent.json == {"username": "x", "password": "x"}
    assert result.to_dict() == {
        "message": "User created",
        "is_admin": True,
        "toast": {"type": "success", "message": "x"},
    }


@pytest.mark.asyncio
async def test_async_get_me_contract(async_client, mock_async_http_client):
    """Generated from GET /users/me in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "userId": "x",
            "username": "x",
            "is_admin": True,
            "is_oidc": True,
            "is_dual_auth": "x",
            "totp_enabled": True,
            "show_donation_modal": True,
        },
    )
    result = await async_client.users.get_me()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/me")
    assert result.to_dict() == {
        "userId": "x",
        "username": "x",
        "is_admin": True,
        "is_oidc": True,
        "is_dual_auth": "x",
        "totp_enabled": True,
        "show_donation_modal": True,
    }


@pytest.mark.asyncio
async def test_async_logout_contract(async_client, mock_async_http_client):
    """Generated from POST /users/logout in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Logged out successfully"}
    )
    result = await async_client.users.logout()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/logout")
    assert result.to_dict() == {"success": True, "message": "Logged out successfully"}


@pytest.mark.asyncio
async def test_async_get_token_contract(async_client, mock_async_http_client):
    """Generated from GET /users/me/token in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"token": "x"})
    result = await async_client.users.get_token()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/me/token")
    assert result.to_dict() == {"token": "x"}


@pytest.mark.asyncio
async def test_async_dismiss_donation_modal_contract(async_client, mock_async_http_client):
    """Generated from POST /users/me/dismiss-donation-modal in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.users.dismiss_donation_modal()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/me/dismiss-donation-modal")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_change_password_contract(async_client, mock_async_http_client):
    """Generated from POST /users/change-password in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"message": "Password changed successfully. Please log in again."}
    )
    result = await async_client.users.change_password(oldPassword="x", newPassword="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/change-password")
    assert sent.json == {"oldPassword": "x", "newPassword": "x"}
    assert result.to_dict() == {"message": "Password changed successfully. Please log in again."}


@pytest.mark.asyncio
async def test_async_delete_account_contract(async_client, mock_async_http_client):
    """Generated from DELETE /users/delete-account in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"message": "Account deleted successfully"}
    )
    result = await async_client.users.delete_account()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/users/delete-account")
    assert result.to_dict() == {"message": "Account deleted successfully"}


@pytest.mark.asyncio
async def test_async_unlock_data_contract(async_client, mock_async_http_client):
    """Generated from POST /users/unlock-data in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Data unlocked successfully"}
    )
    result = await async_client.users.unlock_data(password="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/unlock-data")
    assert sent.json == {"password": "x"}
    assert result.to_dict() == {"success": True, "message": "Data unlocked successfully"}


@pytest.mark.asyncio
async def test_async_get_data_status_contract(async_client, mock_async_http_client):
    """Generated from GET /users/data-status in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"unlocked": True, "message": "Data is unlocked"}
    )
    result = await async_client.users.get_data_status()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/data-status")
    assert result.to_dict() == {"unlocked": True, "message": "Data is unlocked"}


@pytest.mark.asyncio
async def test_async_setup_totp_contract(async_client, mock_async_http_client):
    """Generated from POST /users/totp/setup in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"secret": "x", "qr_code": "x"})
    result = await async_client.users.setup_totp()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/setup")
    assert result.to_dict() == {"secret": "x", "qr_code": "x"}


@pytest.mark.asyncio
async def test_async_enable_totp_contract(async_client, mock_async_http_client):
    """Generated from POST /users/totp/enable in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"message": "TOTP enabled successfully", "backup_codes": ["x"]}
    )
    result = await async_client.users.enable_totp(totp_code="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/enable")
    assert sent.json == {"totp_code": "x"}
    assert result.to_dict() == {"message": "TOTP enabled successfully", "backup_codes": ["x"]}


@pytest.mark.asyncio
async def test_async_disable_totp_contract(async_client, mock_async_http_client):
    """Generated from POST /users/totp/disable in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"message": "TOTP disabled successfully"}
    )
    result = await async_client.users.disable_totp(password="x", totp_code="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/disable")
    assert sent.json == {"password": "x", "totp_code": "x"}
    assert result.to_dict() == {"message": "TOTP disabled successfully"}


@pytest.mark.asyncio
async def test_async_get_totp_backup_codes_contract(async_client, mock_async_http_client):
    """Generated from POST /users/totp/backup-codes in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"backup_codes": ["x"]})
    result = await async_client.users.get_totp_backup_codes(password="x", totp_code="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/totp/backup-codes")
    assert sent.json == {"password": "x", "totp_code": "x"}
    assert result.to_dict() == {"backup_codes": ["x"]}


@pytest.mark.asyncio
async def test_async_proxy_login_contract(async_client, mock_async_http_client):
    """Generated from POST /users/proxy-login in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"enabled": False})
    result = await async_client.users.proxy_login()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/proxy-login")
    assert result.to_dict() == {"enabled": False}


@pytest.mark.asyncio
async def test_async_unlink_oidc_from_password_contract(async_client, mock_async_http_client):
    """Generated from POST /users/unlink-oidc-from-password in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True, "message": "x"})
    result = await async_client.users.unlink_oidc_from_password(userId="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/unlink-oidc-from-password")
    assert sent.json == {"userId": "x"}
    assert result.to_dict() == {"success": True, "message": "x"}


@pytest.mark.asyncio
async def test_async_link_oidc_to_password_contract(async_client, mock_async_http_client):
    """Generated from POST /users/link-oidc-to-password in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True, "message": "x"})
    result = await async_client.users.link_oidc_to_password(oidcUserId="x", targetUsername="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/link-oidc-to-password")
    assert sent.json == {"oidcUserId": "x", "targetUsername": "x"}
    assert result.to_dict() == {"success": True, "message": "x"}


@pytest.mark.asyncio
async def test_async_initiate_reset_contract(async_client, mock_async_http_client):
    """Generated from POST /users/initiate-reset in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "message": "Password reset code has been generated and logged. Check docker logs for the code."
        },
    )
    result = await async_client.users.initiate_reset(username="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/initiate-reset")
    assert sent.json == {"username": "x"}
    assert result.to_dict() == {
        "message": "Password reset code has been generated and logged. Check docker logs for the code."
    }


@pytest.mark.asyncio
async def test_async_verify_reset_code_contract(async_client, mock_async_http_client):
    """Generated from POST /users/verify-reset-code in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"message": "Reset code verified", "tempToken": "x"}
    )
    result = await async_client.users.verify_reset_code(username="x", resetCode="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/verify-reset-code")
    assert sent.json == {"username": "x", "resetCode": "x"}
    assert result.to_dict() == {"message": "Reset code verified", "tempToken": "x"}


@pytest.mark.asyncio
async def test_async_complete_reset_contract(async_client, mock_async_http_client):
    """Generated from POST /users/complete-reset in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"message": "Password has been successfully reset", "dataWiped": True}
    )
    result = await async_client.users.complete_reset(
        username="x", tempToken="x", newPassword="x", confirmDataWipe=True
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/complete-reset")
    assert sent.json == {
        "username": "x",
        "tempToken": "x",
        "newPassword": "x",
        "confirmDataWipe": True,
    }
    assert result.to_dict() == {
        "message": "Password has been successfully reset",
        "dataWiped": True,
    }


@pytest.mark.asyncio
async def test_async_list_sessions_contract(async_client, mock_async_http_client):
    """Generated from GET /users/sessions in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "sessions": [
                {
                    "id": "x",
                    "userId": "x",
                    "deviceType": "x",
                    "deviceInfo": "x",
                    "createdAt": "x",
                    "expiresAt": "x",
                    "lastActiveAt": "x",
                    "isRevoked": "x",
                    "isCurrentSession": True,
                }
            ]
        },
    )
    result = await async_client.users.list_sessions()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/sessions")
    assert result.to_dict() == {
        "sessions": [
            {
                "id": "x",
                "userId": "x",
                "deviceType": "x",
                "deviceInfo": "x",
                "createdAt": "x",
                "expiresAt": "x",
                "lastActiveAt": "x",
                "isRevoked": "x",
                "isCurrentSession": True,
            }
        ]
    }


@pytest.mark.asyncio
async def test_async_revoke_session_contract(async_client, mock_async_http_client):
    """Generated from DELETE /users/sessions/{sessionId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Session revoked successfully"}
    )
    result = await async_client.users.revoke_session("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/users/sessions/x")
    assert result.to_dict() == {"success": True, "message": "Session revoked successfully"}


@pytest.mark.asyncio
async def test_async_revoke_all_sessions_contract(async_client, mock_async_http_client):
    """Generated from POST /users/sessions/revoke-all in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"message": "x", "count": 1.0})
    result = await async_client.users.revoke_all_sessions(targetUserId="x", exceptCurrent=True)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/sessions/revoke-all")
    assert sent.json == {"targetUserId": "x", "exceptCurrent": True}
    assert result.to_dict() == {"message": "x", "count": 1.0}


@pytest.mark.asyncio
async def test_async_get_terminal_image_storage_settings_contract(
    async_client, mock_async_http_client
):
    """Generated from GET /users/terminal-image-storage-settings in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.users.get_terminal_image_storage_settings()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/users/terminal-image-storage-settings")
    assert result is not None


@pytest.mark.asyncio
async def test_async_update_terminal_image_storage_settings_contract(
    async_client, mock_async_http_client
):
    """Generated from PATCH /users/terminal-image-storage-settings in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.users.update_terminal_image_storage_settings(
        mode="local", localDir="x", hostPath="x", ttlMs=1.0, maxCount=1.0, maxBytes=1.0
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/users/terminal-image-storage-settings")
    assert sent.json == {
        "mode": "local",
        "localDir": "x",
        "hostPath": "x",
        "ttlMs": 1.0,
        "maxCount": 1.0,
        "maxBytes": 1.0,
    }
    assert result is not None


@pytest.mark.asyncio
async def test_async_test_terminal_image_storage_settings_contract(
    async_client, mock_async_http_client
):
    """Generated from POST /users/terminal-image-storage-settings/test in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "mode": "local",
            "connected": True,
            "remoteSftpAvailable": True,
            "localHostVisible": True,
            "selectedMode": "local",
            "localMappingConfigured": True,
        },
    )
    result = await async_client.users.test_terminal_image_storage_settings(instanceId="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/terminal-image-storage-settings/test")
    assert sent.json == {"instanceId": "x"}
    assert result.to_dict() == {
        "mode": "local",
        "connected": True,
        "remoteSftpAvailable": True,
        "localHostVisible": True,
        "selectedMode": "local",
        "localMappingConfigured": True,
    }


@pytest.mark.asyncio
async def test_async_register_contract(async_client, mock_async_http_client):
    """Generated from POST /users/create in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "message": "User created",
            "is_admin": True,
            "toast": {"type": "success", "message": "x"},
        },
    )
    result = await async_client.users.register(username="x", password="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/users/create")
    assert sent.json == {"username": "x", "password": "x"}
    assert result.to_dict() == {
        "message": "User created",
        "is_admin": True,
        "toast": {"type": "success", "message": "x"},
    }
