"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.system."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_health_contract(client, mock_http_client):
    """Generated from GET /health in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"status": "ok"})
    result = client.system.health()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/health")
    assert result.to_dict() == {"status": "ok"}


def test_version_contract(client, mock_http_client):
    """Generated from GET /version in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"localVersion": "x", "status": "unknown"}
    )
    result = client.system.version(checkRemote="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/version")
    assert sent.params == {"checkRemote": "x"}
    assert result.to_dict() == {"localVersion": "x", "status": "unknown"}


def test_list_releases_contract(client, mock_http_client):
    """Generated from GET /releases/rss in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "feed": {"title": "x", "description": "x", "link": "x", "updated": "x"},
            "items": [
                {
                    "id": 1.0,
                    "title": "x",
                    "description": "x",
                    "link": "x",
                    "pubDate": "x",
                    "version": "x",
                    "isPrerelease": True,
                    "isDraft": True,
                    "assets": [
                        {"name": "x", "size": "x", "download_count": "x", "download_url": "x"}
                    ],
                }
            ],
            "total_count": 1.0,
            "cached": True,
            "cache_age": 1.0,
        },
    )
    result = client.system.list_releases(page=1, per_page=1)
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/releases/rss")
    assert sent.params == {"page": 1, "per_page": 1}
    assert result.to_dict() == {
        "feed": {"title": "x", "description": "x", "link": "x", "updated": "x"},
        "items": [
            {
                "id": 1.0,
                "title": "x",
                "description": "x",
                "link": "x",
                "pubDate": "x",
                "version": "x",
                "isPrerelease": True,
                "isDraft": True,
                "assets": [{"name": "x", "size": "x", "download_count": "x", "download_url": "x"}],
            }
        ],
        "total_count": 1.0,
        "cached": True,
        "cache_age": 1.0,
    }


@pytest.mark.asyncio
async def test_async_health_contract(async_client, mock_async_http_client):
    """Generated from GET /health in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"status": "ok"})
    result = await async_client.system.health()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/health")
    assert result.to_dict() == {"status": "ok"}


@pytest.mark.asyncio
async def test_async_version_contract(async_client, mock_async_http_client):
    """Generated from GET /version in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"localVersion": "x", "status": "unknown"}
    )
    result = await async_client.system.version(checkRemote="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/version")
    assert sent.params == {"checkRemote": "x"}
    assert result.to_dict() == {"localVersion": "x", "status": "unknown"}


@pytest.mark.asyncio
async def test_async_list_releases_contract(async_client, mock_async_http_client):
    """Generated from GET /releases/rss in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "feed": {"title": "x", "description": "x", "link": "x", "updated": "x"},
            "items": [
                {
                    "id": 1.0,
                    "title": "x",
                    "description": "x",
                    "link": "x",
                    "pubDate": "x",
                    "version": "x",
                    "isPrerelease": True,
                    "isDraft": True,
                    "assets": [
                        {"name": "x", "size": "x", "download_count": "x", "download_url": "x"}
                    ],
                }
            ],
            "total_count": 1.0,
            "cached": True,
            "cache_age": 1.0,
        },
    )
    result = await async_client.system.list_releases(page=1, per_page=1)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/releases/rss")
    assert sent.params == {"page": 1, "per_page": 1}
    assert result.to_dict() == {
        "feed": {"title": "x", "description": "x", "link": "x", "updated": "x"},
        "items": [
            {
                "id": 1.0,
                "title": "x",
                "description": "x",
                "link": "x",
                "pubDate": "x",
                "version": "x",
                "isPrerelease": True,
                "isDraft": True,
                "assets": [{"name": "x", "size": "x", "download_count": "x", "download_url": "x"}],
            }
        ],
        "total_count": 1.0,
        "cached": True,
        "cache_age": 1.0,
    }
