"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.automations."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_list_contract(client, mock_http_client):
    """Generated from GET /automations in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=["x"])
    result = client.automations.list()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations")
    assert result == ["x"]


def test_create_contract(client, mock_http_client):
    """Generated from POST /automations in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"webhookToken": "x"})
    result = client.automations.create(
        name="x",
        description="x",
        enabled=True,
        definition="x",
        concurrencyPolicy="x",
        channels=[1.0],
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/automations")
    assert sent.json == {
        "name": "x",
        "description": "x",
        "enabled": True,
        "definition": "x",
        "concurrencyPolicy": "x",
        "channels": [1.0],
    }
    assert result.to_dict() == {"webhookToken": "x"}


def test_retrieve_contract(client, mock_http_client):
    """Generated from GET /automations/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.automations.retrieve("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations/x")
    assert result is not None


def test_update_contract(client, mock_http_client):
    """Generated from PUT /automations/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.automations.update(
        "x",
        name="x",
        description="x",
        enabled=True,
        concurrencyPolicy="x",
        channels=[1.0],
        definition="x",
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/automations/x")
    assert sent.json == {
        "name": "x",
        "description": "x",
        "enabled": True,
        "concurrencyPolicy": "x",
        "channels": [1.0],
        "definition": "x",
    }
    assert result is not None


def test_delete_contract(client, mock_http_client):
    """Generated from DELETE /automations/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.automations.delete("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/automations/x")
    assert result.to_dict() == {"success": True}


def test_run_contract(client, mock_http_client):
    """Generated from POST /automations/{id}/run in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"runId": 1.0, "status": "success", "error": "x"}
    )
    result = client.automations.run("x", dryRun=True)
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/automations/x/run")
    assert sent.json == {"dryRun": True}
    assert result.to_dict() == {"runId": 1.0, "status": "success", "error": "x"}


def test_list_run_history_contract(client, mock_http_client):
    """Generated from GET /automations/runs/history in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body=[
            {
                "id": 1.0,
                "automation_id": 1.0,
                "user_id": "x",
                "trigger_type": "x",
                "trigger_context": "x",
                "status": "x",
                "started_at": "x",
                "finished_at": "x",
                "duration_ms": 1.0,
                "error": "x",
                "dry_run": 1.0,
                "parent_run_id": 1.0,
                "automation_name": "x",
            }
        ],
    )
    result = client.automations.list_run_history(automationId="x", limit=1, offset=1)
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations/runs/history")
    assert sent.params == {"automationId": "x", "limit": 1, "offset": 1}
    assert len(result) == 1
    assert result[0].to_dict() == {
        "id": 1.0,
        "automation_id": 1.0,
        "user_id": "x",
        "trigger_type": "x",
        "trigger_context": "x",
        "status": "x",
        "started_at": "x",
        "finished_at": "x",
        "duration_ms": 1.0,
        "error": "x",
        "dry_run": 1.0,
        "parent_run_id": 1.0,
        "automation_name": "x",
    }


def test_list_run_steps_contract(client, mock_http_client):
    """Generated from GET /automations/runs/{runId}/steps in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body=[
            {
                "id": 1.0,
                "run_id": 1.0,
                "step_index": 1.0,
                "step_id": "x",
                "step_type": "x",
                "status": "x",
                "started_at": "x",
                "finished_at": "x",
                "output": "x",
                "error": "x",
                "truncated": 1.0,
            }
        ],
    )
    result = client.automations.list_run_steps("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations/runs/x/steps")
    assert len(result) == 1
    assert result[0].to_dict() == {
        "id": 1.0,
        "run_id": 1.0,
        "step_index": 1.0,
        "step_id": "x",
        "step_type": "x",
        "status": "x",
        "started_at": "x",
        "finished_at": "x",
        "output": "x",
        "error": "x",
        "truncated": 1.0,
    }


def test_trigger_webhook_contract(client, mock_http_client):
    """Generated from POST /automations/webhook/{token} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"x-contract-test-placeholder": True})
    result = client.automations.trigger_webhook("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/automations/webhook/x")
    assert result.to_dict() == {"x-contract-test-placeholder": True}


@pytest.mark.asyncio
async def test_async_list_contract(async_client, mock_async_http_client):
    """Generated from GET /automations in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=["x"])
    result = await async_client.automations.list()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations")
    assert result == ["x"]


@pytest.mark.asyncio
async def test_async_create_contract(async_client, mock_async_http_client):
    """Generated from POST /automations in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"webhookToken": "x"})
    result = await async_client.automations.create(
        name="x",
        description="x",
        enabled=True,
        definition="x",
        concurrencyPolicy="x",
        channels=[1.0],
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/automations")
    assert sent.json == {
        "name": "x",
        "description": "x",
        "enabled": True,
        "definition": "x",
        "concurrencyPolicy": "x",
        "channels": [1.0],
    }
    assert result.to_dict() == {"webhookToken": "x"}


@pytest.mark.asyncio
async def test_async_retrieve_contract(async_client, mock_async_http_client):
    """Generated from GET /automations/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.automations.retrieve("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations/x")
    assert result is not None


@pytest.mark.asyncio
async def test_async_update_contract(async_client, mock_async_http_client):
    """Generated from PUT /automations/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.automations.update(
        "x",
        name="x",
        description="x",
        enabled=True,
        concurrencyPolicy="x",
        channels=[1.0],
        definition="x",
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/automations/x")
    assert sent.json == {
        "name": "x",
        "description": "x",
        "enabled": True,
        "concurrencyPolicy": "x",
        "channels": [1.0],
        "definition": "x",
    }
    assert result is not None


@pytest.mark.asyncio
async def test_async_delete_contract(async_client, mock_async_http_client):
    """Generated from DELETE /automations/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.automations.delete("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/automations/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_run_contract(async_client, mock_async_http_client):
    """Generated from POST /automations/{id}/run in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"runId": 1.0, "status": "success", "error": "x"}
    )
    result = await async_client.automations.run("x", dryRun=True)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/automations/x/run")
    assert sent.json == {"dryRun": True}
    assert result.to_dict() == {"runId": 1.0, "status": "success", "error": "x"}


@pytest.mark.asyncio
async def test_async_list_run_history_contract(async_client, mock_async_http_client):
    """Generated from GET /automations/runs/history in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body=[
            {
                "id": 1.0,
                "automation_id": 1.0,
                "user_id": "x",
                "trigger_type": "x",
                "trigger_context": "x",
                "status": "x",
                "started_at": "x",
                "finished_at": "x",
                "duration_ms": 1.0,
                "error": "x",
                "dry_run": 1.0,
                "parent_run_id": 1.0,
                "automation_name": "x",
            }
        ],
    )
    result = await async_client.automations.list_run_history(automationId="x", limit=1, offset=1)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations/runs/history")
    assert sent.params == {"automationId": "x", "limit": 1, "offset": 1}
    assert len(result) == 1
    assert result[0].to_dict() == {
        "id": 1.0,
        "automation_id": 1.0,
        "user_id": "x",
        "trigger_type": "x",
        "trigger_context": "x",
        "status": "x",
        "started_at": "x",
        "finished_at": "x",
        "duration_ms": 1.0,
        "error": "x",
        "dry_run": 1.0,
        "parent_run_id": 1.0,
        "automation_name": "x",
    }


@pytest.mark.asyncio
async def test_async_list_run_steps_contract(async_client, mock_async_http_client):
    """Generated from GET /automations/runs/{runId}/steps in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body=[
            {
                "id": 1.0,
                "run_id": 1.0,
                "step_index": 1.0,
                "step_id": "x",
                "step_type": "x",
                "status": "x",
                "started_at": "x",
                "finished_at": "x",
                "output": "x",
                "error": "x",
                "truncated": 1.0,
            }
        ],
    )
    result = await async_client.automations.list_run_steps("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/automations/runs/x/steps")
    assert len(result) == 1
    assert result[0].to_dict() == {
        "id": 1.0,
        "run_id": 1.0,
        "step_index": 1.0,
        "step_id": "x",
        "step_type": "x",
        "status": "x",
        "started_at": "x",
        "finished_at": "x",
        "output": "x",
        "error": "x",
        "truncated": 1.0,
    }


@pytest.mark.asyncio
async def test_async_trigger_webhook_contract(async_client, mock_async_http_client):
    """Generated from POST /automations/webhook/{token} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"x-contract-test-placeholder": True}
    )
    result = await async_client.automations.trigger_webhook("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/automations/webhook/x")
    assert result.to_dict() == {"x-contract-test-placeholder": True}
