"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.sync."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_pull_contract(client, mock_http_client):
    """Generated from GET /sync/{entityType} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"rows": ["x"]})
    result = client.sync.pull("x", since="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/sync/x")
    assert sent.params == {"since": "x"}
    assert result.to_dict() == {"rows": ["x"]}


def test_push_contract(client, mock_http_client):
    """Generated from POST /sync/{entityType} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"row": "x", "created": True})
    result = client.sync.push("x", row="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/sync/x")
    assert sent.json == {"row": "x"}
    assert result.to_dict() == {"row": "x", "created": True}


def test_push_tombstones_contract(client, mock_http_client):
    """Generated from POST /sync/tombstones in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.sync.push_tombstones(entityType="x", syncId="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/sync/tombstones")
    assert sent.json == {"entityType": "x", "syncId": "x"}
    assert result.to_dict() == {"success": True}


def test_pull_tombstones_contract(client, mock_http_client):
    """Generated from GET /sync/{entityType}/tombstones in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"tombstones": [{}]})
    result = client.sync.pull_tombstones("x", since="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/sync/x/tombstones")
    assert sent.params == {"since": "x"}
    assert result.to_dict() == {"tombstones": [{}]}


@pytest.mark.asyncio
async def test_async_pull_contract(async_client, mock_async_http_client):
    """Generated from GET /sync/{entityType} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"rows": ["x"]})
    result = await async_client.sync.pull("x", since="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/sync/x")
    assert sent.params == {"since": "x"}
    assert result.to_dict() == {"rows": ["x"]}


@pytest.mark.asyncio
async def test_async_push_contract(async_client, mock_async_http_client):
    """Generated from POST /sync/{entityType} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"row": "x", "created": True})
    result = await async_client.sync.push("x", row="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/sync/x")
    assert sent.json == {"row": "x"}
    assert result.to_dict() == {"row": "x", "created": True}


@pytest.mark.asyncio
async def test_async_push_tombstones_contract(async_client, mock_async_http_client):
    """Generated from POST /sync/tombstones in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.sync.push_tombstones(entityType="x", syncId="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/sync/tombstones")
    assert sent.json == {"entityType": "x", "syncId": "x"}
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_pull_tombstones_contract(async_client, mock_async_http_client):
    """Generated from GET /sync/{entityType}/tombstones in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"tombstones": [{}]})
    result = await async_client.sync.pull_tombstones("x", since="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/sync/x/tombstones")
    assert sent.params == {"since": "x"}
    assert result.to_dict() == {"tombstones": [{}]}
