"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.open_tabs."""

from __future__ import annotations

import pytest


def test_upsert_contract(client, mock_http_client):
    """Generated from POST /open-tabs in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.open_tabs.upsert(
        id="x", tabType="x", hostId=1.0, label="x", tabOrder=1.0, backendSessionId="x"
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/open-tabs")
    assert sent.json == {
        "id": "x",
        "tabType": "x",
        "hostId": 1.0,
        "label": "x",
        "tabOrder": 1.0,
        "backendSessionId": "x",
    }
    assert result.to_dict() == {"success": True}


def test_replace_all_contract(client, mock_http_client):
    """Generated from PUT /open-tabs in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.open_tabs.replace_all(tabs=[])
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/open-tabs")
    assert sent.json == {"tabs": []}
    assert result.to_dict() == {"success": True}


def test_list_contract(client, mock_http_client):
    """Generated from GET /open-tabs in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=[{"tabType": "x"}])
    result = client.open_tabs.list()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/open-tabs")
    assert len(result) == 1
    assert result[0].to_dict() == {"tabType": "x"}


def test_update_contract(client, mock_http_client):
    """Generated from PATCH /open-tabs/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.open_tabs.update("x", hostId=1.0, label="x", tabOrder=1.0, backendSessionId="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/open-tabs/x")
    assert sent.json == {"hostId": 1.0, "label": "x", "tabOrder": 1.0, "backendSessionId": "x"}
    assert result.to_dict() == {"success": True}


def test_delete_contract(client, mock_http_client):
    """Generated from DELETE /open-tabs/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.open_tabs.delete("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/open-tabs/x")
    assert result.to_dict() == {"success": True}


def test_list_active_sessions_contract(client, mock_http_client):
    """Generated from GET /open-tabs/active-sessions in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body=[
            {
                "sessionId": "x",
                "hostId": 1.0,
                "hostName": "x",
                "tabInstanceId": "x",
                "isConnected": True,
                "createdAt": 1.0,
                "isOwnSession": True,
                "sharedByUsername": "x",
                "permissionLevel": "x",
                "shareId": "x",
            }
        ],
    )
    result = client.open_tabs.list_active_sessions()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/open-tabs/active-sessions")
    assert len(result) == 1
    assert result[0].to_dict() == {
        "sessionId": "x",
        "hostId": 1.0,
        "hostName": "x",
        "tabInstanceId": "x",
        "isConnected": True,
        "createdAt": 1.0,
        "isOwnSession": True,
        "sharedByUsername": "x",
        "permissionLevel": "x",
        "shareId": "x",
    }


@pytest.mark.asyncio
async def test_async_upsert_contract(async_client, mock_async_http_client):
    """Generated from POST /open-tabs in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.open_tabs.upsert(
        id="x", tabType="x", hostId=1.0, label="x", tabOrder=1.0, backendSessionId="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/open-tabs")
    assert sent.json == {
        "id": "x",
        "tabType": "x",
        "hostId": 1.0,
        "label": "x",
        "tabOrder": 1.0,
        "backendSessionId": "x",
    }
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_replace_all_contract(async_client, mock_async_http_client):
    """Generated from PUT /open-tabs in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.open_tabs.replace_all(tabs=[])
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/open-tabs")
    assert sent.json == {"tabs": []}
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_list_contract(async_client, mock_async_http_client):
    """Generated from GET /open-tabs in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=[{"tabType": "x"}])
    result = await async_client.open_tabs.list()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/open-tabs")
    assert len(result) == 1
    assert result[0].to_dict() == {"tabType": "x"}


@pytest.mark.asyncio
async def test_async_update_contract(async_client, mock_async_http_client):
    """Generated from PATCH /open-tabs/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.open_tabs.update(
        "x", hostId=1.0, label="x", tabOrder=1.0, backendSessionId="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/open-tabs/x")
    assert sent.json == {"hostId": 1.0, "label": "x", "tabOrder": 1.0, "backendSessionId": "x"}
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_delete_contract(async_client, mock_async_http_client):
    """Generated from DELETE /open-tabs/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.open_tabs.delete("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/open-tabs/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_list_active_sessions_contract(async_client, mock_async_http_client):
    """Generated from GET /open-tabs/active-sessions in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body=[
            {
                "sessionId": "x",
                "hostId": 1.0,
                "hostName": "x",
                "tabInstanceId": "x",
                "isConnected": True,
                "createdAt": 1.0,
                "isOwnSession": True,
                "sharedByUsername": "x",
                "permissionLevel": "x",
                "shareId": "x",
            }
        ],
    )
    result = await async_client.open_tabs.list_active_sessions()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/open-tabs/active-sessions")
    assert len(result) == 1
    assert result[0].to_dict() == {
        "sessionId": "x",
        "hostId": 1.0,
        "hostName": "x",
        "tabInstanceId": "x",
        "isConnected": True,
        "createdAt": 1.0,
        "isOwnSession": True,
        "sharedByUsername": "x",
        "permissionLevel": "x",
        "shareId": "x",
    }
