"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.termix_id."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_get_ca_contract(client, mock_http_client):
    """Generated from GET /termix-id/ca in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"ca": {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}}
    )
    result = client.termix_id.get_ca()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/ca")
    assert result.to_dict() == {"ca": {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}}


def test_create_ca_contract(client, mock_http_client):
    """Generated from POST /termix-id/ca in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}
    )
    result = client.termix_id.create_ca(validityDays=1)
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/ca")
    assert sent.json == {"validityDays": 1}
    assert result.to_dict() == {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}


def test_delete_ca_contract(client, mock_http_client):
    """Generated from DELETE /termix-id/ca in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.termix_id.delete_ca()
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/termix-id/ca")
    assert result.to_dict() == {"success": True}


def test_rotate_ca_contract(client, mock_http_client):
    """Generated from POST /termix-id/ca/rotate in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}
    )
    result = client.termix_id.rotate_ca(validityDays=1)
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/ca/rotate")
    assert sent.json == {"validityDays": 1}
    assert result.to_dict() == {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}


def test_issue_certificate_contract(client, mock_http_client):
    """Generated from POST /termix-id/keys/{id}/certificate in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "certificate": "x",
            "keyId": "x",
            "validBefore": 1.0,
            "principals": "x",
            "validityDays": 1.0,
        },
    )
    result = client.termix_id.issue_certificate("x", validityDays=1.0, principals=["x"])
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/keys/x/certificate")
    assert sent.json == {"validityDays": 1.0, "principals": ["x"]}
    assert result.to_dict() == {
        "certificate": "x",
        "keyId": "x",
        "validBefore": 1.0,
        "principals": "x",
        "validityDays": 1.0,
    }


def test_list_linked_credentials_contract(client, mock_http_client):
    """Generated from GET /termix-id/linked-credentials in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"credentialIds": [1.0]})
    result = client.termix_id.list_linked_credentials()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/linked-credentials")
    assert result.to_dict() == {"credentialIds": [1.0]}


def test_get_public_ca_contract(client, mock_http_client):
    """Generated from GET /termix-id/u/{handle}/ca in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = client.termix_id.get_public_ca("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/u/x/ca")
    assert result.read() == b"binary-content-placeholder"


def test_get_public_identity_contract(client, mock_http_client):
    """Generated from GET /termix-id/u/{handle} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = client.termix_id.get_public_identity("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/u/x")
    assert result.read() == b"binary-content-placeholder"


def test_get_public_key_contract(client, mock_http_client):
    """Generated from GET /termix-id/u/{handle}/{algo} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = client.termix_id.get_public_key("x", "x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/u/x/x")
    assert result.read() == b"binary-content-placeholder"


def test_get_me_contract(client, mock_http_client):
    """Generated from GET /termix-id/me in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"identity": {"resolverPath": "x"}, "keys": [{}]}
    )
    result = client.termix_id.get_me()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/me")
    assert result.to_dict() == {"identity": {"resolverPath": "x"}, "keys": [{}]}


def test_check_handle_contract(client, mock_http_client):
    """Generated from GET /termix-id/check/{handle} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"available": True, "valid": True})
    result = client.termix_id.check_handle("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/check/x")
    assert result.to_dict() == {"available": True, "valid": True}


def test_create_contract(client, mock_http_client):
    """Generated from POST /termix-id in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.termix_id.create(handle="x", description="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id")
    assert sent.json == {"handle": "x", "description": "x"}
    assert result is not None


def test_update_contract(client, mock_http_client):
    """Generated from PUT /termix-id in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.termix_id.update(handle="x", description="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/termix-id")
    assert sent.json == {"handle": "x", "description": "x"}
    assert result is not None


def test_delete_contract(client, mock_http_client):
    """Generated from DELETE /termix-id in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.termix_id.delete()
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/termix-id")
    assert result.to_dict() == {"success": True}


def test_create_key_contract(client, mock_http_client):
    """Generated from POST /termix-id/keys in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.termix_id.create_key(label="x", credentialId=1, publicKey="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/keys")
    assert sent.json == {"label": "x", "credentialId": 1, "publicKey": "x"}
    assert result is not None


def test_generate_key_contract(client, mock_http_client):
    """Generated from POST /termix-id/keys/generate in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"key": {}, "privateKey": "x", "publicKey": "x", "credentialId": 1.0}
    )
    result = client.termix_id.generate_key(
        type="ed25519", label="x", saveCredential=True, username="x"
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/keys/generate")
    assert sent.json == {"type": "ed25519", "label": "x", "saveCredential": True, "username": "x"}
    assert result.to_dict() == {"key": {}, "privateKey": "x", "publicKey": "x", "credentialId": 1.0}


def test_update_key_contract(client, mock_http_client):
    """Generated from PATCH /termix-id/keys/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.termix_id.update_key("x", enabled=True, label="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/termix-id/keys/x")
    assert sent.json == {"enabled": True, "label": "x"}
    assert result is not None


def test_delete_key_contract(client, mock_http_client):
    """Generated from DELETE /termix-id/keys/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.termix_id.delete_key("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/termix-id/keys/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_get_ca_contract(async_client, mock_async_http_client):
    """Generated from GET /termix-id/ca in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"ca": {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}}
    )
    result = await async_client.termix_id.get_ca()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/ca")
    assert result.to_dict() == {"ca": {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}}


@pytest.mark.asyncio
async def test_async_create_ca_contract(async_client, mock_async_http_client):
    """Generated from POST /termix-id/ca in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}
    )
    result = await async_client.termix_id.create_ca(validityDays=1)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/ca")
    assert sent.json == {"validityDays": 1}
    assert result.to_dict() == {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}


@pytest.mark.asyncio
async def test_async_delete_ca_contract(async_client, mock_async_http_client):
    """Generated from DELETE /termix-id/ca in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.termix_id.delete_ca()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/termix-id/ca")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_rotate_ca_contract(async_client, mock_async_http_client):
    """Generated from POST /termix-id/ca/rotate in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}
    )
    result = await async_client.termix_id.rotate_ca(validityDays=1)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/ca/rotate")
    assert sent.json == {"validityDays": 1}
    assert result.to_dict() == {"publicKey": "x", "validityDays": 1.0, "resolverPath": "x"}


@pytest.mark.asyncio
async def test_async_issue_certificate_contract(async_client, mock_async_http_client):
    """Generated from POST /termix-id/keys/{id}/certificate in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "certificate": "x",
            "keyId": "x",
            "validBefore": 1.0,
            "principals": "x",
            "validityDays": 1.0,
        },
    )
    result = await async_client.termix_id.issue_certificate("x", validityDays=1.0, principals=["x"])
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/keys/x/certificate")
    assert sent.json == {"validityDays": 1.0, "principals": ["x"]}
    assert result.to_dict() == {
        "certificate": "x",
        "keyId": "x",
        "validBefore": 1.0,
        "principals": "x",
        "validityDays": 1.0,
    }


@pytest.mark.asyncio
async def test_async_list_linked_credentials_contract(async_client, mock_async_http_client):
    """Generated from GET /termix-id/linked-credentials in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"credentialIds": [1.0]})
    result = await async_client.termix_id.list_linked_credentials()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/linked-credentials")
    assert result.to_dict() == {"credentialIds": [1.0]}


@pytest.mark.asyncio
async def test_async_get_public_ca_contract(async_client, mock_async_http_client):
    """Generated from GET /termix-id/u/{handle}/ca in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = await async_client.termix_id.get_public_ca("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/u/x/ca")
    assert await result.read() == b"binary-content-placeholder"


@pytest.mark.asyncio
async def test_async_get_public_identity_contract(async_client, mock_async_http_client):
    """Generated from GET /termix-id/u/{handle} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = await async_client.termix_id.get_public_identity("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/u/x")
    assert await result.read() == b"binary-content-placeholder"


@pytest.mark.asyncio
async def test_async_get_public_key_contract(async_client, mock_async_http_client):
    """Generated from GET /termix-id/u/{handle}/{algo} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = await async_client.termix_id.get_public_key("x", "x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/u/x/x")
    assert await result.read() == b"binary-content-placeholder"


@pytest.mark.asyncio
async def test_async_get_me_contract(async_client, mock_async_http_client):
    """Generated from GET /termix-id/me in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"identity": {"resolverPath": "x"}, "keys": [{}]}
    )
    result = await async_client.termix_id.get_me()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/me")
    assert result.to_dict() == {"identity": {"resolverPath": "x"}, "keys": [{}]}


@pytest.mark.asyncio
async def test_async_check_handle_contract(async_client, mock_async_http_client):
    """Generated from GET /termix-id/check/{handle} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"available": True, "valid": True})
    result = await async_client.termix_id.check_handle("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/termix-id/check/x")
    assert result.to_dict() == {"available": True, "valid": True}


@pytest.mark.asyncio
async def test_async_create_contract(async_client, mock_async_http_client):
    """Generated from POST /termix-id in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.termix_id.create(handle="x", description="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id")
    assert sent.json == {"handle": "x", "description": "x"}
    assert result is not None


@pytest.mark.asyncio
async def test_async_update_contract(async_client, mock_async_http_client):
    """Generated from PUT /termix-id in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.termix_id.update(handle="x", description="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/termix-id")
    assert sent.json == {"handle": "x", "description": "x"}
    assert result is not None


@pytest.mark.asyncio
async def test_async_delete_contract(async_client, mock_async_http_client):
    """Generated from DELETE /termix-id in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.termix_id.delete()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/termix-id")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_create_key_contract(async_client, mock_async_http_client):
    """Generated from POST /termix-id/keys in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.termix_id.create_key(label="x", credentialId=1, publicKey="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/keys")
    assert sent.json == {"label": "x", "credentialId": 1, "publicKey": "x"}
    assert result is not None


@pytest.mark.asyncio
async def test_async_generate_key_contract(async_client, mock_async_http_client):
    """Generated from POST /termix-id/keys/generate in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"key": {}, "privateKey": "x", "publicKey": "x", "credentialId": 1.0}
    )
    result = await async_client.termix_id.generate_key(
        type="ed25519", label="x", saveCredential=True, username="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/termix-id/keys/generate")
    assert sent.json == {"type": "ed25519", "label": "x", "saveCredential": True, "username": "x"}
    assert result.to_dict() == {"key": {}, "privateKey": "x", "publicKey": "x", "credentialId": 1.0}


@pytest.mark.asyncio
async def test_async_update_key_contract(async_client, mock_async_http_client):
    """Generated from PATCH /termix-id/keys/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.termix_id.update_key("x", enabled=True, label="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/termix-id/keys/x")
    assert sent.json == {"enabled": True, "label": "x"}
    assert result is not None


@pytest.mark.asyncio
async def test_async_delete_key_contract(async_client, mock_async_http_client):
    """Generated from DELETE /termix-id/keys/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.termix_id.delete_key("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/termix-id/keys/x")
    assert result.to_dict() == {"success": True}
