"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.tailscale."""

from __future__ import annotations

import pytest


def test_list_devices_contract(client, mock_http_client):
    """Generated from GET /tailscale/devices in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "devices": [
                {
                    "id": "x",
                    "name": "x",
                    "hostname": "x",
                    "addresses": ["x"],
                    "os": "x",
                    "lastSeen": "x",
                }
            ],
            "hasApiKey": True,
        },
    )
    result = client.tailscale.list_devices()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/tailscale/devices")
    assert result.to_dict() == {
        "devices": [
            {
                "id": "x",
                "name": "x",
                "hostname": "x",
                "addresses": ["x"],
                "os": "x",
                "lastSeen": "x",
            }
        ],
        "hasApiKey": True,
    }


@pytest.mark.asyncio
async def test_async_list_devices_contract(async_client, mock_async_http_client):
    """Generated from GET /tailscale/devices in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "devices": [
                {
                    "id": "x",
                    "name": "x",
                    "hostname": "x",
                    "addresses": ["x"],
                    "os": "x",
                    "lastSeen": "x",
                }
            ],
            "hasApiKey": True,
        },
    )
    result = await async_client.tailscale.list_devices()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/tailscale/devices")
    assert result.to_dict() == {
        "devices": [
            {
                "id": "x",
                "name": "x",
                "hostname": "x",
                "addresses": ["x"],
                "os": "x",
                "lastSeen": "x",
            }
        ],
        "hasApiKey": True,
    }
