"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.ai."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_create_provider_contract(client, mock_http_client):
    """Generated from POST /ai/providers in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"provider": {}})
    result = client.ai.create_provider(
        providerType="x", label="x", baseUrl="x", apiKey="x", defaultModel="x"
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/providers")
    assert sent.json == {
        "providerType": "x",
        "label": "x",
        "baseUrl": "x",
        "apiKey": "x",
        "defaultModel": "x",
    }
    assert result.to_dict() == {"provider": {}}


def test_list_providers_contract(client, mock_http_client):
    """Generated from GET /ai/providers in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"providers": [{}]})
    result = client.ai.list_providers()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/providers")
    assert result.to_dict() == {"providers": [{}]}


def test_update_provider_contract(client, mock_http_client):
    """Generated from PATCH /ai/providers/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"provider": {}})
    result = client.ai.update_provider(
        "x", label="x", baseUrl="x", apiKey="x", defaultModel="x", enabled=True
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/ai/providers/x")
    assert sent.json == {
        "label": "x",
        "baseUrl": "x",
        "apiKey": "x",
        "defaultModel": "x",
        "enabled": True,
    }
    assert result.to_dict() == {"provider": {}}


def test_delete_provider_contract(client, mock_http_client):
    """Generated from DELETE /ai/providers/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.ai.delete_provider("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/ai/providers/x")
    assert result.to_dict() == {"success": True}


def test_probe_models_contract(client, mock_http_client):
    """Generated from POST /ai/probe-models in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"models": ["x"], "source": "live"})
    result = client.ai.probe_models(providerType="x", baseUrl="x", apiKey="x", providerId=1)
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/probe-models")
    assert sent.json == {"providerType": "x", "baseUrl": "x", "apiKey": "x", "providerId": 1}
    assert result.to_dict() == {"models": ["x"], "source": "live"}


def test_list_provider_models_contract(client, mock_http_client):
    """Generated from GET /ai/providers/{id}/models in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"models": ["x"]})
    result = client.ai.list_provider_models("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/providers/x/models")
    assert result.to_dict() == {"models": ["x"]}


def test_list_conversations_contract(client, mock_http_client):
    """Generated from GET /ai/conversations in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"conversations": [{}]})
    result = client.ai.list_conversations()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/conversations")
    assert result.to_dict() == {"conversations": [{}]}


def test_get_conversation_contract(client, mock_http_client):
    """Generated from GET /ai/conversations/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"conversation": {}, "messages": [{}], "proposals": [{}]}
    )
    result = client.ai.get_conversation("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/conversations/x")
    assert result.to_dict() == {"conversation": {}, "messages": [{}], "proposals": [{}]}


def test_delete_conversation_contract(client, mock_http_client):
    """Generated from DELETE /ai/conversations/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.ai.delete_conversation("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/ai/conversations/x")
    assert result.to_dict() == {"success": True}


def test_get_status_contract(client, mock_http_client):
    """Generated from GET /ai/status in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={"globallyEnabled": True, "enabled": True, "allowReadOnlyCommands": True},
    )
    result = client.ai.get_status()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/status")
    assert result.to_dict() == {
        "globallyEnabled": True,
        "enabled": True,
        "allowReadOnlyCommands": True,
    }


def test_apply_proposal_contract(client, mock_http_client):
    """Generated from POST /ai/proposals/{id}/apply in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True, "summary": "x"})
    result = client.ai.apply_proposal("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/proposals/x/apply")
    assert result.to_dict() == {"success": True, "summary": "x"}


def test_reject_proposal_contract(client, mock_http_client):
    """Generated from POST /ai/proposals/{id}/reject in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.ai.reject_proposal("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/proposals/x/reject")
    assert result.to_dict() == {"success": True}


def test_chat_stream_contract(client, mock_http_client):
    """Generated from POST /ai/chat/stream in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=b'event: message\ndata: {"ok": true}\n\n')
    result = client.ai.chat_stream(
        conversationId=1, providerId=1, model="x", message="x", activeTab="x"
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/chat/stream")
    assert sent.json == {
        "conversationId": 1,
        "providerId": 1,
        "model": "x",
        "message": "x",
        "activeTab": "x",
    }
    events = list(result)
    assert events[0].event == "message"
    assert events[0].json() == {"ok": True}


@pytest.mark.asyncio
async def test_async_create_provider_contract(async_client, mock_async_http_client):
    """Generated from POST /ai/providers in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"provider": {}})
    result = await async_client.ai.create_provider(
        providerType="x", label="x", baseUrl="x", apiKey="x", defaultModel="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/providers")
    assert sent.json == {
        "providerType": "x",
        "label": "x",
        "baseUrl": "x",
        "apiKey": "x",
        "defaultModel": "x",
    }
    assert result.to_dict() == {"provider": {}}


@pytest.mark.asyncio
async def test_async_list_providers_contract(async_client, mock_async_http_client):
    """Generated from GET /ai/providers in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"providers": [{}]})
    result = await async_client.ai.list_providers()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/providers")
    assert result.to_dict() == {"providers": [{}]}


@pytest.mark.asyncio
async def test_async_update_provider_contract(async_client, mock_async_http_client):
    """Generated from PATCH /ai/providers/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"provider": {}})
    result = await async_client.ai.update_provider(
        "x", label="x", baseUrl="x", apiKey="x", defaultModel="x", enabled=True
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/ai/providers/x")
    assert sent.json == {
        "label": "x",
        "baseUrl": "x",
        "apiKey": "x",
        "defaultModel": "x",
        "enabled": True,
    }
    assert result.to_dict() == {"provider": {}}


@pytest.mark.asyncio
async def test_async_delete_provider_contract(async_client, mock_async_http_client):
    """Generated from DELETE /ai/providers/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.ai.delete_provider("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/ai/providers/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_probe_models_contract(async_client, mock_async_http_client):
    """Generated from POST /ai/probe-models in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"models": ["x"], "source": "live"})
    result = await async_client.ai.probe_models(
        providerType="x", baseUrl="x", apiKey="x", providerId=1
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/probe-models")
    assert sent.json == {"providerType": "x", "baseUrl": "x", "apiKey": "x", "providerId": 1}
    assert result.to_dict() == {"models": ["x"], "source": "live"}


@pytest.mark.asyncio
async def test_async_list_provider_models_contract(async_client, mock_async_http_client):
    """Generated from GET /ai/providers/{id}/models in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"models": ["x"]})
    result = await async_client.ai.list_provider_models("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/providers/x/models")
    assert result.to_dict() == {"models": ["x"]}


@pytest.mark.asyncio
async def test_async_list_conversations_contract(async_client, mock_async_http_client):
    """Generated from GET /ai/conversations in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"conversations": [{}]})
    result = await async_client.ai.list_conversations()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/conversations")
    assert result.to_dict() == {"conversations": [{}]}


@pytest.mark.asyncio
async def test_async_get_conversation_contract(async_client, mock_async_http_client):
    """Generated from GET /ai/conversations/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"conversation": {}, "messages": [{}], "proposals": [{}]}
    )
    result = await async_client.ai.get_conversation("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/conversations/x")
    assert result.to_dict() == {"conversation": {}, "messages": [{}], "proposals": [{}]}


@pytest.mark.asyncio
async def test_async_delete_conversation_contract(async_client, mock_async_http_client):
    """Generated from DELETE /ai/conversations/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.ai.delete_conversation("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/ai/conversations/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_get_status_contract(async_client, mock_async_http_client):
    """Generated from GET /ai/status in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={"globallyEnabled": True, "enabled": True, "allowReadOnlyCommands": True},
    )
    result = await async_client.ai.get_status()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/ai/status")
    assert result.to_dict() == {
        "globallyEnabled": True,
        "enabled": True,
        "allowReadOnlyCommands": True,
    }


@pytest.mark.asyncio
async def test_async_apply_proposal_contract(async_client, mock_async_http_client):
    """Generated from POST /ai/proposals/{id}/apply in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True, "summary": "x"})
    result = await async_client.ai.apply_proposal("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/proposals/x/apply")
    assert result.to_dict() == {"success": True, "summary": "x"}


@pytest.mark.asyncio
async def test_async_reject_proposal_contract(async_client, mock_async_http_client):
    """Generated from POST /ai/proposals/{id}/reject in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.ai.reject_proposal("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/proposals/x/reject")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_chat_stream_contract(async_client, mock_async_http_client):
    """Generated from POST /ai/chat/stream in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body=b'event: message\ndata: {"ok": true}\n\n'
    )
    result = await async_client.ai.chat_stream(
        conversationId=1, providerId=1, model="x", message="x", activeTab="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/ai/chat/stream")
    assert sent.json == {
        "conversationId": 1,
        "providerId": 1,
        "model": "x",
        "message": "x",
        "activeTab": "x",
    }
    events = [e async for e in result]
    assert events[0].event == "message"
    assert events[0].json() == {"ok": True}
