"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.rbac."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_list_roles_contract(client, mock_http_client):
    """Generated from GET /rbac/roles in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "roles": [
                {
                    "id": 1.0,
                    "name": "x",
                    "displayName": "x",
                    "description": "x",
                    "isSystem": True,
                    "permissions": ["x"],
                    "createdAt": "x",
                    "updatedAt": "x",
                }
            ]
        },
    )
    result = client.rbac.list_roles()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/roles")
    assert result.to_dict() == {
        "roles": [
            {
                "id": 1.0,
                "name": "x",
                "displayName": "x",
                "description": "x",
                "isSystem": True,
                "permissions": ["x"],
                "createdAt": "x",
                "updatedAt": "x",
            }
        ]
    }


def test_create_role_contract(client, mock_http_client):
    """Generated from POST /rbac/roles in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={"success": True, "roleId": 1.0, "message": "Role created successfully"},
    )
    result = client.rbac.create_role(name="x", displayName="x", description="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/roles")
    assert sent.json == {"name": "x", "displayName": "x", "description": "x"}
    assert result.to_dict() == {
        "success": True,
        "roleId": 1.0,
        "message": "Role created successfully",
    }


def test_update_role_contract(client, mock_http_client):
    """Generated from PUT /rbac/roles/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role updated successfully"}
    )
    result = client.rbac.update_role("x", displayName="x", description="x", permissions=[])
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/rbac/roles/x")
    assert sent.json == {"displayName": "x", "description": "x", "permissions": []}
    assert result.to_dict() == {"success": True, "message": "Role updated successfully"}


def test_delete_role_contract(client, mock_http_client):
    """Generated from DELETE /rbac/roles/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role deleted successfully"}
    )
    result = client.rbac.delete_role("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/roles/x")
    assert result.to_dict() == {"success": True, "message": "Role deleted successfully"}


def test_permissions_catalog_contract(client, mock_http_client):
    """Generated from GET /rbac/permissions/catalog in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"catalog": [{"group": "x", "permissions": ["x"]}]}
    )
    result = client.rbac.permissions_catalog()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/permissions/catalog")
    assert result.to_dict() == {"catalog": [{"group": "x", "permissions": ["x"]}]}


def test_assign_role_contract(client, mock_http_client):
    """Generated from POST /rbac/users/{userId}/roles in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role assigned successfully"}
    )
    result = client.rbac.assign_role("x", roleId=1.0)
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/users/x/roles")
    assert sent.json == {"roleId": 1.0}
    assert result.to_dict() == {"success": True, "message": "Role assigned successfully"}


def test_list_user_roles_contract(client, mock_http_client):
    """Generated from GET /rbac/users/{userId}/roles in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"roles": [{}]})
    result = client.rbac.list_user_roles("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/users/x/roles")
    assert result.to_dict() == {"roles": [{}]}


def test_revoke_role_contract(client, mock_http_client):
    """Generated from DELETE /rbac/users/{userId}/roles/{roleId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role removed successfully"}
    )
    result = client.rbac.revoke_role("x", "x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/users/x/roles/x")
    assert result.to_dict() == {"success": True, "message": "Role removed successfully"}


def test_share_snippet_contract(client, mock_http_client):
    """Generated from POST /rbac/snippet/{id}/share in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "x", "expiresAt": "x"}
    )
    result = client.rbac.share_snippet(
        "x", targetType="user", targetUserId="x", targetRoleId=1.0, durationHours=1.0
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/snippet/x/share")
    assert sent.json == {
        "targetType": "user",
        "targetUserId": "x",
        "targetRoleId": 1.0,
        "durationHours": 1.0,
    }
    assert result.to_dict() == {"success": True, "message": "x", "expiresAt": "x"}


def test_share_host_contract(client, mock_http_client):
    """Generated from POST /rbac/host/{id}/share in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "Host shared successfully",
            "permissionLevel": "manage",
            "expiresAt": "x",
            "results": [{"type": "role", "id": "x", "accessId": 1.0, "created": True}],
        },
    )
    result = client.rbac.share_host("x", durationHours="x", permissionLevel="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/host/x/share")
    assert sent.json == {"durationHours": "x", "permissionLevel": "x"}
    assert result.to_dict() == {
        "success": True,
        "message": "Host shared successfully",
        "permissionLevel": "manage",
        "expiresAt": "x",
        "results": [{"type": "role", "id": "x", "accessId": 1.0, "created": True}],
    }


def test_delete_snippet_access_contract(client, mock_http_client):
    """Generated from DELETE /rbac/snippet/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Snippet access revoked"}
    )
    result = client.rbac.delete_snippet_access("x", "x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/snippet/x/access/x")
    assert result.to_dict() == {"success": True, "message": "Snippet access revoked"}


def test_list_snippet_access_contract(client, mock_http_client):
    """Generated from GET /rbac/snippet/{id}/access in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "accessList": [
                {
                    "id": 1.0,
                    "targetType": "role",
                    "userId": "x",
                    "roleId": 1.0,
                    "username": "x",
                    "roleName": "x",
                    "roleDisplayName": "x",
                    "grantedBy": "x",
                    "grantedByUsername": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                    "createdAt": "x",
                }
            ]
        },
    )
    result = client.rbac.list_snippet_access("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/snippet/x/access")
    assert result.to_dict() == {
        "accessList": [
            {
                "id": 1.0,
                "targetType": "role",
                "userId": "x",
                "roleId": 1.0,
                "username": "x",
                "roleName": "x",
                "roleDisplayName": "x",
                "grantedBy": "x",
                "grantedByUsername": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
                "createdAt": "x",
            }
        ]
    }


def test_list_shared_snippets_contract(client, mock_http_client):
    """Generated from GET /rbac/shared-snippets in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "sharedSnippets": [
                {
                    "id": 1.0,
                    "name": "x",
                    "content": "x",
                    "description": "x",
                    "folder": "x",
                    "ownerUsername": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                }
            ]
        },
    )
    result = client.rbac.list_shared_snippets()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/shared-snippets")
    assert result.to_dict() == {
        "sharedSnippets": [
            {
                "id": 1.0,
                "name": "x",
                "content": "x",
                "description": "x",
                "folder": "x",
                "ownerUsername": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
            }
        ]
    }


def test_set_host_access_auth_contract(client, mock_http_client):
    """Generated from PUT /rbac/host-access/{hostId}/auth/{protocol} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "protocol": "ssh", "credentialId": "x"}
    )
    result = client.rbac.set_host_access_auth("x", "x", credentialId="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/rbac/host-access/x/auth/x")
    assert sent.json == {"credentialId": "x"}
    assert result.to_dict() == {"success": True, "protocol": "ssh", "credentialId": "x"}


def test_get_host_access_auth_contract(client, mock_http_client):
    """Generated from GET /rbac/host-access/{hostId}/auth/{protocol} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"protocol": "ssh", "credentialId": 1.0})
    result = client.rbac.get_host_access_auth("x", "x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/host-access/x/auth/x")
    assert result.to_dict() == {"protocol": "ssh", "credentialId": 1.0}


def test_share_folder_contract(client, mock_http_client):
    """Generated from POST /rbac/folder/share in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "Folder shared successfully",
            "permissionLevel": "manage",
            "expiresAt": "x",
            "hostsShared": 1.0,
            "hostsTotal": 1.0,
            "hostResults": [{"hostId": 1.0, "shared": True, "reason": "x"}],
        },
    )
    result = client.rbac.share_folder(folder="x", durationHours="x", permissionLevel="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/folder/share")
    assert sent.json == {"folder": "x", "durationHours": "x", "permissionLevel": "x"}
    assert result.to_dict() == {
        "success": True,
        "message": "Folder shared successfully",
        "permissionLevel": "manage",
        "expiresAt": "x",
        "hostsShared": 1.0,
        "hostsTotal": 1.0,
        "hostResults": [{"hostId": 1.0, "shared": True, "reason": "x"}],
    }


def test_update_host_access_contract(client, mock_http_client):
    """Generated from PATCH /rbac/host/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Access updated", "expiresAt": "x"}
    )
    result = client.rbac.update_host_access("x", "x", permissionLevel="x", durationHours="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/rbac/host/x/access/x")
    assert sent.json == {"permissionLevel": "x", "durationHours": "x"}
    assert result.to_dict() == {"success": True, "message": "Access updated", "expiresAt": "x"}


def test_delete_host_access_contract(client, mock_http_client):
    """Generated from DELETE /rbac/host/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Access revoked"}
    )
    result = client.rbac.delete_host_access("x", "x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/host/x/access/x")
    assert result.to_dict() == {"success": True, "message": "Access revoked"}


def test_list_host_access_contract(client, mock_http_client):
    """Generated from GET /rbac/host/{id}/access in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "accessList": [
                {
                    "id": 1.0,
                    "targetType": "role",
                    "userId": "x",
                    "roleId": 1.0,
                    "username": "x",
                    "roleName": "x",
                    "roleDisplayName": "x",
                    "grantedBy": "x",
                    "grantedByUsername": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                    "createdAt": "x",
                }
            ],
            "isOwner": True,
        },
    )
    result = client.rbac.list_host_access("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/host/x/access")
    assert result.to_dict() == {
        "accessList": [
            {
                "id": 1.0,
                "targetType": "role",
                "userId": "x",
                "roleId": 1.0,
                "username": "x",
                "roleName": "x",
                "roleDisplayName": "x",
                "grantedBy": "x",
                "grantedByUsername": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
                "createdAt": "x",
            }
        ],
        "isOwner": True,
    }


def test_list_shared_hosts_contract(client, mock_http_client):
    """Generated from GET /rbac/shared-hosts in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "sharedHosts": [
                {
                    "id": 1.0,
                    "name": "x",
                    "ip": "x",
                    "port": 1.0,
                    "username": "x",
                    "folder": "x",
                    "tags": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                    "grantedBy": "x",
                    "ownerUsername": "x",
                }
            ]
        },
    )
    result = client.rbac.list_shared_hosts()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/shared-hosts")
    assert result.to_dict() == {
        "sharedHosts": [
            {
                "id": 1.0,
                "name": "x",
                "ip": "x",
                "port": 1.0,
                "username": "x",
                "folder": "x",
                "tags": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
                "grantedBy": "x",
                "ownerUsername": "x",
            }
        ]
    }


def test_share_credential_contract(client, mock_http_client):
    """Generated from POST /rbac/credential/{id}/share in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "permissionLevel": "x", "expiresAt": "x"}
    )
    result = client.rbac.share_credential("x", durationHours=1.0, permissionLevel="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/credential/x/share")
    assert sent.json == {"durationHours": 1.0, "permissionLevel": "x"}
    assert result.to_dict() == {"success": True, "permissionLevel": "x", "expiresAt": "x"}


def test_list_credential_access_contract(client, mock_http_client):
    """Generated from GET /rbac/credential/{id}/access in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "access": [
                {
                    "targetType": "role",
                    "username": "x",
                    "roleName": "x",
                    "roleDisplayName": "x",
                    "grantedByUsername": "x",
                }
            ]
        },
    )
    result = client.rbac.list_credential_access("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/credential/x/access")
    assert result.to_dict() == {
        "access": [
            {
                "targetType": "role",
                "username": "x",
                "roleName": "x",
                "roleDisplayName": "x",
                "grantedByUsername": "x",
            }
        ]
    }


def test_delete_credential_access_contract(client, mock_http_client):
    """Generated from DELETE /rbac/credential/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.rbac.delete_credential_access("x", "x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/credential/x/access/x")
    assert result.to_dict() == {"success": True}


def test_share_snippet_folder_contract(client, mock_http_client):
    """Generated from POST /rbac/snippet-folder/share in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"success": True, "expiresAt": "x", "snippetsShared": 1.0}
    )
    result = client.rbac.share_snippet_folder(folder="x", durationHours=1.0)
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/snippet-folder/share")
    assert sent.json == {"folder": "x", "durationHours": 1.0}
    assert result.to_dict() == {"success": True, "expiresAt": "x", "snippetsShared": 1.0}


def test_list_folder_access_contract(client, mock_http_client):
    """Generated from GET /rbac/folder/access in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "rules": [
                {"targetType": "role", "username": "x", "roleName": "x", "roleDisplayName": "x"}
            ]
        },
    )
    result = client.rbac.list_folder_access(folder="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/folder/access")
    assert sent.params == {"folder": "x"}
    assert result.to_dict() == {
        "rules": [{"targetType": "role", "username": "x", "roleName": "x", "roleDisplayName": "x"}]
    }


def test_delete_folder_access_contract(client, mock_http_client):
    """Generated from DELETE /rbac/folder/access/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.rbac.delete_folder_access("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/folder/access/x")
    assert result.to_dict() == {"success": True}


def test_list_role_members_contract(client, mock_http_client):
    """Generated from GET /rbac/roles/{id}/members in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={"members": [{"userId": "x", "username": "x", "grantedAt": "x", "grantedBy": "x"}]},
    )
    result = client.rbac.list_role_members("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/roles/x/members")
    assert result.to_dict() == {
        "members": [{"userId": "x", "username": "x", "grantedAt": "x", "grantedBy": "x"}]
    }


@pytest.mark.asyncio
async def test_async_list_roles_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/roles in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "roles": [
                {
                    "id": 1.0,
                    "name": "x",
                    "displayName": "x",
                    "description": "x",
                    "isSystem": True,
                    "permissions": ["x"],
                    "createdAt": "x",
                    "updatedAt": "x",
                }
            ]
        },
    )
    result = await async_client.rbac.list_roles()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/roles")
    assert result.to_dict() == {
        "roles": [
            {
                "id": 1.0,
                "name": "x",
                "displayName": "x",
                "description": "x",
                "isSystem": True,
                "permissions": ["x"],
                "createdAt": "x",
                "updatedAt": "x",
            }
        ]
    }


@pytest.mark.asyncio
async def test_async_create_role_contract(async_client, mock_async_http_client):
    """Generated from POST /rbac/roles in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={"success": True, "roleId": 1.0, "message": "Role created successfully"},
    )
    result = await async_client.rbac.create_role(name="x", displayName="x", description="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/roles")
    assert sent.json == {"name": "x", "displayName": "x", "description": "x"}
    assert result.to_dict() == {
        "success": True,
        "roleId": 1.0,
        "message": "Role created successfully",
    }


@pytest.mark.asyncio
async def test_async_update_role_contract(async_client, mock_async_http_client):
    """Generated from PUT /rbac/roles/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role updated successfully"}
    )
    result = await async_client.rbac.update_role(
        "x", displayName="x", description="x", permissions=[]
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/rbac/roles/x")
    assert sent.json == {"displayName": "x", "description": "x", "permissions": []}
    assert result.to_dict() == {"success": True, "message": "Role updated successfully"}


@pytest.mark.asyncio
async def test_async_delete_role_contract(async_client, mock_async_http_client):
    """Generated from DELETE /rbac/roles/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role deleted successfully"}
    )
    result = await async_client.rbac.delete_role("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/roles/x")
    assert result.to_dict() == {"success": True, "message": "Role deleted successfully"}


@pytest.mark.asyncio
async def test_async_permissions_catalog_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/permissions/catalog in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"catalog": [{"group": "x", "permissions": ["x"]}]}
    )
    result = await async_client.rbac.permissions_catalog()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/permissions/catalog")
    assert result.to_dict() == {"catalog": [{"group": "x", "permissions": ["x"]}]}


@pytest.mark.asyncio
async def test_async_assign_role_contract(async_client, mock_async_http_client):
    """Generated from POST /rbac/users/{userId}/roles in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role assigned successfully"}
    )
    result = await async_client.rbac.assign_role("x", roleId=1.0)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/users/x/roles")
    assert sent.json == {"roleId": 1.0}
    assert result.to_dict() == {"success": True, "message": "Role assigned successfully"}


@pytest.mark.asyncio
async def test_async_list_user_roles_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/users/{userId}/roles in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"roles": [{}]})
    result = await async_client.rbac.list_user_roles("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/users/x/roles")
    assert result.to_dict() == {"roles": [{}]}


@pytest.mark.asyncio
async def test_async_revoke_role_contract(async_client, mock_async_http_client):
    """Generated from DELETE /rbac/users/{userId}/roles/{roleId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Role removed successfully"}
    )
    result = await async_client.rbac.revoke_role("x", "x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/users/x/roles/x")
    assert result.to_dict() == {"success": True, "message": "Role removed successfully"}


@pytest.mark.asyncio
async def test_async_share_snippet_contract(async_client, mock_async_http_client):
    """Generated from POST /rbac/snippet/{id}/share in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "x", "expiresAt": "x"}
    )
    result = await async_client.rbac.share_snippet(
        "x", targetType="user", targetUserId="x", targetRoleId=1.0, durationHours=1.0
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/snippet/x/share")
    assert sent.json == {
        "targetType": "user",
        "targetUserId": "x",
        "targetRoleId": 1.0,
        "durationHours": 1.0,
    }
    assert result.to_dict() == {"success": True, "message": "x", "expiresAt": "x"}


@pytest.mark.asyncio
async def test_async_share_host_contract(async_client, mock_async_http_client):
    """Generated from POST /rbac/host/{id}/share in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "Host shared successfully",
            "permissionLevel": "manage",
            "expiresAt": "x",
            "results": [{"type": "role", "id": "x", "accessId": 1.0, "created": True}],
        },
    )
    result = await async_client.rbac.share_host("x", durationHours="x", permissionLevel="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/host/x/share")
    assert sent.json == {"durationHours": "x", "permissionLevel": "x"}
    assert result.to_dict() == {
        "success": True,
        "message": "Host shared successfully",
        "permissionLevel": "manage",
        "expiresAt": "x",
        "results": [{"type": "role", "id": "x", "accessId": 1.0, "created": True}],
    }


@pytest.mark.asyncio
async def test_async_delete_snippet_access_contract(async_client, mock_async_http_client):
    """Generated from DELETE /rbac/snippet/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Snippet access revoked"}
    )
    result = await async_client.rbac.delete_snippet_access("x", "x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/snippet/x/access/x")
    assert result.to_dict() == {"success": True, "message": "Snippet access revoked"}


@pytest.mark.asyncio
async def test_async_list_snippet_access_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/snippet/{id}/access in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "accessList": [
                {
                    "id": 1.0,
                    "targetType": "role",
                    "userId": "x",
                    "roleId": 1.0,
                    "username": "x",
                    "roleName": "x",
                    "roleDisplayName": "x",
                    "grantedBy": "x",
                    "grantedByUsername": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                    "createdAt": "x",
                }
            ]
        },
    )
    result = await async_client.rbac.list_snippet_access("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/snippet/x/access")
    assert result.to_dict() == {
        "accessList": [
            {
                "id": 1.0,
                "targetType": "role",
                "userId": "x",
                "roleId": 1.0,
                "username": "x",
                "roleName": "x",
                "roleDisplayName": "x",
                "grantedBy": "x",
                "grantedByUsername": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
                "createdAt": "x",
            }
        ]
    }


@pytest.mark.asyncio
async def test_async_list_shared_snippets_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/shared-snippets in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "sharedSnippets": [
                {
                    "id": 1.0,
                    "name": "x",
                    "content": "x",
                    "description": "x",
                    "folder": "x",
                    "ownerUsername": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                }
            ]
        },
    )
    result = await async_client.rbac.list_shared_snippets()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/shared-snippets")
    assert result.to_dict() == {
        "sharedSnippets": [
            {
                "id": 1.0,
                "name": "x",
                "content": "x",
                "description": "x",
                "folder": "x",
                "ownerUsername": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
            }
        ]
    }


@pytest.mark.asyncio
async def test_async_set_host_access_auth_contract(async_client, mock_async_http_client):
    """Generated from PUT /rbac/host-access/{hostId}/auth/{protocol} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "protocol": "ssh", "credentialId": "x"}
    )
    result = await async_client.rbac.set_host_access_auth("x", "x", credentialId="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/rbac/host-access/x/auth/x")
    assert sent.json == {"credentialId": "x"}
    assert result.to_dict() == {"success": True, "protocol": "ssh", "credentialId": "x"}


@pytest.mark.asyncio
async def test_async_get_host_access_auth_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/host-access/{hostId}/auth/{protocol} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"protocol": "ssh", "credentialId": 1.0}
    )
    result = await async_client.rbac.get_host_access_auth("x", "x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/host-access/x/auth/x")
    assert result.to_dict() == {"protocol": "ssh", "credentialId": 1.0}


@pytest.mark.asyncio
async def test_async_share_folder_contract(async_client, mock_async_http_client):
    """Generated from POST /rbac/folder/share in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "Folder shared successfully",
            "permissionLevel": "manage",
            "expiresAt": "x",
            "hostsShared": 1.0,
            "hostsTotal": 1.0,
            "hostResults": [{"hostId": 1.0, "shared": True, "reason": "x"}],
        },
    )
    result = await async_client.rbac.share_folder(
        folder="x", durationHours="x", permissionLevel="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/folder/share")
    assert sent.json == {"folder": "x", "durationHours": "x", "permissionLevel": "x"}
    assert result.to_dict() == {
        "success": True,
        "message": "Folder shared successfully",
        "permissionLevel": "manage",
        "expiresAt": "x",
        "hostsShared": 1.0,
        "hostsTotal": 1.0,
        "hostResults": [{"hostId": 1.0, "shared": True, "reason": "x"}],
    }


@pytest.mark.asyncio
async def test_async_update_host_access_contract(async_client, mock_async_http_client):
    """Generated from PATCH /rbac/host/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Access updated", "expiresAt": "x"}
    )
    result = await async_client.rbac.update_host_access(
        "x", "x", permissionLevel="x", durationHours="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/rbac/host/x/access/x")
    assert sent.json == {"permissionLevel": "x", "durationHours": "x"}
    assert result.to_dict() == {"success": True, "message": "Access updated", "expiresAt": "x"}


@pytest.mark.asyncio
async def test_async_delete_host_access_contract(async_client, mock_async_http_client):
    """Generated from DELETE /rbac/host/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "message": "Access revoked"}
    )
    result = await async_client.rbac.delete_host_access("x", "x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/host/x/access/x")
    assert result.to_dict() == {"success": True, "message": "Access revoked"}


@pytest.mark.asyncio
async def test_async_list_host_access_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/host/{id}/access in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "accessList": [
                {
                    "id": 1.0,
                    "targetType": "role",
                    "userId": "x",
                    "roleId": 1.0,
                    "username": "x",
                    "roleName": "x",
                    "roleDisplayName": "x",
                    "grantedBy": "x",
                    "grantedByUsername": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                    "createdAt": "x",
                }
            ],
            "isOwner": True,
        },
    )
    result = await async_client.rbac.list_host_access("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/host/x/access")
    assert result.to_dict() == {
        "accessList": [
            {
                "id": 1.0,
                "targetType": "role",
                "userId": "x",
                "roleId": 1.0,
                "username": "x",
                "roleName": "x",
                "roleDisplayName": "x",
                "grantedBy": "x",
                "grantedByUsername": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
                "createdAt": "x",
            }
        ],
        "isOwner": True,
    }


@pytest.mark.asyncio
async def test_async_list_shared_hosts_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/shared-hosts in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "sharedHosts": [
                {
                    "id": 1.0,
                    "name": "x",
                    "ip": "x",
                    "port": 1.0,
                    "username": "x",
                    "folder": "x",
                    "tags": "x",
                    "permissionLevel": "x",
                    "expiresAt": "x",
                    "grantedBy": "x",
                    "ownerUsername": "x",
                }
            ]
        },
    )
    result = await async_client.rbac.list_shared_hosts()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/shared-hosts")
    assert result.to_dict() == {
        "sharedHosts": [
            {
                "id": 1.0,
                "name": "x",
                "ip": "x",
                "port": 1.0,
                "username": "x",
                "folder": "x",
                "tags": "x",
                "permissionLevel": "x",
                "expiresAt": "x",
                "grantedBy": "x",
                "ownerUsername": "x",
            }
        ]
    }


@pytest.mark.asyncio
async def test_async_share_credential_contract(async_client, mock_async_http_client):
    """Generated from POST /rbac/credential/{id}/share in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "permissionLevel": "x", "expiresAt": "x"}
    )
    result = await async_client.rbac.share_credential("x", durationHours=1.0, permissionLevel="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/credential/x/share")
    assert sent.json == {"durationHours": 1.0, "permissionLevel": "x"}
    assert result.to_dict() == {"success": True, "permissionLevel": "x", "expiresAt": "x"}


@pytest.mark.asyncio
async def test_async_list_credential_access_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/credential/{id}/access in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "access": [
                {
                    "targetType": "role",
                    "username": "x",
                    "roleName": "x",
                    "roleDisplayName": "x",
                    "grantedByUsername": "x",
                }
            ]
        },
    )
    result = await async_client.rbac.list_credential_access("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/credential/x/access")
    assert result.to_dict() == {
        "access": [
            {
                "targetType": "role",
                "username": "x",
                "roleName": "x",
                "roleDisplayName": "x",
                "grantedByUsername": "x",
            }
        ]
    }


@pytest.mark.asyncio
async def test_async_delete_credential_access_contract(async_client, mock_async_http_client):
    """Generated from DELETE /rbac/credential/{id}/access/{accessId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.rbac.delete_credential_access("x", "x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/credential/x/access/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_share_snippet_folder_contract(async_client, mock_async_http_client):
    """Generated from POST /rbac/snippet-folder/share in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"success": True, "expiresAt": "x", "snippetsShared": 1.0}
    )
    result = await async_client.rbac.share_snippet_folder(folder="x", durationHours=1.0)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/rbac/snippet-folder/share")
    assert sent.json == {"folder": "x", "durationHours": 1.0}
    assert result.to_dict() == {"success": True, "expiresAt": "x", "snippetsShared": 1.0}


@pytest.mark.asyncio
async def test_async_list_folder_access_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/folder/access in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "rules": [
                {"targetType": "role", "username": "x", "roleName": "x", "roleDisplayName": "x"}
            ]
        },
    )
    result = await async_client.rbac.list_folder_access(folder="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/folder/access")
    assert sent.params == {"folder": "x"}
    assert result.to_dict() == {
        "rules": [{"targetType": "role", "username": "x", "roleName": "x", "roleDisplayName": "x"}]
    }


@pytest.mark.asyncio
async def test_async_delete_folder_access_contract(async_client, mock_async_http_client):
    """Generated from DELETE /rbac/folder/access/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.rbac.delete_folder_access("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/rbac/folder/access/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_list_role_members_contract(async_client, mock_async_http_client):
    """Generated from GET /rbac/roles/{id}/members in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={"members": [{"userId": "x", "username": "x", "grantedAt": "x", "grantedBy": "x"}]},
    )
    result = await async_client.rbac.list_role_members("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/rbac/roles/x/members")
    assert result.to_dict() == {
        "members": [{"userId": "x", "username": "x", "grantedAt": "x", "grantedBy": "x"}]
    }
