"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.terminal."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_image_upload_contract(client, mock_http_client):
    """Generated from POST /terminal/image-upload in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"id": "x", "filename": "x", "shellPath": "x", "storage": "local"}
    )
    result = client.terminal.image_upload(instanceId="x", source="file", clientUploadTimestamp="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/image-upload")
    assert sent.json == {"instanceId": "x", "source": "file", "clientUploadTimestamp": "x"}
    assert result.to_dict() == {"id": "x", "filename": "x", "shellPath": "x", "storage": "local"}


def test_log_command_contract(client, mock_http_client):
    """Generated from POST /terminal/command_history in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={"id": 0, "userId": "x", "hostId": 1.0, "command": "x", "executedAt": "x"},
    )
    result = client.terminal.log_command(hostId=1, command="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/command_history")
    assert sent.json == {"hostId": 1, "command": "x"}
    assert result.to_dict() == {
        "id": 0,
        "userId": "x",
        "hostId": 1.0,
        "command": "x",
        "executedAt": "x",
    }


def test_list_command_history_contract(client, mock_http_client):
    """Generated from GET /terminal/command_history/{hostId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=["x"])
    result = client.terminal.list_command_history("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/terminal/command_history/x")
    assert result == ["x"]


def test_clear_command_history_contract(client, mock_http_client):
    """Generated from DELETE /terminal/command_history/{hostId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.terminal.clear_command_history("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/terminal/command_history/x")
    assert result.to_dict() == {"success": True}


def test_delete_command_history_entries_contract(client, mock_http_client):
    """Generated from POST /terminal/command_history/delete in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.terminal.delete_command_history_entries(hostId=1, command="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/command_history/delete")
    assert sent.json == {"hostId": 1, "command": "x"}
    assert result.to_dict() == {"success": True}


def test_get_session_settings_contract(client, mock_http_client):
    """Generated from GET /terminal/session_settings in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"timeoutMinutes": 1.0, "enabled": True})
    result = client.terminal.get_session_settings()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/terminal/session_settings")
    assert result.to_dict() == {"timeoutMinutes": 1.0, "enabled": True}


def test_set_session_settings_contract(client, mock_http_client):
    """Generated from POST /terminal/session_settings in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.terminal.set_session_settings(timeoutMinutes=1.0, enabled="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/session_settings")
    assert sent.json == {"timeoutMinutes": 1.0, "enabled": "x"}
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_image_upload_contract(async_client, mock_async_http_client):
    """Generated from POST /terminal/image-upload in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"id": "x", "filename": "x", "shellPath": "x", "storage": "local"}
    )
    result = await async_client.terminal.image_upload(
        instanceId="x", source="file", clientUploadTimestamp="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/image-upload")
    assert sent.json == {"instanceId": "x", "source": "file", "clientUploadTimestamp": "x"}
    assert result.to_dict() == {"id": "x", "filename": "x", "shellPath": "x", "storage": "local"}


@pytest.mark.asyncio
async def test_async_log_command_contract(async_client, mock_async_http_client):
    """Generated from POST /terminal/command_history in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={"id": 0, "userId": "x", "hostId": 1.0, "command": "x", "executedAt": "x"},
    )
    result = await async_client.terminal.log_command(hostId=1, command="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/command_history")
    assert sent.json == {"hostId": 1, "command": "x"}
    assert result.to_dict() == {
        "id": 0,
        "userId": "x",
        "hostId": 1.0,
        "command": "x",
        "executedAt": "x",
    }


@pytest.mark.asyncio
async def test_async_list_command_history_contract(async_client, mock_async_http_client):
    """Generated from GET /terminal/command_history/{hostId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=["x"])
    result = await async_client.terminal.list_command_history("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/terminal/command_history/x")
    assert result == ["x"]


@pytest.mark.asyncio
async def test_async_clear_command_history_contract(async_client, mock_async_http_client):
    """Generated from DELETE /terminal/command_history/{hostId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.terminal.clear_command_history("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/terminal/command_history/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_delete_command_history_entries_contract(async_client, mock_async_http_client):
    """Generated from POST /terminal/command_history/delete in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.terminal.delete_command_history_entries(hostId=1, command="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/command_history/delete")
    assert sent.json == {"hostId": 1, "command": "x"}
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_get_session_settings_contract(async_client, mock_async_http_client):
    """Generated from GET /terminal/session_settings in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"timeoutMinutes": 1.0, "enabled": True}
    )
    result = await async_client.terminal.get_session_settings()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/terminal/session_settings")
    assert result.to_dict() == {"timeoutMinutes": 1.0, "enabled": True}


@pytest.mark.asyncio
async def test_async_set_session_settings_contract(async_client, mock_async_http_client):
    """Generated from POST /terminal/session_settings in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.terminal.set_session_settings(timeoutMinutes=1.0, enabled="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/terminal/session_settings")
    assert sent.json == {"timeoutMinutes": 1.0, "enabled": "x"}
    assert result.to_dict() == {"success": True}
