"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.workspaces."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_create_contract(client, mock_http_client):
    """Generated from POST /workspaces in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.create(
        name="x",
        color="x",
        icon="x",
        payload={
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        },
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces")
    assert sent.json == {
        "name": "x",
        "color": "x",
        "icon": "x",
        "payload": {
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        },
    }
    assert result is not None


def test_list_contract(client, mock_http_client):
    """Generated from GET /workspaces in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=["x"])
    result = client.workspaces.list()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/workspaces")
    assert result == ["x"]


def test_get_last_session_contract(client, mock_http_client):
    """Generated from GET /workspaces/last-session in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.get_last_session()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/workspaces/last-session")
    assert result is not None


def test_save_last_session_contract(client, mock_http_client):
    """Generated from PUT /workspaces/last-session in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.save_last_session(
        payload={
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        }
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/workspaces/last-session")
    assert sent.json == {
        "payload": {
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        }
    }
    assert result is not None


def test_update_contract(client, mock_http_client):
    """Generated from PATCH /workspaces/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.update("x", name="x", color="x", icon="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/workspaces/x")
    assert sent.json == {"name": "x", "color": "x", "icon": "x"}
    assert result is not None


def test_delete_contract(client, mock_http_client):
    """Generated from DELETE /workspaces/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.workspaces.delete("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/workspaces/x")
    assert result.to_dict() == {"success": True}


def test_set_content_contract(client, mock_http_client):
    """Generated from PUT /workspaces/{id}/content in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.set_content(
        "x",
        payload={
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        },
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/workspaces/x/content")
    assert sent.json == {
        "payload": {
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        }
    }
    assert result is not None


def test_duplicate_contract(client, mock_http_client):
    """Generated from POST /workspaces/{id}/duplicate in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.duplicate("x", name="x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/duplicate")
    assert sent.json == {"name": "x"}
    assert result is not None


def test_set_default_contract(client, mock_http_client):
    """Generated from POST /workspaces/{id}/set-default in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.set_default("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/set-default")
    assert result is not None


def test_unset_default_contract(client, mock_http_client):
    """Generated from POST /workspaces/{id}/unset-default in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.unset_default("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/unset-default")
    assert result is not None


def test_apply_contract(client, mock_http_client):
    """Generated from POST /workspaces/{id}/apply in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={})
    result = client.workspaces.apply("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/apply")
    assert result is not None


@pytest.mark.asyncio
async def test_async_create_contract(async_client, mock_async_http_client):
    """Generated from POST /workspaces in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.create(
        name="x",
        color="x",
        icon="x",
        payload={
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        },
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces")
    assert sent.json == {
        "name": "x",
        "color": "x",
        "icon": "x",
        "payload": {
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        },
    }
    assert result is not None


@pytest.mark.asyncio
async def test_async_list_contract(async_client, mock_async_http_client):
    """Generated from GET /workspaces in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=["x"])
    result = await async_client.workspaces.list()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/workspaces")
    assert result == ["x"]


@pytest.mark.asyncio
async def test_async_get_last_session_contract(async_client, mock_async_http_client):
    """Generated from GET /workspaces/last-session in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.get_last_session()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/workspaces/last-session")
    assert result is not None


@pytest.mark.asyncio
async def test_async_save_last_session_contract(async_client, mock_async_http_client):
    """Generated from PUT /workspaces/last-session in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.save_last_session(
        payload={
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        }
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/workspaces/last-session")
    assert sent.json == {
        "payload": {
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        }
    }
    assert result is not None


@pytest.mark.asyncio
async def test_async_update_contract(async_client, mock_async_http_client):
    """Generated from PATCH /workspaces/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.update("x", name="x", color="x", icon="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PATCH"
    assert sent.url.endswith("/workspaces/x")
    assert sent.json == {"name": "x", "color": "x", "icon": "x"}
    assert result is not None


@pytest.mark.asyncio
async def test_async_delete_contract(async_client, mock_async_http_client):
    """Generated from DELETE /workspaces/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.workspaces.delete("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/workspaces/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_set_content_contract(async_client, mock_async_http_client):
    """Generated from PUT /workspaces/{id}/content in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.set_content(
        "x",
        payload={
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        },
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/workspaces/x/content")
    assert sent.json == {
        "payload": {
            "version": 1.0,
            "tabs": [{}],
            "activeSlotId": "x",
            "splitMode": "none",
            "paneTabIds": ["x"],
            "rowSizes": [1.0],
            "rowColSizes": [[1.0]],
            "sidebar": {"left": {}, "right": {}},
        }
    }
    assert result is not None


@pytest.mark.asyncio
async def test_async_duplicate_contract(async_client, mock_async_http_client):
    """Generated from POST /workspaces/{id}/duplicate in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.duplicate("x", name="x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/duplicate")
    assert sent.json == {"name": "x"}
    assert result is not None


@pytest.mark.asyncio
async def test_async_set_default_contract(async_client, mock_async_http_client):
    """Generated from POST /workspaces/{id}/set-default in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.set_default("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/set-default")
    assert result is not None


@pytest.mark.asyncio
async def test_async_unset_default_contract(async_client, mock_async_http_client):
    """Generated from POST /workspaces/{id}/unset-default in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.unset_default("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/unset-default")
    assert result is not None


@pytest.mark.asyncio
async def test_async_apply_contract(async_client, mock_async_http_client):
    """Generated from POST /workspaces/{id}/apply in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={})
    result = await async_client.workspaces.apply("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/workspaces/x/apply")
    assert result is not None
