"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.guacamole."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_connect_host_contract(client, mock_http_client):
    """Generated from POST /guacamole/connect-host/{hostId} in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200, body={"token": "x", "guacamoleConnectionId": "x"}
    )
    result = client.guacamole.connect_host(
        "x", protocol="x", promptedUsername="x", promptedPassword="x", promptedDomain="x"
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/guacamole/connect-host/x")
    assert sent.json == {
        "protocol": "x",
        "promptedUsername": "x",
        "promptedPassword": "x",
        "promptedDomain": "x",
    }
    assert result.to_dict() == {"token": "x", "guacamoleConnectionId": "x"}


def test_get_status_contract(client, mock_http_client):
    """Generated from GET /guacamole/status in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "guacd": {"host": "x", "port": 1.0, "status": "connected"},
            "websocket": {"port": 30008, "status": "running"},
        },
    )
    result = client.guacamole.get_status()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/guacamole/status")
    assert result.to_dict() == {
        "guacd": {"host": "x", "port": 1.0, "status": "connected"},
        "websocket": {"port": 30008, "status": "running"},
    }


def test_create_token_contract(client, mock_http_client):
    """Generated from POST /guacamole/token in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"token": "x"})
    result = client.guacamole.create_token(
        type="rdp", hostname="x", port="x", username="x", password="x", domain="x", rawOptions="x"
    )
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/guacamole/token")
    assert sent.json == {
        "type": "rdp",
        "hostname": "x",
        "port": "x",
        "username": "x",
        "password": "x",
        "domain": "x",
        "rawOptions": "x",
    }
    assert result.to_dict() == {"token": "x"}


@pytest.mark.asyncio
async def test_async_connect_host_contract(async_client, mock_async_http_client):
    """Generated from POST /guacamole/connect-host/{hostId} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200, body={"token": "x", "guacamoleConnectionId": "x"}
    )
    result = await async_client.guacamole.connect_host(
        "x", protocol="x", promptedUsername="x", promptedPassword="x", promptedDomain="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/guacamole/connect-host/x")
    assert sent.json == {
        "protocol": "x",
        "promptedUsername": "x",
        "promptedPassword": "x",
        "promptedDomain": "x",
    }
    assert result.to_dict() == {"token": "x", "guacamoleConnectionId": "x"}


@pytest.mark.asyncio
async def test_async_get_status_contract(async_client, mock_async_http_client):
    """Generated from GET /guacamole/status in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "guacd": {"host": "x", "port": 1.0, "status": "connected"},
            "websocket": {"port": 30008, "status": "running"},
        },
    )
    result = await async_client.guacamole.get_status()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/guacamole/status")
    assert result.to_dict() == {
        "guacd": {"host": "x", "port": 1.0, "status": "connected"},
        "websocket": {"port": 30008, "status": "running"},
    }


@pytest.mark.asyncio
async def test_async_create_token_contract(async_client, mock_async_http_client):
    """Generated from POST /guacamole/token in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"token": "x"})
    result = await async_client.guacamole.create_token(
        type="rdp", hostname="x", port="x", username="x", password="x", domain="x", rawOptions="x"
    )
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/guacamole/token")
    assert sent.json == {
        "type": "rdp",
        "hostname": "x",
        "port": "x",
        "username": "x",
        "password": "x",
        "domain": "x",
        "rawOptions": "x",
    }
    assert result.to_dict() == {"token": "x"}
