"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.encryption."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_get_status_contract(client, mock_http_client):
    """Generated from GET /encryption/status in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "security": {
                "initialized": True,
                "system": {"hasSecret": True, "isValid": True},
                "activeSessions": {},
                "activeSessionCount": 0,
            },
            "version": "v2-kek-dek",
        },
    )
    result = client.encryption.get_status()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/encryption/status")
    assert result.to_dict() == {
        "security": {
            "initialized": True,
            "system": {"hasSecret": True, "isValid": True},
            "activeSessions": {},
            "activeSessionCount": 0,
        },
        "version": "v2-kek-dek",
    }


def test_initialize_contract(client, mock_http_client):
    """Generated from POST /encryption/initialize in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "Security system initialized successfully",
            "version": "v2-kek-dek",
            "note": "User data encryption will be set up when users log in",
        },
    )
    result = client.encryption.initialize()
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/encryption/initialize")
    assert result.to_dict() == {
        "success": True,
        "message": "Security system initialized successfully",
        "version": "v2-kek-dek",
        "note": "User data encryption will be set up when users log in",
    }


def test_regenerate_contract(client, mock_http_client):
    """Generated from POST /encryption/regenerate in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "System JWT secret regenerated",
            "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
            "note": "User data encryption keys are protected by passwords and cannot be regenerated",
        },
    )
    result = client.encryption.regenerate()
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/encryption/regenerate")
    assert result.to_dict() == {
        "success": True,
        "message": "System JWT secret regenerated",
        "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
        "note": "User data encryption keys are protected by passwords and cannot be regenerated",
    }


def test_regenerate_jwt_contract(client, mock_http_client):
    """Generated from POST /encryption/regenerate-jwt in spec/termix-openapi.json."""
    mock_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "New JWT secret generated",
            "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
        },
    )
    result = client.encryption.regenerate_jwt()
    sent = mock_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/encryption/regenerate-jwt")
    assert result.to_dict() == {
        "success": True,
        "message": "New JWT secret generated",
        "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
    }


@pytest.mark.asyncio
async def test_async_get_status_contract(async_client, mock_async_http_client):
    """Generated from GET /encryption/status in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "security": {
                "initialized": True,
                "system": {"hasSecret": True, "isValid": True},
                "activeSessions": {},
                "activeSessionCount": 0,
            },
            "version": "v2-kek-dek",
        },
    )
    result = await async_client.encryption.get_status()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/encryption/status")
    assert result.to_dict() == {
        "security": {
            "initialized": True,
            "system": {"hasSecret": True, "isValid": True},
            "activeSessions": {},
            "activeSessionCount": 0,
        },
        "version": "v2-kek-dek",
    }


@pytest.mark.asyncio
async def test_async_initialize_contract(async_client, mock_async_http_client):
    """Generated from POST /encryption/initialize in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "Security system initialized successfully",
            "version": "v2-kek-dek",
            "note": "User data encryption will be set up when users log in",
        },
    )
    result = await async_client.encryption.initialize()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/encryption/initialize")
    assert result.to_dict() == {
        "success": True,
        "message": "Security system initialized successfully",
        "version": "v2-kek-dek",
        "note": "User data encryption will be set up when users log in",
    }


@pytest.mark.asyncio
async def test_async_regenerate_contract(async_client, mock_async_http_client):
    """Generated from POST /encryption/regenerate in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "System JWT secret regenerated",
            "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
            "note": "User data encryption keys are protected by passwords and cannot be regenerated",
        },
    )
    result = await async_client.encryption.regenerate()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/encryption/regenerate")
    assert result.to_dict() == {
        "success": True,
        "message": "System JWT secret regenerated",
        "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
        "note": "User data encryption keys are protected by passwords and cannot be regenerated",
    }


@pytest.mark.asyncio
async def test_async_regenerate_jwt_contract(async_client, mock_async_http_client):
    """Generated from POST /encryption/regenerate-jwt in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(
        status_code=200,
        body={
            "success": True,
            "message": "New JWT secret generated",
            "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
        },
    )
    result = await async_client.encryption.regenerate_jwt()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "POST"
    assert sent.url.endswith("/encryption/regenerate-jwt")
    assert result.to_dict() == {
        "success": True,
        "message": "New JWT secret generated",
        "warning": "All existing JWT tokens are now invalid - users must re-authenticate",
    }
