"""Generated by tools/sdk-gen/generate.py. Do not edit by hand —
see docs/sdk-plan.md phases F3/F4. Covers termix_sdk.resources.session_logs."""

from __future__ import annotations

# ruff: noqa: E501
import pytest


def test_list_contract(client, mock_http_client):
    """Generated from GET /session_logs in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"logs": [{"sizeBytes": 1.0}]})
    result = client.session_logs.list()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs")
    assert result.to_dict() == {"logs": [{"sizeBytes": 1.0}]}


def test_get_retention_contract(client, mock_http_client):
    """Generated from GET /session_logs/retention in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"retentionDays": 1.0})
    result = client.session_logs.get_retention()
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs/retention")
    assert result.to_dict() == {"retentionDays": 1.0}


def test_set_retention_contract(client, mock_http_client):
    """Generated from PUT /session_logs/retention in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"retentionDays": 1.0})
    result = client.session_logs.set_retention(retentionDays=1.0)
    sent = mock_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/session_logs/retention")
    assert sent.json == {"retentionDays": 1.0}
    assert result.to_dict() == {"retentionDays": 1.0}


def test_retrieve_contract(client, mock_http_client):
    """Generated from GET /session_logs/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"log": {}})
    result = client.session_logs.retrieve("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs/x")
    assert result.to_dict() == {"log": {}}


def test_delete_contract(client, mock_http_client):
    """Generated from DELETE /session_logs/{id} in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body={"success": True})
    result = client.session_logs.delete("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/session_logs/x")
    assert result.to_dict() == {"success": True}


def test_get_content_contract(client, mock_http_client):
    """Generated from GET /session_logs/{id}/content in spec/termix-openapi.json."""
    mock_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = client.session_logs.get_content("x")
    sent = mock_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs/x/content")
    assert result.read() == b"binary-content-placeholder"


@pytest.mark.asyncio
async def test_async_list_contract(async_client, mock_async_http_client):
    """Generated from GET /session_logs in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"logs": [{"sizeBytes": 1.0}]})
    result = await async_client.session_logs.list()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs")
    assert result.to_dict() == {"logs": [{"sizeBytes": 1.0}]}


@pytest.mark.asyncio
async def test_async_get_retention_contract(async_client, mock_async_http_client):
    """Generated from GET /session_logs/retention in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"retentionDays": 1.0})
    result = await async_client.session_logs.get_retention()
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs/retention")
    assert result.to_dict() == {"retentionDays": 1.0}


@pytest.mark.asyncio
async def test_async_set_retention_contract(async_client, mock_async_http_client):
    """Generated from PUT /session_logs/retention in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"retentionDays": 1.0})
    result = await async_client.session_logs.set_retention(retentionDays=1.0)
    sent = mock_async_http_client.requests[0]
    assert sent.method == "PUT"
    assert sent.url.endswith("/session_logs/retention")
    assert sent.json == {"retentionDays": 1.0}
    assert result.to_dict() == {"retentionDays": 1.0}


@pytest.mark.asyncio
async def test_async_retrieve_contract(async_client, mock_async_http_client):
    """Generated from GET /session_logs/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"log": {}})
    result = await async_client.session_logs.retrieve("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs/x")
    assert result.to_dict() == {"log": {}}


@pytest.mark.asyncio
async def test_async_delete_contract(async_client, mock_async_http_client):
    """Generated from DELETE /session_logs/{id} in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body={"success": True})
    result = await async_client.session_logs.delete("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "DELETE"
    assert sent.url.endswith("/session_logs/x")
    assert result.to_dict() == {"success": True}


@pytest.mark.asyncio
async def test_async_get_content_contract(async_client, mock_async_http_client):
    """Generated from GET /session_logs/{id}/content in spec/termix-openapi.json."""
    mock_async_http_client.queue_response(status_code=200, body=b"binary-content-placeholder")
    result = await async_client.session_logs.get_content("x")
    sent = mock_async_http_client.requests[0]
    assert sent.method == "GET"
    assert sent.url.endswith("/session_logs/x/content")
    assert await result.read() == b"binary-content-placeholder"
