# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Collab: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.collab import (
    CollabCreateRoomResult,
    CollabDeleteControlRequestResult,
    CollabDeleteRoomResult,
    CollabEndRoomResult,
    CollabGetGuestStageResult,
    CollabGetRoomResult,
    CollabGetStageResult,
    CollabInviteMembersResult,
    CollabListControlRequestsResult,
    CollabListRoomsResult,
    CollabPresentResult,
    CollabRemoveMemberResult,
    CollabRequestControlResult,
    CollabSetControlResult,
    CollabSetGuestLinkResult,
    CollabStopPresentingResult,
)
from ..types.collab import (
    CollabCreateRoomParams,
    CollabInviteMembersParams,
    CollabPresentParams,
    CollabSetControlParams,
    CollabSetGuestLinkParams,
)


class CollabService(TermixService):
    service = "database"

    def list_rooms(self, *, options: RequestOptions | None = None) -> CollabListRoomsResult:
        """List rooms the caller belongs to

        GET /collab/rooms
        Source: src/backend/hosts/collab/routes.ts:162
        """
        response = self._request("GET", "/collab/rooms", options=options)
        return CollabListRoomsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def create_room(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabCreateRoomParams],
    ) -> CollabCreateRoomResult:
        """Create a collaboration room

        POST /collab/rooms
        Source: src/backend/hosts/collab/routes.ts:109
        """
        response = self._request(
            "POST", "/collab/rooms", json_body=dict(params) or None, options=options
        )
        return CollabCreateRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_room(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabGetRoomResult:
        """Get a room with members, online users and stage state

        GET /collab/rooms/{id}
        Source: src/backend/hosts/collab/routes.ts:183
        """
        response = self._request("GET", f"/collab/rooms/{id}", options=options)
        return CollabGetRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete_room(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabDeleteRoomResult:
        """Permanently delete a room (host only)

        DELETE /collab/rooms/{id}
        Source: src/backend/hosts/collab/routes.ts:1182
        """
        response = self._request("DELETE", f"/collab/rooms/{id}", options=options)
        return CollabDeleteRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    def end_room(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabEndRoomResult:
        """End the meeting (host only)

        POST /collab/rooms/{id}/end
        Source: src/backend/hosts/collab/routes.ts:1117
        """
        response = self._request("POST", f"/collab/rooms/{id}/end", options=options)
        return CollabEndRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    def invite_members(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabInviteMembersParams],
    ) -> CollabInviteMembersResult:
        """Invite users to a room (host only)

        POST /collab/rooms/{id}/members
        Source: src/backend/hosts/collab/routes.ts:256
        """
        response = self._request(
            "POST", f"/collab/rooms/{id}/members", json_body=dict(params) or None, options=options
        )
        return CollabInviteMembersResult.construct_from(
            response.data if response else None, last_response=response
        )

    def remove_member(
        self,
        id: str,
        user_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabRemoveMemberResult:
        """Remove a member (host), or leave the room (self)

        DELETE /collab/rooms/{id}/members/{userId}
        Source: src/backend/hosts/collab/routes.ts:352
        """
        response = self._request("DELETE", f"/collab/rooms/{id}/members/{user_id}", options=options)
        return CollabRemoveMemberResult.construct_from(
            response.data if response else None, last_response=response
        )

    def present(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabPresentParams],
    ) -> CollabPresentResult:
        """Take the stage with one of your live sessions

        POST /collab/rooms/{id}/present
        Source: src/backend/hosts/collab/routes.ts:449
        """
        response = self._request(
            "POST", f"/collab/rooms/{id}/present", json_body=dict(params) or None, options=options
        )
        return CollabPresentResult.construct_from(
            response.data if response else None, last_response=response
        )

    def stop_presenting(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabStopPresentingResult:
        """Stop presenting (presenter or host)

        POST /collab/rooms/{id}/stop
        Source: src/backend/hosts/collab/routes.ts:562
        """
        response = self._request("POST", f"/collab/rooms/{id}/stop", options=options)
        return CollabStopPresentingResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_stage(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabGetStageResult:
        """Get connect info for the current stage (members only)

        GET /collab/rooms/{id}/stage
        Source: src/backend/hosts/collab/routes.ts:619
        """
        response = self._request("GET", f"/collab/rooms/{id}/stage", options=options)
        return CollabGetStageResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_control(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabSetControlParams],
    ) -> CollabSetControlResult:
        """Grant or revoke stage control (presenter or host)

        POST /collab/rooms/{id}/control
        Source: src/backend/hosts/collab/routes.ts:755
        """
        response = self._request(
            "POST", f"/collab/rooms/{id}/control", json_body=dict(params) or None, options=options
        )
        return CollabSetControlResult.construct_from(
            response.data if response else None, last_response=response
        )

    def request_control(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabRequestControlResult:
        """Ask the presenter for stage control (hand raise)

        POST /collab/rooms/{id}/control/request
        Source: src/backend/hosts/collab/routes.ts:838
        """
        response = self._request("POST", f"/collab/rooms/{id}/control/request", options=options)
        return CollabRequestControlResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_control_requests(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabListControlRequestsResult:
        """Get collab rooms control requests

        GET /collab/rooms/{id}/control/requests
        Source: src/backend/hosts/collab/routes.ts:900
        """
        response = self._request("GET", f"/collab/rooms/{id}/control/requests", options=options)
        return CollabListControlRequestsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete_control_request(
        self,
        id: str,
        user_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabDeleteControlRequestResult:
        """Delete collab rooms control requests

        DELETE /collab/rooms/{id}/control/requests/{userId}
        Source: src/backend/hosts/collab/routes.ts:924
        """
        response = self._request(
            "DELETE", f"/collab/rooms/{id}/control/requests/{user_id}", options=options
        )
        return CollabDeleteControlRequestResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_guest_link(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabSetGuestLinkParams],
    ) -> CollabSetGuestLinkResult:
        """Enable, rotate or disable the room's anonymous guest link (host only)

        POST /collab/rooms/{id}/guest-link
        Source: src/backend/hosts/collab/routes.ts:979
        """
        response = self._request(
            "POST",
            f"/collab/rooms/{id}/guest-link",
            json_body=dict(params) or None,
            options=options,
        )
        return CollabSetGuestLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_guest_stage(
        self,
        token: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabGetGuestStageResult:
        """Resolve a room's current stage for an anonymous guest

        GET /collab/guest/{token}
        Source: src/backend/hosts/collab/routes.ts:1059
        """
        response = self._request("GET", f"/collab/guest/{token}", options=options)
        return CollabGetGuestStageResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncCollabService(AsyncTermixService):
    service = "database"

    async def list_rooms(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> CollabListRoomsResult:
        """List rooms the caller belongs to

        GET /collab/rooms
        Source: src/backend/hosts/collab/routes.ts:162
        """
        response = await self._request("GET", "/collab/rooms", options=options)
        return CollabListRoomsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def create_room(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabCreateRoomParams],
    ) -> CollabCreateRoomResult:
        """Create a collaboration room

        POST /collab/rooms
        Source: src/backend/hosts/collab/routes.ts:109
        """
        response = await self._request(
            "POST", "/collab/rooms", json_body=dict(params) or None, options=options
        )
        return CollabCreateRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_room(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabGetRoomResult:
        """Get a room with members, online users and stage state

        GET /collab/rooms/{id}
        Source: src/backend/hosts/collab/routes.ts:183
        """
        response = await self._request("GET", f"/collab/rooms/{id}", options=options)
        return CollabGetRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete_room(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabDeleteRoomResult:
        """Permanently delete a room (host only)

        DELETE /collab/rooms/{id}
        Source: src/backend/hosts/collab/routes.ts:1182
        """
        response = await self._request("DELETE", f"/collab/rooms/{id}", options=options)
        return CollabDeleteRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def end_room(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabEndRoomResult:
        """End the meeting (host only)

        POST /collab/rooms/{id}/end
        Source: src/backend/hosts/collab/routes.ts:1117
        """
        response = await self._request("POST", f"/collab/rooms/{id}/end", options=options)
        return CollabEndRoomResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def invite_members(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabInviteMembersParams],
    ) -> CollabInviteMembersResult:
        """Invite users to a room (host only)

        POST /collab/rooms/{id}/members
        Source: src/backend/hosts/collab/routes.ts:256
        """
        response = await self._request(
            "POST", f"/collab/rooms/{id}/members", json_body=dict(params) or None, options=options
        )
        return CollabInviteMembersResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def remove_member(
        self,
        id: str,
        user_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabRemoveMemberResult:
        """Remove a member (host), or leave the room (self)

        DELETE /collab/rooms/{id}/members/{userId}
        Source: src/backend/hosts/collab/routes.ts:352
        """
        response = await self._request(
            "DELETE", f"/collab/rooms/{id}/members/{user_id}", options=options
        )
        return CollabRemoveMemberResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def present(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabPresentParams],
    ) -> CollabPresentResult:
        """Take the stage with one of your live sessions

        POST /collab/rooms/{id}/present
        Source: src/backend/hosts/collab/routes.ts:449
        """
        response = await self._request(
            "POST", f"/collab/rooms/{id}/present", json_body=dict(params) or None, options=options
        )
        return CollabPresentResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def stop_presenting(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabStopPresentingResult:
        """Stop presenting (presenter or host)

        POST /collab/rooms/{id}/stop
        Source: src/backend/hosts/collab/routes.ts:562
        """
        response = await self._request("POST", f"/collab/rooms/{id}/stop", options=options)
        return CollabStopPresentingResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_stage(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabGetStageResult:
        """Get connect info for the current stage (members only)

        GET /collab/rooms/{id}/stage
        Source: src/backend/hosts/collab/routes.ts:619
        """
        response = await self._request("GET", f"/collab/rooms/{id}/stage", options=options)
        return CollabGetStageResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_control(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabSetControlParams],
    ) -> CollabSetControlResult:
        """Grant or revoke stage control (presenter or host)

        POST /collab/rooms/{id}/control
        Source: src/backend/hosts/collab/routes.ts:755
        """
        response = await self._request(
            "POST", f"/collab/rooms/{id}/control", json_body=dict(params) or None, options=options
        )
        return CollabSetControlResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def request_control(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabRequestControlResult:
        """Ask the presenter for stage control (hand raise)

        POST /collab/rooms/{id}/control/request
        Source: src/backend/hosts/collab/routes.ts:838
        """
        response = await self._request(
            "POST", f"/collab/rooms/{id}/control/request", options=options
        )
        return CollabRequestControlResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_control_requests(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabListControlRequestsResult:
        """Get collab rooms control requests

        GET /collab/rooms/{id}/control/requests
        Source: src/backend/hosts/collab/routes.ts:900
        """
        response = await self._request(
            "GET", f"/collab/rooms/{id}/control/requests", options=options
        )
        return CollabListControlRequestsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete_control_request(
        self,
        id: str,
        user_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabDeleteControlRequestResult:
        """Delete collab rooms control requests

        DELETE /collab/rooms/{id}/control/requests/{userId}
        Source: src/backend/hosts/collab/routes.ts:924
        """
        response = await self._request(
            "DELETE", f"/collab/rooms/{id}/control/requests/{user_id}", options=options
        )
        return CollabDeleteControlRequestResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_guest_link(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[CollabSetGuestLinkParams],
    ) -> CollabSetGuestLinkResult:
        """Enable, rotate or disable the room's anonymous guest link (host only)

        POST /collab/rooms/{id}/guest-link
        Source: src/backend/hosts/collab/routes.ts:979
        """
        response = await self._request(
            "POST",
            f"/collab/rooms/{id}/guest-link",
            json_body=dict(params) or None,
            options=options,
        )
        return CollabSetGuestLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_guest_stage(
        self,
        token: str,
        *,
        options: RequestOptions | None = None,
    ) -> CollabGetGuestStageResult:
        """Resolve a room's current stage for an anonymous guest

        GET /collab/guest/{token}
        Source: src/backend/hosts/collab/routes.ts:1059
        """
        response = await self._request("GET", f"/collab/guest/{token}", options=options)
        return CollabGetGuestStageResult.construct_from(
            response.data if response else None, last_response=response
        )
