# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Dashboard: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._object import TermixObject
from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.dashboard import (
    DashboardCreateServiceLinkResult,
    DashboardDeleteServiceLinkResult,
    DashboardResetActivityResult,
    DashboardUpdateServiceLinkResult,
    DashboardUptimeResult,
)
from ..types.dashboard import (
    DashboardCreateServiceLinkParams,
    DashboardListRecentActivityParams,
    DashboardLogActivityParams,
    DashboardUpdateServiceLinkParams,
)


class DashboardService(TermixService):
    service = "dashboard"

    def delete_service_link(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DashboardDeleteServiceLinkResult:
        """Delete service link

        DELETE /service-links/{id}
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:133
        """
        response = self._request("DELETE", f"/service-links/{id}", options=options)
        return DashboardDeleteServiceLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    def update_service_link(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardUpdateServiceLinkParams],
    ) -> DashboardUpdateServiceLinkResult:
        """Update service link

        PUT /service-links/{id}
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:214
        """
        response = self._request(
            "PUT", f"/service-links/{id}", json_body=dict(params) or None, options=options
        )
        return DashboardUpdateServiceLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_service_links(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> list[Any]:
        """Get service links

        GET /service-links
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:36
        """
        response = self._request("GET", "/service-links", options=options)
        return response.data if response else []

    def create_service_link(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardCreateServiceLinkParams],
    ) -> DashboardCreateServiceLinkResult:
        """Create service link

        POST /service-links
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:78
        """
        response = self._request(
            "POST", "/service-links", json_body=dict(params) or None, options=options
        )
        return DashboardCreateServiceLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_recent_activity(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardListRecentActivityParams],
    ) -> list[Any]:
        """Get recent activity

        GET /activity/recent
        Source: src/backend/services/dashboard.ts:108
        """
        response = self._request(
            "GET", "/activity/recent", query=dict(params) or None, options=options
        )
        return response.data if response else []

    def log_activity(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardLogActivityParams],
    ) -> TermixObject:
        """Log a new activity

        POST /activity/log
        Source: src/backend/services/dashboard.ts:165
        """
        response = self._request(
            "POST", "/activity/log", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def reset_activity(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> DashboardResetActivityResult:
        """Reset recent activity

        DELETE /activity/reset
        Source: src/backend/services/dashboard.ts:294
        """
        response = self._request("DELETE", "/activity/reset", options=options)
        return DashboardResetActivityResult.construct_from(
            response.data if response else None, last_response=response
        )

    def uptime(self, *, options: RequestOptions | None = None) -> DashboardUptimeResult:
        """Get server uptime

        GET /uptime
        Source: src/backend/services/dashboard.ts:67
        """
        response = self._request("GET", "/uptime", options=options)
        return DashboardUptimeResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncDashboardService(AsyncTermixService):
    service = "dashboard"

    async def delete_service_link(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DashboardDeleteServiceLinkResult:
        """Delete service link

        DELETE /service-links/{id}
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:133
        """
        response = await self._request("DELETE", f"/service-links/{id}", options=options)
        return DashboardDeleteServiceLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def update_service_link(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardUpdateServiceLinkParams],
    ) -> DashboardUpdateServiceLinkResult:
        """Update service link

        PUT /service-links/{id}
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:214
        """
        response = await self._request(
            "PUT", f"/service-links/{id}", json_body=dict(params) or None, options=options
        )
        return DashboardUpdateServiceLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_service_links(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> list[Any]:
        """Get service links

        GET /service-links
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:36
        """
        response = await self._request("GET", "/service-links", options=options)
        return response.data if response else []

    async def create_service_link(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardCreateServiceLinkParams],
    ) -> DashboardCreateServiceLinkResult:
        """Create service link

        POST /service-links
        Source: src/backend/database/routes/dashboard-service-links-routes.ts:78
        """
        response = await self._request(
            "POST", "/service-links", json_body=dict(params) or None, options=options
        )
        return DashboardCreateServiceLinkResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_recent_activity(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardListRecentActivityParams],
    ) -> list[Any]:
        """Get recent activity

        GET /activity/recent
        Source: src/backend/services/dashboard.ts:108
        """
        response = await self._request(
            "GET", "/activity/recent", query=dict(params) or None, options=options
        )
        return response.data if response else []

    async def log_activity(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DashboardLogActivityParams],
    ) -> TermixObject:
        """Log a new activity

        POST /activity/log
        Source: src/backend/services/dashboard.ts:165
        """
        response = await self._request(
            "POST", "/activity/log", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def reset_activity(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> DashboardResetActivityResult:
        """Reset recent activity

        DELETE /activity/reset
        Source: src/backend/services/dashboard.ts:294
        """
        response = await self._request("DELETE", "/activity/reset", options=options)
        return DashboardResetActivityResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def uptime(self, *, options: RequestOptions | None = None) -> DashboardUptimeResult:
        """Get server uptime

        GET /uptime
        Source: src/backend/services/dashboard.ts:67
        """
        response = await self._request("GET", "/uptime", options=options)
        return DashboardUptimeResult.construct_from(
            response.data if response else None, last_response=response
        )
