# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Docker: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._object import TermixObject
from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.docker import (
    DockerConnectTotpResult,
    DockerConnectWarpgateResult,
    DockerDisconnectResult,
    DockerGetContainerLogsResult,
    DockerGetContainerResult,
    DockerGetContainerStatsResult,
    DockerGetStatusResult,
    DockerKeepaliveResult,
    DockerPauseResult,
    DockerRemoveContainerResult,
    DockerRestartResult,
    DockerStartResult,
    DockerStopResult,
    DockerUnpauseResult,
)
from ..types.docker import (
    DockerConnectParams,
    DockerConnectTotpParams,
    DockerConnectWarpgateParams,
    DockerDisconnectParams,
    DockerGetContainerLogsParams,
    DockerGetStatusParams,
    DockerKeepaliveParams,
    DockerListContainersParams,
    DockerRemoveContainerParams,
)


class DockerService(TermixService):
    service = "docker"

    def get_container_stats(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerGetContainerStatsResult:
        """Get container stats

        GET /docker/containers/{sessionId}/{containerId}/stats
        Source: src/backend/hosts/docker/container-routes.ts:1038
        """
        response = self._request(
            "GET", f"/docker/containers/{session_id}/{container_id}/stats", options=options
        )
        return DockerGetContainerStatsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_container(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerGetContainerResult:
        """Get container details

        GET /docker/containers/{sessionId}/{containerId}
        Source: src/backend/hosts/docker/container-routes.ts:189
        """
        response = self._request(
            "GET", f"/docker/containers/{session_id}/{container_id}", options=options
        )
        return DockerGetContainerResult.construct_from(
            response.data if response else None, last_response=response
        )

    def start(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerStartResult:
        """Start container

        POST /docker/containers/{sessionId}/{containerId}/start
        Source: src/backend/hosts/docker/container-routes.ts:285
        """
        response = self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/start", options=options
        )
        return DockerStartResult.construct_from(
            response.data if response else None, last_response=response
        )

    def stop(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerStopResult:
        """Stop container

        POST /docker/containers/{sessionId}/{containerId}/stop
        Source: src/backend/hosts/docker/container-routes.ts:385
        """
        response = self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/stop", options=options
        )
        return DockerStopResult.construct_from(
            response.data if response else None, last_response=response
        )

    def restart(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerRestartResult:
        """Restart container

        POST /docker/containers/{sessionId}/{containerId}/restart
        Source: src/backend/hosts/docker/container-routes.ts:485
        """
        response = self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/restart", options=options
        )
        return DockerRestartResult.construct_from(
            response.data if response else None, last_response=response
        )

    def pause(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerPauseResult:
        """Pause container

        POST /docker/containers/{sessionId}/{containerId}/pause
        Source: src/backend/hosts/docker/container-routes.ts:585
        """
        response = self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/pause", options=options
        )
        return DockerPauseResult.construct_from(
            response.data if response else None, last_response=response
        )

    def unpause(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerUnpauseResult:
        """Unpause container

        POST /docker/containers/{sessionId}/{containerId}/unpause
        Source: src/backend/hosts/docker/container-routes.ts:685
        """
        response = self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/unpause", options=options
        )
        return DockerUnpauseResult.construct_from(
            response.data if response else None, last_response=response
        )

    def remove_container(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerRemoveContainerParams],
    ) -> DockerRemoveContainerResult:
        """Remove container

        DELETE /docker/containers/{sessionId}/{containerId}/remove
        Source: src/backend/hosts/docker/container-routes.ts:789
        """
        response = self._request(
            "DELETE",
            f"/docker/containers/{session_id}/{container_id}/remove",
            query=dict(params) or None,
            options=options,
        )
        return DockerRemoveContainerResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_containers(
        self,
        session_id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerListContainersParams],
    ) -> list[Any]:
        """List all containers

        GET /docker/containers/{sessionId}
        Source: src/backend/hosts/docker/container-routes.ts:82
        """
        response = self._request(
            "GET", f"/docker/containers/{session_id}", query=dict(params) or None, options=options
        )
        return response.data if response else []

    def get_container_logs(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerGetContainerLogsParams],
    ) -> DockerGetContainerLogsResult:
        """Get container logs

        GET /docker/containers/{sessionId}/{containerId}/logs
        Source: src/backend/hosts/docker/container-routes.ts:919
        """
        response = self._request(
            "GET",
            f"/docker/containers/{session_id}/{container_id}/logs",
            query=dict(params) or None,
            options=options,
        )
        return DockerGetContainerLogsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def disconnect(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerDisconnectParams],
    ) -> DockerDisconnectResult:
        """Disconnect SSH session

        POST /docker/ssh/disconnect
        Source: src/backend/hosts/docker/routes.ts:1087
        """
        response = self._request(
            "POST", "/docker/ssh/disconnect", json_body=dict(params) or None, options=options
        )
        return DockerDisconnectResult.construct_from(
            response.data if response else None, last_response=response
        )

    def connect_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerConnectTotpParams],
    ) -> DockerConnectTotpResult:
        """Verify TOTP and complete connection

        POST /docker/ssh/connect-totp
        Source: src/backend/hosts/docker/routes.ts:1128
        """
        response = self._request(
            "POST", "/docker/ssh/connect-totp", json_body=dict(params) or None, options=options
        )
        return DockerConnectTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    def connect_warpgate(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerConnectWarpgateParams],
    ) -> DockerConnectWarpgateResult:
        """Complete Warpgate authentication

        POST /docker/ssh/connect-warpgate
        Source: src/backend/hosts/docker/routes.ts:1314
        """
        response = self._request(
            "POST", "/docker/ssh/connect-warpgate", json_body=dict(params) or None, options=options
        )
        return DockerConnectWarpgateResult.construct_from(
            response.data if response else None, last_response=response
        )

    def keepalive(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerKeepaliveParams],
    ) -> DockerKeepaliveResult:
        """Keep SSH session alive

        POST /docker/ssh/keepalive
        Source: src/backend/hosts/docker/routes.ts:1491
        """
        response = self._request(
            "POST", "/docker/ssh/keepalive", json_body=dict(params) or None, options=options
        )
        return DockerKeepaliveResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_status(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerGetStatusParams],
    ) -> DockerGetStatusResult:
        """Check SSH session status

        GET /docker/ssh/status
        Source: src/backend/hosts/docker/routes.ts:1543
        """
        response = self._request(
            "GET", "/docker/ssh/status", query=dict(params) or None, options=options
        )
        return DockerGetStatusResult.construct_from(
            response.data if response else None, last_response=response
        )

    def validate_session(
        self,
        session_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> TermixObject:
        """Validate Docker availability

        GET /docker/validate/{sessionId}
        Source: src/backend/hosts/docker/routes.ts:1584
        """
        response = self._request("GET", f"/docker/validate/{session_id}", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def connect(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerConnectParams],
    ) -> TermixObject:
        """Establish SSH session for Docker

        POST /docker/ssh/connect
        Source: src/backend/hosts/docker/routes.ts:94
        """
        response = self._request(
            "POST", "/docker/ssh/connect", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncDockerService(AsyncTermixService):
    service = "docker"

    async def get_container_stats(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerGetContainerStatsResult:
        """Get container stats

        GET /docker/containers/{sessionId}/{containerId}/stats
        Source: src/backend/hosts/docker/container-routes.ts:1038
        """
        response = await self._request(
            "GET", f"/docker/containers/{session_id}/{container_id}/stats", options=options
        )
        return DockerGetContainerStatsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_container(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerGetContainerResult:
        """Get container details

        GET /docker/containers/{sessionId}/{containerId}
        Source: src/backend/hosts/docker/container-routes.ts:189
        """
        response = await self._request(
            "GET", f"/docker/containers/{session_id}/{container_id}", options=options
        )
        return DockerGetContainerResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def start(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerStartResult:
        """Start container

        POST /docker/containers/{sessionId}/{containerId}/start
        Source: src/backend/hosts/docker/container-routes.ts:285
        """
        response = await self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/start", options=options
        )
        return DockerStartResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def stop(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerStopResult:
        """Stop container

        POST /docker/containers/{sessionId}/{containerId}/stop
        Source: src/backend/hosts/docker/container-routes.ts:385
        """
        response = await self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/stop", options=options
        )
        return DockerStopResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def restart(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerRestartResult:
        """Restart container

        POST /docker/containers/{sessionId}/{containerId}/restart
        Source: src/backend/hosts/docker/container-routes.ts:485
        """
        response = await self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/restart", options=options
        )
        return DockerRestartResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def pause(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerPauseResult:
        """Pause container

        POST /docker/containers/{sessionId}/{containerId}/pause
        Source: src/backend/hosts/docker/container-routes.ts:585
        """
        response = await self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/pause", options=options
        )
        return DockerPauseResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def unpause(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> DockerUnpauseResult:
        """Unpause container

        POST /docker/containers/{sessionId}/{containerId}/unpause
        Source: src/backend/hosts/docker/container-routes.ts:685
        """
        response = await self._request(
            "POST", f"/docker/containers/{session_id}/{container_id}/unpause", options=options
        )
        return DockerUnpauseResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def remove_container(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerRemoveContainerParams],
    ) -> DockerRemoveContainerResult:
        """Remove container

        DELETE /docker/containers/{sessionId}/{containerId}/remove
        Source: src/backend/hosts/docker/container-routes.ts:789
        """
        response = await self._request(
            "DELETE",
            f"/docker/containers/{session_id}/{container_id}/remove",
            query=dict(params) or None,
            options=options,
        )
        return DockerRemoveContainerResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_containers(
        self,
        session_id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerListContainersParams],
    ) -> list[Any]:
        """List all containers

        GET /docker/containers/{sessionId}
        Source: src/backend/hosts/docker/container-routes.ts:82
        """
        response = await self._request(
            "GET", f"/docker/containers/{session_id}", query=dict(params) or None, options=options
        )
        return response.data if response else []

    async def get_container_logs(
        self,
        session_id: str,
        container_id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerGetContainerLogsParams],
    ) -> DockerGetContainerLogsResult:
        """Get container logs

        GET /docker/containers/{sessionId}/{containerId}/logs
        Source: src/backend/hosts/docker/container-routes.ts:919
        """
        response = await self._request(
            "GET",
            f"/docker/containers/{session_id}/{container_id}/logs",
            query=dict(params) or None,
            options=options,
        )
        return DockerGetContainerLogsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def disconnect(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerDisconnectParams],
    ) -> DockerDisconnectResult:
        """Disconnect SSH session

        POST /docker/ssh/disconnect
        Source: src/backend/hosts/docker/routes.ts:1087
        """
        response = await self._request(
            "POST", "/docker/ssh/disconnect", json_body=dict(params) or None, options=options
        )
        return DockerDisconnectResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def connect_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerConnectTotpParams],
    ) -> DockerConnectTotpResult:
        """Verify TOTP and complete connection

        POST /docker/ssh/connect-totp
        Source: src/backend/hosts/docker/routes.ts:1128
        """
        response = await self._request(
            "POST", "/docker/ssh/connect-totp", json_body=dict(params) or None, options=options
        )
        return DockerConnectTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def connect_warpgate(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerConnectWarpgateParams],
    ) -> DockerConnectWarpgateResult:
        """Complete Warpgate authentication

        POST /docker/ssh/connect-warpgate
        Source: src/backend/hosts/docker/routes.ts:1314
        """
        response = await self._request(
            "POST", "/docker/ssh/connect-warpgate", json_body=dict(params) or None, options=options
        )
        return DockerConnectWarpgateResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def keepalive(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerKeepaliveParams],
    ) -> DockerKeepaliveResult:
        """Keep SSH session alive

        POST /docker/ssh/keepalive
        Source: src/backend/hosts/docker/routes.ts:1491
        """
        response = await self._request(
            "POST", "/docker/ssh/keepalive", json_body=dict(params) or None, options=options
        )
        return DockerKeepaliveResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_status(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerGetStatusParams],
    ) -> DockerGetStatusResult:
        """Check SSH session status

        GET /docker/ssh/status
        Source: src/backend/hosts/docker/routes.ts:1543
        """
        response = await self._request(
            "GET", "/docker/ssh/status", query=dict(params) or None, options=options
        )
        return DockerGetStatusResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def validate_session(
        self,
        session_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> TermixObject:
        """Validate Docker availability

        GET /docker/validate/{sessionId}
        Source: src/backend/hosts/docker/routes.ts:1584
        """
        response = await self._request("GET", f"/docker/validate/{session_id}", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def connect(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[DockerConnectParams],
    ) -> TermixObject:
        """Establish SSH session for Docker

        POST /docker/ssh/connect
        Source: src/backend/hosts/docker/routes.ts:94
        """
        response = await self._request(
            "POST", "/docker/ssh/connect", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )
