# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Metrics: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._object import TermixObject
from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.metrics import (
    MetricsAddFirewallRuleResult,
    MetricsClearConnectionsResult,
    MetricsConfigureHealthResult,
    MetricsConnectTotpResult,
    MetricsGetCronResult,
    MetricsGetDiskBreakdownResult,
    MetricsGetFirewallResult,
    MetricsGetGlobalSettingsHistoryResult,
    MetricsGetGlobalSettingsResult,
    MetricsGetHealthResult,
    MetricsGetLogsResult,
    MetricsGetMetricsHistoryResult,
    MetricsGetMetricsPreferencesResult,
    MetricsGetMetricsResult,
    MetricsGetPackagesResult,
    MetricsGetPlatformResult,
    MetricsGetProcessesResult,
    MetricsGetServicesResult,
    MetricsGetSslResult,
    MetricsGetStatusResult,
    MetricsGetTailscaleResult,
    MetricsGetTimersResult,
    MetricsGetTopMemoryResult,
    MetricsGetUsersResult,
    MetricsGetWireguardResult,
    MetricsIssueSslResult,
    MetricsListLogFilesResult,
    MetricsListStatusesResult,
    MetricsMetricsHeartbeatResult,
    MetricsNotifyHostDeletedResult,
    MetricsNotifyHostUpdatedResult,
    MetricsPersistFirewallResult,
    MetricsRefreshPollingResult,
    MetricsRenewSslResult,
    MetricsRevokeSslResult,
    MetricsRunHealthCheckResult,
    MetricsRunPackageActionResult,
    MetricsRunServiceActionResult,
    MetricsRunTailscaleActionResult,
    MetricsRunUserActionResult,
    MetricsRunWireguardActionResult,
    MetricsSaveGlobalSettingsHistoryResult,
    MetricsSetCronResult,
    MetricsSetGlobalSettingsResult,
    MetricsSetMetricsPreferencesResult,
    MetricsSignalProcessResult,
    MetricsStopMetricsResult,
    MetricsUnregisterMetricsViewerResult,
)
from ..types.metrics import (
    MetricsAddFirewallRuleParams,
    MetricsConfigureHealthParams,
    MetricsConnectTotpParams,
    MetricsGetLogsParams,
    MetricsIssueSslParams,
    MetricsListStatusesParams,
    MetricsMetricsHeartbeatParams,
    MetricsNotifyHostDeletedParams,
    MetricsNotifyHostUpdatedParams,
    MetricsRegisterMetricsViewerParams,
    MetricsRenewSslParams,
    MetricsRevokeSslParams,
    MetricsRunPackageActionParams,
    MetricsRunServiceActionParams,
    MetricsRunTailscaleActionParams,
    MetricsRunUserActionParams,
    MetricsRunWireguardActionParams,
    MetricsSaveGlobalSettingsHistoryParams,
    MetricsSetCronParams,
    MetricsSetGlobalSettingsParams,
    MetricsSetMetricsPreferencesParams,
    MetricsSignalProcessParams,
    MetricsStopMetricsParams,
    MetricsUnregisterMetricsViewerParams,
)


class MetricsService(TermixService):
    service = "metrics"

    def get_cron(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetCronResult:
        """Get host metrics managers cron

        GET /host-metrics/managers/cron/{id}
        Source: src/backend/hosts/metrics/managers/cron.ts:85
        """
        response = self._request("GET", f"/host-metrics/managers/cron/{id}", options=options)
        return MetricsGetCronResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_cron(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSetCronParams],
    ) -> MetricsSetCronResult:
        """Create host metrics managers cron

        POST /host-metrics/managers/cron/{id}
        Source: src/backend/hosts/metrics/managers/cron.ts:94
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/cron/{id}",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsSetCronResult.construct_from(
            response.data if response else None, last_response=response
        )

    def persist_firewall(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsPersistFirewallResult:
        """Create host metrics managers firewall persist

        POST /host-metrics/managers/firewall/{id}/persist
        Source: src/backend/hosts/metrics/managers/firewall.ts:104
        """
        response = self._request(
            "POST", f"/host-metrics/managers/firewall/{id}/persist", options=options
        )
        return MetricsPersistFirewallResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_firewall(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetFirewallResult:
        """Get host metrics managers firewall

        GET /host-metrics/managers/firewall/{id}
        Source: src/backend/hosts/metrics/managers/firewall.ts:51
        """
        response = self._request("GET", f"/host-metrics/managers/firewall/{id}", options=options)
        return MetricsGetFirewallResult.construct_from(
            response.data if response else None, last_response=response
        )

    def add_firewall_rule(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsAddFirewallRuleParams],
    ) -> MetricsAddFirewallRuleResult:
        """Create host metrics managers firewall rule

        POST /host-metrics/managers/firewall/{id}/rule
        Source: src/backend/hosts/metrics/managers/firewall.ts:59
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/firewall/{id}/rule",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsAddFirewallRuleResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_health(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetHealthResult:
        """Get host metrics managers health

        GET /host-metrics/managers/health/{id}
        Source: src/backend/hosts/metrics/managers/health.ts:146
        """
        response = self._request("GET", f"/host-metrics/managers/health/{id}", options=options)
        return MetricsGetHealthResult.construct_from(
            response.data if response else None, last_response=response
        )

    def configure_health(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsConfigureHealthParams],
    ) -> MetricsConfigureHealthResult:
        """Create host metrics managers health config

        POST /host-metrics/managers/health/{id}/config
        Source: src/backend/hosts/metrics/managers/health.ts:197
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/health/{id}/config",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsConfigureHealthResult.construct_from(
            response.data if response else None, last_response=response
        )

    def run_health_check(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsRunHealthCheckResult:
        """Create host metrics managers health run

        POST /host-metrics/managers/health/{id}/run
        Source: src/backend/hosts/metrics/managers/health.ts:232
        """
        response = self._request("POST", f"/host-metrics/managers/health/{id}/run", options=options)
        return MetricsRunHealthCheckResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_platform(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetPlatformResult:
        """Detect available management tooling on a host

        GET /host-metrics/platform/{id}
        Source: src/backend/hosts/metrics/managers/index.ts:45
        """
        response = self._request("GET", f"/host-metrics/platform/{id}", options=options)
        return MetricsGetPlatformResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_log_files(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsListLogFilesResult:
        """Get host metrics managers logs files

        GET /host-metrics/managers/logs/{id}/files
        Source: src/backend/hosts/metrics/managers/logs.ts:45
        """
        response = self._request("GET", f"/host-metrics/managers/logs/{id}/files", options=options)
        return MetricsListLogFilesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_logs(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsGetLogsParams],
    ) -> MetricsGetLogsResult:
        """Get host metrics managers logs

        GET /host-metrics/managers/logs/{id}
        Source: src/backend/hosts/metrics/managers/logs.ts:59
        """
        response = self._request(
            "GET", f"/host-metrics/managers/logs/{id}", query=dict(params) or None, options=options
        )
        return MetricsGetLogsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def run_package_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunPackageActionParams],
    ) -> MetricsRunPackageActionResult:
        """Create host metrics managers packages action

        POST /host-metrics/managers/packages/{id}/action
        Source: src/backend/hosts/metrics/managers/packages.ts:111
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/packages/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunPackageActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_packages(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetPackagesResult:
        """Get host metrics managers packages

        GET /host-metrics/managers/packages/{id}
        Source: src/backend/hosts/metrics/managers/packages.ts:96
        """
        response = self._request("GET", f"/host-metrics/managers/packages/{id}", options=options)
        return MetricsGetPackagesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def signal_process(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSignalProcessParams],
    ) -> MetricsSignalProcessResult:
        """Send a signal to a process (TERM/KILL/HUP/INT)

        POST /host-metrics/managers/processes/{id}/signal
        Source: src/backend/hosts/metrics/managers/processes.ts:104
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/processes/{id}/signal",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsSignalProcessResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_processes(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetProcessesResult:
        """List processes (rich, sortable, filterable client-side)

        GET /host-metrics/managers/processes/{id}
        Source: src/backend/hosts/metrics/managers/processes.ts:70
        """
        response = self._request("GET", f"/host-metrics/managers/processes/{id}", options=options)
        return MetricsGetProcessesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def run_service_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunServiceActionParams],
    ) -> MetricsRunServiceActionResult:
        """Start/stop/restart/enable/disable a systemd service

        POST /host-metrics/managers/services/{id}/action
        Source: src/backend/hosts/metrics/managers/services.ts:104
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/services/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunServiceActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_services(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetServicesResult:
        """List systemd services

        GET /host-metrics/managers/services/{id}
        Source: src/backend/hosts/metrics/managers/services.ts:70
        """
        response = self._request("GET", f"/host-metrics/managers/services/{id}", options=options)
        return MetricsGetServicesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_top_memory(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetTopMemoryResult:
        """Get host metrics managers top memory

        GET /host-metrics/managers/top-memory/{id}
        Source: src/backend/hosts/metrics/managers/simple-reads.ts:112
        """
        response = self._request("GET", f"/host-metrics/managers/top-memory/{id}", options=options)
        return MetricsGetTopMemoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_timers(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetTimersResult:
        """Get host metrics managers timers

        GET /host-metrics/managers/timers/{id}
        Source: src/backend/hosts/metrics/managers/simple-reads.ts:121
        """
        response = self._request("GET", f"/host-metrics/managers/timers/{id}", options=options)
        return MetricsGetTimersResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_disk_breakdown(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetDiskBreakdownResult:
        """Get host metrics managers disk breakdown

        GET /host-metrics/managers/disk-breakdown/{id}
        Source: src/backend/hosts/metrics/managers/simple-reads.ts:130
        """
        response = self._request(
            "GET", f"/host-metrics/managers/disk-breakdown/{id}", options=options
        )
        return MetricsGetDiskBreakdownResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetSslResult:
        """Get host metrics managers ssl

        GET /host-metrics/managers/ssl/{id}
        Source: src/backend/hosts/metrics/managers/ssl.ts:153
        """
        response = self._request("GET", f"/host-metrics/managers/ssl/{id}", options=options)
        return MetricsGetSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    def issue_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsIssueSslParams],
    ) -> MetricsIssueSslResult:
        """Create host metrics managers ssl issue

        POST /host-metrics/managers/ssl/{id}/issue
        Source: src/backend/hosts/metrics/managers/ssl.ts:185
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/ssl/{id}/issue",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsIssueSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    def renew_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRenewSslParams],
    ) -> MetricsRenewSslResult:
        """Create host metrics managers ssl renew

        POST /host-metrics/managers/ssl/{id}/renew
        Source: src/backend/hosts/metrics/managers/ssl.ts:234
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/ssl/{id}/renew",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRenewSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    def revoke_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRevokeSslParams],
    ) -> MetricsRevokeSslResult:
        """Revoke and remove an issued certificate (certbot or acme.sh)

        POST /host-metrics/managers/ssl/{id}/revoke
        Source: src/backend/hosts/metrics/managers/ssl.ts:287
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/ssl/{id}/revoke",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRevokeSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_tailscale(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetTailscaleResult:
        """Get Tailscale status and IPs

        GET /host-metrics/managers/tailscale/{id}
        Source: src/backend/hosts/metrics/managers/tailscale.ts:116
        """
        response = self._request("GET", f"/host-metrics/managers/tailscale/{id}", options=options)
        return MetricsGetTailscaleResult.construct_from(
            response.data if response else None, last_response=response
        )

    def run_tailscale_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunTailscaleActionParams],
    ) -> MetricsRunTailscaleActionResult:
        """Connect or disconnect Tailscale

        POST /host-metrics/managers/tailscale/{id}/action
        Source: src/backend/hosts/metrics/managers/tailscale.ts:152
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/tailscale/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunTailscaleActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_users(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetUsersResult:
        """Get host metrics managers users

        GET /host-metrics/managers/users/{id}
        Source: src/backend/hosts/metrics/managers/users.ts:79
        """
        response = self._request("GET", f"/host-metrics/managers/users/{id}", options=options)
        return MetricsGetUsersResult.construct_from(
            response.data if response else None, last_response=response
        )

    def run_user_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunUserActionParams],
    ) -> MetricsRunUserActionResult:
        """Create host metrics managers users action

        POST /host-metrics/managers/users/{id}/action
        Source: src/backend/hosts/metrics/managers/users.ts:96
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/users/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunUserActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_wireguard(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetWireguardResult:
        """Get WireGuard interfaces and peers

        GET /host-metrics/managers/wireguard/{id}
        Source: src/backend/hosts/metrics/managers/wireguard.ts:140
        """
        response = self._request("GET", f"/host-metrics/managers/wireguard/{id}", options=options)
        return MetricsGetWireguardResult.construct_from(
            response.data if response else None, last_response=response
        )

    def run_wireguard_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunWireguardActionParams],
    ) -> MetricsRunWireguardActionResult:
        """Bring a WireGuard interface up or down

        POST /host-metrics/managers/wireguard/{id}/action
        Source: src/backend/hosts/metrics/managers/wireguard.ts:191
        """
        response = self._request(
            "POST",
            f"/host-metrics/managers/wireguard/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunWireguardActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_metrics_preferences(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSetMetricsPreferencesParams],
    ) -> MetricsSetMetricsPreferencesResult:
        """Save the Host Metrics layout for a host

        POST /host-metrics/preferences/{id}
        Source: src/backend/hosts/metrics/preferences-routes.ts:163
        """
        response = self._request(
            "POST",
            f"/host-metrics/preferences/{id}",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsSetMetricsPreferencesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_metrics_preferences(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetMetricsPreferencesResult:
        """Get the Host Metrics layout for a host

        GET /host-metrics/preferences/{id}
        Source: src/backend/hosts/metrics/preferences-routes.ts:88
        """
        response = self._request("GET", f"/host-metrics/preferences/{id}", options=options)
        return MetricsGetMetricsPreferencesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_metrics_history(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetMetricsHistoryResult:
        """Get historical metrics for a host

        GET /metrics/history/{id}
        Source: src/backend/hosts/metrics/history-routes.ts:64
        """
        response = self._request("GET", f"/metrics/history/{id}", options=options)
        return MetricsGetMetricsHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_statuses(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsListStatusesParams],
    ) -> MetricsListStatusesResult:
        """Get all host statuses

        GET /status
        Source: src/backend/hosts/metrics/index.ts:1930
        """
        response = self._request("GET", "/status", query=dict(params) or None, options=options)
        return MetricsListStatusesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_status(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetStatusResult:
        """Get host status by ID

        GET /status/{id}
        Source: src/backend/hosts/metrics/index.ts:1990
        """
        response = self._request("GET", f"/status/{id}", options=options)
        return MetricsGetStatusResult.construct_from(
            response.data if response else None, last_response=response
        )

    def clear_connections(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsClearConnectionsResult:
        """Clear all SSH connections

        POST /clear-connections
        Source: src/backend/hosts/metrics/index.ts:2033
        """
        response = self._request("POST", "/clear-connections", options=options)
        return MetricsClearConnectionsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def refresh_polling(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsRefreshPollingResult:
        """Refresh polling

        POST /refresh
        Source: src/backend/hosts/metrics/index.ts:2061
        """
        response = self._request("POST", "/refresh", options=options)
        return MetricsRefreshPollingResult.construct_from(
            response.data if response else None, last_response=response
        )

    def notify_host_updated(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsNotifyHostUpdatedParams],
    ) -> MetricsNotifyHostUpdatedResult:
        """Start polling for updated host

        POST /host-updated
        Source: src/backend/hosts/metrics/index.ts:2104
        """
        response = self._request(
            "POST", "/host-updated", json_body=dict(params) or None, options=options
        )
        return MetricsNotifyHostUpdatedResult.construct_from(
            response.data if response else None, last_response=response
        )

    def notify_host_deleted(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsNotifyHostDeletedParams],
    ) -> MetricsNotifyHostDeletedResult:
        """Stop polling for deleted host

        POST /host-deleted
        Source: src/backend/hosts/metrics/index.ts:2167
        """
        response = self._request(
            "POST", "/host-deleted", json_body=dict(params) or None, options=options
        )
        return MetricsNotifyHostDeletedResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_metrics(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetMetricsResult:
        """Get host metrics

        GET /metrics/{id}
        Source: src/backend/hosts/metrics/index.ts:2217
        """
        response = self._request("GET", f"/metrics/{id}", options=options)
        return MetricsGetMetricsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def start_metrics(self, id: str, *, options: RequestOptions | None = None) -> TermixObject:
        """Start metrics collection

        POST /metrics/start/{id}
        Source: src/backend/hosts/metrics/index.ts:2280
        """
        response = self._request("POST", f"/metrics/start/{id}", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def stop_metrics(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsStopMetricsParams],
    ) -> MetricsStopMetricsResult:
        """Stop metrics collection

        POST /metrics/stop/{id}
        Source: src/backend/hosts/metrics/index.ts:2734
        """
        response = self._request(
            "POST", f"/metrics/stop/{id}", json_body=dict(params) or None, options=options
        )
        return MetricsStopMetricsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def connect_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsConnectTotpParams],
    ) -> MetricsConnectTotpResult:
        """Complete TOTP verification for metrics

        POST /metrics/connect-totp
        Source: src/backend/hosts/metrics/index.ts:2804
        """
        response = self._request(
            "POST", "/metrics/connect-totp", json_body=dict(params) or None, options=options
        )
        return MetricsConnectTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_global_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSetGlobalSettingsParams],
    ) -> MetricsSetGlobalSettingsResult:
        """Update global monitoring defaults

        POST /global-settings
        Source: src/backend/hosts/metrics/settings-routes.ts:103
        """
        response = self._request(
            "POST", "/global-settings", json_body=dict(params) or None, options=options
        )
        return MetricsSetGlobalSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_global_settings(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetGlobalSettingsResult:
        """Get global monitoring defaults

        GET /global-settings
        Source: src/backend/hosts/metrics/settings-routes.ts:43
        """
        response = self._request("GET", "/global-settings", options=options)
        return MetricsGetGlobalSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_global_settings_history(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetGlobalSettingsHistoryResult:
        """Get metrics history retention setting

        GET /global-settings/history
        Source: src/backend/hosts/metrics/settings-routes.ts:185
        """
        response = self._request("GET", "/global-settings/history", options=options)
        return MetricsGetGlobalSettingsHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    def save_global_settings_history(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSaveGlobalSettingsHistoryParams],
    ) -> MetricsSaveGlobalSettingsHistoryResult:
        """Update metrics history retention setting

        POST /global-settings/history
        Source: src/backend/hosts/metrics/settings-routes.ts:229
        """
        response = self._request(
            "POST", "/global-settings/history", json_body=dict(params) or None, options=options
        )
        return MetricsSaveGlobalSettingsHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    def register_metrics_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRegisterMetricsViewerParams],
    ) -> TermixObject:
        """Register metrics viewer

        POST /metrics/register-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:132
        """
        response = self._request(
            "POST", "/metrics/register-viewer", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def unregister_metrics_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsUnregisterMetricsViewerParams],
    ) -> MetricsUnregisterMetricsViewerResult:
        """Unregister metrics viewer

        POST /metrics/unregister-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:259
        """
        response = self._request(
            "POST", "/metrics/unregister-viewer", json_body=dict(params) or None, options=options
        )
        return MetricsUnregisterMetricsViewerResult.construct_from(
            response.data if response else None, last_response=response
        )

    def metrics_heartbeat(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsMetricsHeartbeatParams],
    ) -> MetricsMetricsHeartbeatResult:
        """Update viewer heartbeat

        POST /metrics/heartbeat
        Source: src/backend/hosts/metrics/viewer-routes.ts:73
        """
        response = self._request(
            "POST", "/metrics/heartbeat", json_body=dict(params) or None, options=options
        )
        return MetricsMetricsHeartbeatResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncMetricsService(AsyncTermixService):
    service = "metrics"

    async def get_cron(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetCronResult:
        """Get host metrics managers cron

        GET /host-metrics/managers/cron/{id}
        Source: src/backend/hosts/metrics/managers/cron.ts:85
        """
        response = await self._request("GET", f"/host-metrics/managers/cron/{id}", options=options)
        return MetricsGetCronResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_cron(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSetCronParams],
    ) -> MetricsSetCronResult:
        """Create host metrics managers cron

        POST /host-metrics/managers/cron/{id}
        Source: src/backend/hosts/metrics/managers/cron.ts:94
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/cron/{id}",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsSetCronResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def persist_firewall(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsPersistFirewallResult:
        """Create host metrics managers firewall persist

        POST /host-metrics/managers/firewall/{id}/persist
        Source: src/backend/hosts/metrics/managers/firewall.ts:104
        """
        response = await self._request(
            "POST", f"/host-metrics/managers/firewall/{id}/persist", options=options
        )
        return MetricsPersistFirewallResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_firewall(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetFirewallResult:
        """Get host metrics managers firewall

        GET /host-metrics/managers/firewall/{id}
        Source: src/backend/hosts/metrics/managers/firewall.ts:51
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/firewall/{id}", options=options
        )
        return MetricsGetFirewallResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def add_firewall_rule(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsAddFirewallRuleParams],
    ) -> MetricsAddFirewallRuleResult:
        """Create host metrics managers firewall rule

        POST /host-metrics/managers/firewall/{id}/rule
        Source: src/backend/hosts/metrics/managers/firewall.ts:59
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/firewall/{id}/rule",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsAddFirewallRuleResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_health(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetHealthResult:
        """Get host metrics managers health

        GET /host-metrics/managers/health/{id}
        Source: src/backend/hosts/metrics/managers/health.ts:146
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/health/{id}", options=options
        )
        return MetricsGetHealthResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def configure_health(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsConfigureHealthParams],
    ) -> MetricsConfigureHealthResult:
        """Create host metrics managers health config

        POST /host-metrics/managers/health/{id}/config
        Source: src/backend/hosts/metrics/managers/health.ts:197
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/health/{id}/config",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsConfigureHealthResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def run_health_check(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsRunHealthCheckResult:
        """Create host metrics managers health run

        POST /host-metrics/managers/health/{id}/run
        Source: src/backend/hosts/metrics/managers/health.ts:232
        """
        response = await self._request(
            "POST", f"/host-metrics/managers/health/{id}/run", options=options
        )
        return MetricsRunHealthCheckResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_platform(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetPlatformResult:
        """Detect available management tooling on a host

        GET /host-metrics/platform/{id}
        Source: src/backend/hosts/metrics/managers/index.ts:45
        """
        response = await self._request("GET", f"/host-metrics/platform/{id}", options=options)
        return MetricsGetPlatformResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_log_files(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsListLogFilesResult:
        """Get host metrics managers logs files

        GET /host-metrics/managers/logs/{id}/files
        Source: src/backend/hosts/metrics/managers/logs.ts:45
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/logs/{id}/files", options=options
        )
        return MetricsListLogFilesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_logs(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsGetLogsParams],
    ) -> MetricsGetLogsResult:
        """Get host metrics managers logs

        GET /host-metrics/managers/logs/{id}
        Source: src/backend/hosts/metrics/managers/logs.ts:59
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/logs/{id}", query=dict(params) or None, options=options
        )
        return MetricsGetLogsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def run_package_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunPackageActionParams],
    ) -> MetricsRunPackageActionResult:
        """Create host metrics managers packages action

        POST /host-metrics/managers/packages/{id}/action
        Source: src/backend/hosts/metrics/managers/packages.ts:111
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/packages/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunPackageActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_packages(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetPackagesResult:
        """Get host metrics managers packages

        GET /host-metrics/managers/packages/{id}
        Source: src/backend/hosts/metrics/managers/packages.ts:96
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/packages/{id}", options=options
        )
        return MetricsGetPackagesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def signal_process(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSignalProcessParams],
    ) -> MetricsSignalProcessResult:
        """Send a signal to a process (TERM/KILL/HUP/INT)

        POST /host-metrics/managers/processes/{id}/signal
        Source: src/backend/hosts/metrics/managers/processes.ts:104
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/processes/{id}/signal",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsSignalProcessResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_processes(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetProcessesResult:
        """List processes (rich, sortable, filterable client-side)

        GET /host-metrics/managers/processes/{id}
        Source: src/backend/hosts/metrics/managers/processes.ts:70
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/processes/{id}", options=options
        )
        return MetricsGetProcessesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def run_service_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunServiceActionParams],
    ) -> MetricsRunServiceActionResult:
        """Start/stop/restart/enable/disable a systemd service

        POST /host-metrics/managers/services/{id}/action
        Source: src/backend/hosts/metrics/managers/services.ts:104
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/services/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunServiceActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_services(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetServicesResult:
        """List systemd services

        GET /host-metrics/managers/services/{id}
        Source: src/backend/hosts/metrics/managers/services.ts:70
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/services/{id}", options=options
        )
        return MetricsGetServicesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_top_memory(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetTopMemoryResult:
        """Get host metrics managers top memory

        GET /host-metrics/managers/top-memory/{id}
        Source: src/backend/hosts/metrics/managers/simple-reads.ts:112
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/top-memory/{id}", options=options
        )
        return MetricsGetTopMemoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_timers(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetTimersResult:
        """Get host metrics managers timers

        GET /host-metrics/managers/timers/{id}
        Source: src/backend/hosts/metrics/managers/simple-reads.ts:121
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/timers/{id}", options=options
        )
        return MetricsGetTimersResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_disk_breakdown(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetDiskBreakdownResult:
        """Get host metrics managers disk breakdown

        GET /host-metrics/managers/disk-breakdown/{id}
        Source: src/backend/hosts/metrics/managers/simple-reads.ts:130
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/disk-breakdown/{id}", options=options
        )
        return MetricsGetDiskBreakdownResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetSslResult:
        """Get host metrics managers ssl

        GET /host-metrics/managers/ssl/{id}
        Source: src/backend/hosts/metrics/managers/ssl.ts:153
        """
        response = await self._request("GET", f"/host-metrics/managers/ssl/{id}", options=options)
        return MetricsGetSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def issue_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsIssueSslParams],
    ) -> MetricsIssueSslResult:
        """Create host metrics managers ssl issue

        POST /host-metrics/managers/ssl/{id}/issue
        Source: src/backend/hosts/metrics/managers/ssl.ts:185
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/ssl/{id}/issue",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsIssueSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def renew_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRenewSslParams],
    ) -> MetricsRenewSslResult:
        """Create host metrics managers ssl renew

        POST /host-metrics/managers/ssl/{id}/renew
        Source: src/backend/hosts/metrics/managers/ssl.ts:234
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/ssl/{id}/renew",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRenewSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def revoke_ssl(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRevokeSslParams],
    ) -> MetricsRevokeSslResult:
        """Revoke and remove an issued certificate (certbot or acme.sh)

        POST /host-metrics/managers/ssl/{id}/revoke
        Source: src/backend/hosts/metrics/managers/ssl.ts:287
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/ssl/{id}/revoke",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRevokeSslResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_tailscale(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetTailscaleResult:
        """Get Tailscale status and IPs

        GET /host-metrics/managers/tailscale/{id}
        Source: src/backend/hosts/metrics/managers/tailscale.ts:116
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/tailscale/{id}", options=options
        )
        return MetricsGetTailscaleResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def run_tailscale_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunTailscaleActionParams],
    ) -> MetricsRunTailscaleActionResult:
        """Connect or disconnect Tailscale

        POST /host-metrics/managers/tailscale/{id}/action
        Source: src/backend/hosts/metrics/managers/tailscale.ts:152
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/tailscale/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunTailscaleActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_users(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetUsersResult:
        """Get host metrics managers users

        GET /host-metrics/managers/users/{id}
        Source: src/backend/hosts/metrics/managers/users.ts:79
        """
        response = await self._request("GET", f"/host-metrics/managers/users/{id}", options=options)
        return MetricsGetUsersResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def run_user_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunUserActionParams],
    ) -> MetricsRunUserActionResult:
        """Create host metrics managers users action

        POST /host-metrics/managers/users/{id}/action
        Source: src/backend/hosts/metrics/managers/users.ts:96
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/users/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunUserActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_wireguard(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetWireguardResult:
        """Get WireGuard interfaces and peers

        GET /host-metrics/managers/wireguard/{id}
        Source: src/backend/hosts/metrics/managers/wireguard.ts:140
        """
        response = await self._request(
            "GET", f"/host-metrics/managers/wireguard/{id}", options=options
        )
        return MetricsGetWireguardResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def run_wireguard_action(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRunWireguardActionParams],
    ) -> MetricsRunWireguardActionResult:
        """Bring a WireGuard interface up or down

        POST /host-metrics/managers/wireguard/{id}/action
        Source: src/backend/hosts/metrics/managers/wireguard.ts:191
        """
        response = await self._request(
            "POST",
            f"/host-metrics/managers/wireguard/{id}/action",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsRunWireguardActionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_metrics_preferences(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSetMetricsPreferencesParams],
    ) -> MetricsSetMetricsPreferencesResult:
        """Save the Host Metrics layout for a host

        POST /host-metrics/preferences/{id}
        Source: src/backend/hosts/metrics/preferences-routes.ts:163
        """
        response = await self._request(
            "POST",
            f"/host-metrics/preferences/{id}",
            json_body=dict(params) or None,
            options=options,
        )
        return MetricsSetMetricsPreferencesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_metrics_preferences(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetMetricsPreferencesResult:
        """Get the Host Metrics layout for a host

        GET /host-metrics/preferences/{id}
        Source: src/backend/hosts/metrics/preferences-routes.ts:88
        """
        response = await self._request("GET", f"/host-metrics/preferences/{id}", options=options)
        return MetricsGetMetricsPreferencesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_metrics_history(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetMetricsHistoryResult:
        """Get historical metrics for a host

        GET /metrics/history/{id}
        Source: src/backend/hosts/metrics/history-routes.ts:64
        """
        response = await self._request("GET", f"/metrics/history/{id}", options=options)
        return MetricsGetMetricsHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_statuses(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsListStatusesParams],
    ) -> MetricsListStatusesResult:
        """Get all host statuses

        GET /status
        Source: src/backend/hosts/metrics/index.ts:1930
        """
        response = await self._request(
            "GET", "/status", query=dict(params) or None, options=options
        )
        return MetricsListStatusesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_status(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetStatusResult:
        """Get host status by ID

        GET /status/{id}
        Source: src/backend/hosts/metrics/index.ts:1990
        """
        response = await self._request("GET", f"/status/{id}", options=options)
        return MetricsGetStatusResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def clear_connections(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsClearConnectionsResult:
        """Clear all SSH connections

        POST /clear-connections
        Source: src/backend/hosts/metrics/index.ts:2033
        """
        response = await self._request("POST", "/clear-connections", options=options)
        return MetricsClearConnectionsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def refresh_polling(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsRefreshPollingResult:
        """Refresh polling

        POST /refresh
        Source: src/backend/hosts/metrics/index.ts:2061
        """
        response = await self._request("POST", "/refresh", options=options)
        return MetricsRefreshPollingResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def notify_host_updated(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsNotifyHostUpdatedParams],
    ) -> MetricsNotifyHostUpdatedResult:
        """Start polling for updated host

        POST /host-updated
        Source: src/backend/hosts/metrics/index.ts:2104
        """
        response = await self._request(
            "POST", "/host-updated", json_body=dict(params) or None, options=options
        )
        return MetricsNotifyHostUpdatedResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def notify_host_deleted(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsNotifyHostDeletedParams],
    ) -> MetricsNotifyHostDeletedResult:
        """Stop polling for deleted host

        POST /host-deleted
        Source: src/backend/hosts/metrics/index.ts:2167
        """
        response = await self._request(
            "POST", "/host-deleted", json_body=dict(params) or None, options=options
        )
        return MetricsNotifyHostDeletedResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_metrics(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetMetricsResult:
        """Get host metrics

        GET /metrics/{id}
        Source: src/backend/hosts/metrics/index.ts:2217
        """
        response = await self._request("GET", f"/metrics/{id}", options=options)
        return MetricsGetMetricsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def start_metrics(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> TermixObject:
        """Start metrics collection

        POST /metrics/start/{id}
        Source: src/backend/hosts/metrics/index.ts:2280
        """
        response = await self._request("POST", f"/metrics/start/{id}", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def stop_metrics(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsStopMetricsParams],
    ) -> MetricsStopMetricsResult:
        """Stop metrics collection

        POST /metrics/stop/{id}
        Source: src/backend/hosts/metrics/index.ts:2734
        """
        response = await self._request(
            "POST", f"/metrics/stop/{id}", json_body=dict(params) or None, options=options
        )
        return MetricsStopMetricsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def connect_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsConnectTotpParams],
    ) -> MetricsConnectTotpResult:
        """Complete TOTP verification for metrics

        POST /metrics/connect-totp
        Source: src/backend/hosts/metrics/index.ts:2804
        """
        response = await self._request(
            "POST", "/metrics/connect-totp", json_body=dict(params) or None, options=options
        )
        return MetricsConnectTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_global_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSetGlobalSettingsParams],
    ) -> MetricsSetGlobalSettingsResult:
        """Update global monitoring defaults

        POST /global-settings
        Source: src/backend/hosts/metrics/settings-routes.ts:103
        """
        response = await self._request(
            "POST", "/global-settings", json_body=dict(params) or None, options=options
        )
        return MetricsSetGlobalSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_global_settings(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetGlobalSettingsResult:
        """Get global monitoring defaults

        GET /global-settings
        Source: src/backend/hosts/metrics/settings-routes.ts:43
        """
        response = await self._request("GET", "/global-settings", options=options)
        return MetricsGetGlobalSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_global_settings_history(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> MetricsGetGlobalSettingsHistoryResult:
        """Get metrics history retention setting

        GET /global-settings/history
        Source: src/backend/hosts/metrics/settings-routes.ts:185
        """
        response = await self._request("GET", "/global-settings/history", options=options)
        return MetricsGetGlobalSettingsHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def save_global_settings_history(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsSaveGlobalSettingsHistoryParams],
    ) -> MetricsSaveGlobalSettingsHistoryResult:
        """Update metrics history retention setting

        POST /global-settings/history
        Source: src/backend/hosts/metrics/settings-routes.ts:229
        """
        response = await self._request(
            "POST", "/global-settings/history", json_body=dict(params) or None, options=options
        )
        return MetricsSaveGlobalSettingsHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def register_metrics_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsRegisterMetricsViewerParams],
    ) -> TermixObject:
        """Register metrics viewer

        POST /metrics/register-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:132
        """
        response = await self._request(
            "POST", "/metrics/register-viewer", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def unregister_metrics_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsUnregisterMetricsViewerParams],
    ) -> MetricsUnregisterMetricsViewerResult:
        """Unregister metrics viewer

        POST /metrics/unregister-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:259
        """
        response = await self._request(
            "POST", "/metrics/unregister-viewer", json_body=dict(params) or None, options=options
        )
        return MetricsUnregisterMetricsViewerResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def metrics_heartbeat(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[MetricsMetricsHeartbeatParams],
    ) -> MetricsMetricsHeartbeatResult:
        """Update viewer heartbeat

        POST /metrics/heartbeat
        Source: src/backend/hosts/metrics/viewer-routes.ts:73
        """
        response = await self._request(
            "POST", "/metrics/heartbeat", json_body=dict(params) or None, options=options
        )
        return MetricsMetricsHeartbeatResult.construct_from(
            response.data if response else None, last_response=response
        )
