# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""OpenTabs: generated resource module."""

from __future__ import annotations

import builtins
from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.open_tabs import (
    OpenTabsDeleteResult,
    OpenTabsListActiveSessionsItem,
    OpenTabsListItem,
    OpenTabsReplaceAllResult,
    OpenTabsUpdateResult,
    OpenTabsUpsertResult,
)
from ..types.open_tabs import OpenTabsReplaceAllParams, OpenTabsUpdateParams, OpenTabsUpsertParams


class OpenTabsService(TermixService):
    service = "database"

    def upsert(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[OpenTabsUpsertParams],
    ) -> OpenTabsUpsertResult:
        """Upsert a single open tab for the current user

        POST /open-tabs
        Source: src/backend/database/routes/open-tabs.ts:105
        """
        response = self._request(
            "POST", "/open-tabs", json_body=dict(params) or None, options=options
        )
        return OpenTabsUpsertResult.construct_from(
            response.data if response else None, last_response=response
        )

    def replace_all(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[OpenTabsReplaceAllParams],
    ) -> OpenTabsReplaceAllResult:
        """Bulk replace all open tabs for the current user

        PUT /open-tabs
        Source: src/backend/database/routes/open-tabs.ts:163
        """
        response = self._request(
            "PUT", "/open-tabs", json_body=dict(params) or None, options=options
        )
        return OpenTabsReplaceAllResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> builtins.list[OpenTabsListItem]:
        """Get all open tabs for the current user

        GET /open-tabs
        Source: src/backend/database/routes/open-tabs.ts:52
        """
        response = self._request("GET", "/open-tabs", options=options)
        return OpenTabsListItem.construct_from(
            response.data if response else [], last_response=response
        )

    def update(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[OpenTabsUpdateParams],
    ) -> OpenTabsUpdateResult:
        """Update a single open tab

        PATCH /open-tabs/{id}
        Source: src/backend/database/routes/open-tabs.ts:211
        """
        response = self._request(
            "PATCH", f"/open-tabs/{id}", json_body=dict(params) or None, options=options
        )
        return OpenTabsUpdateResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> OpenTabsDeleteResult:
        """Delete a single open tab

        DELETE /open-tabs/{id}
        Source: src/backend/database/routes/open-tabs.ts:259
        """
        response = self._request("DELETE", f"/open-tabs/{id}", options=options)
        return OpenTabsDeleteResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_active_sessions(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> builtins.list[OpenTabsListActiveSessionsItem]:
        """Get all active backend sessions for the current user

        GET /open-tabs/active-sessions
        Source: src/backend/database/routes/open-tabs.ts:321
        """
        response = self._request("GET", "/open-tabs/active-sessions", options=options)
        return OpenTabsListActiveSessionsItem.construct_from(
            response.data if response else [], last_response=response
        )


class AsyncOpenTabsService(AsyncTermixService):
    service = "database"

    async def upsert(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[OpenTabsUpsertParams],
    ) -> OpenTabsUpsertResult:
        """Upsert a single open tab for the current user

        POST /open-tabs
        Source: src/backend/database/routes/open-tabs.ts:105
        """
        response = await self._request(
            "POST", "/open-tabs", json_body=dict(params) or None, options=options
        )
        return OpenTabsUpsertResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def replace_all(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[OpenTabsReplaceAllParams],
    ) -> OpenTabsReplaceAllResult:
        """Bulk replace all open tabs for the current user

        PUT /open-tabs
        Source: src/backend/database/routes/open-tabs.ts:163
        """
        response = await self._request(
            "PUT", "/open-tabs", json_body=dict(params) or None, options=options
        )
        return OpenTabsReplaceAllResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> builtins.list[OpenTabsListItem]:
        """Get all open tabs for the current user

        GET /open-tabs
        Source: src/backend/database/routes/open-tabs.ts:52
        """
        response = await self._request("GET", "/open-tabs", options=options)
        return OpenTabsListItem.construct_from(
            response.data if response else [], last_response=response
        )

    async def update(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[OpenTabsUpdateParams],
    ) -> OpenTabsUpdateResult:
        """Update a single open tab

        PATCH /open-tabs/{id}
        Source: src/backend/database/routes/open-tabs.ts:211
        """
        response = await self._request(
            "PATCH", f"/open-tabs/{id}", json_body=dict(params) or None, options=options
        )
        return OpenTabsUpdateResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> OpenTabsDeleteResult:
        """Delete a single open tab

        DELETE /open-tabs/{id}
        Source: src/backend/database/routes/open-tabs.ts:259
        """
        response = await self._request("DELETE", f"/open-tabs/{id}", options=options)
        return OpenTabsDeleteResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_active_sessions(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> builtins.list[OpenTabsListActiveSessionsItem]:
        """Get all active backend sessions for the current user

        GET /open-tabs/active-sessions
        Source: src/backend/database/routes/open-tabs.ts:321
        """
        response = await self._request("GET", "/open-tabs/active-sessions", options=options)
        return OpenTabsListActiveSessionsItem.construct_from(
            response.data if response else [], last_response=response
        )
