# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""ProxmoxStats: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._object import TermixObject
from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.proxmox_stats import (
    ProxmoxStatsGetHistoryResult,
    ProxmoxStatsHeartbeatResult,
    ProxmoxStatsRetrieveResult,
    ProxmoxStatsStopResult,
    ProxmoxStatsUnregisterViewerResult,
)
from ..types.proxmox_stats import (
    ProxmoxStatsHeartbeatParams,
    ProxmoxStatsRegisterViewerParams,
    ProxmoxStatsStopParams,
    ProxmoxStatsUnregisterViewerParams,
)


class ProxmoxStatsService(TermixService):
    service = "metrics"

    def get_history(
        self,
        host_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> ProxmoxStatsGetHistoryResult:
        """Get historical Proxmox node stats for a host

        GET /proxmox-stats/history/{hostId}
        Source: src/backend/hosts/metrics/proxmox-stats-history-routes.ts:62
        """
        response = self._request("GET", f"/proxmox-stats/history/{host_id}", options=options)
        return ProxmoxStatsGetHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    def start(self, id: str, *, options: RequestOptions | None = None) -> TermixObject:
        """Start Proxmox stats collection

        POST /proxmox-stats/start/{id}
        Source: src/backend/hosts/metrics/proxmox-stats-routes.ts:127
        """
        response = self._request("POST", f"/proxmox-stats/start/{id}", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def stop(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsStopParams],
    ) -> ProxmoxStatsStopResult:
        """Stop Proxmox stats collection

        POST /proxmox-stats/stop/{id}
        Source: src/backend/hosts/metrics/proxmox-stats-routes.ts:227
        """
        response = self._request(
            "POST", f"/proxmox-stats/stop/{id}", json_body=dict(params) or None, options=options
        )
        return ProxmoxStatsStopResult.construct_from(
            response.data if response else None, last_response=response
        )

    def retrieve(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> ProxmoxStatsRetrieveResult:
        """Get cached Proxmox node stats for a host

        GET /proxmox-stats/{id}
        Source: src/backend/hosts/metrics/proxmox-stats-routes.ts:76
        """
        response = self._request("GET", f"/proxmox-stats/{id}", options=options)
        return ProxmoxStatsRetrieveResult.construct_from(
            response.data if response else None, last_response=response
        )

    def register_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsRegisterViewerParams],
    ) -> TermixObject:
        """Create proxmox stats register viewer

        POST /proxmox-stats/register-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:132
        """
        response = self._request(
            "POST",
            "/proxmox-stats/register-viewer",
            json_body=dict(params) or None,
            options=options,
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def unregister_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsUnregisterViewerParams],
    ) -> ProxmoxStatsUnregisterViewerResult:
        """Create proxmox stats unregister viewer

        POST /proxmox-stats/unregister-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:259
        """
        response = self._request(
            "POST",
            "/proxmox-stats/unregister-viewer",
            json_body=dict(params) or None,
            options=options,
        )
        return ProxmoxStatsUnregisterViewerResult.construct_from(
            response.data if response else None, last_response=response
        )

    def heartbeat(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsHeartbeatParams],
    ) -> ProxmoxStatsHeartbeatResult:
        """Create proxmox stats heartbeat

        POST /proxmox-stats/heartbeat
        Source: src/backend/hosts/metrics/viewer-routes.ts:73
        """
        response = self._request(
            "POST", "/proxmox-stats/heartbeat", json_body=dict(params) or None, options=options
        )
        return ProxmoxStatsHeartbeatResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncProxmoxStatsService(AsyncTermixService):
    service = "metrics"

    async def get_history(
        self,
        host_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> ProxmoxStatsGetHistoryResult:
        """Get historical Proxmox node stats for a host

        GET /proxmox-stats/history/{hostId}
        Source: src/backend/hosts/metrics/proxmox-stats-history-routes.ts:62
        """
        response = await self._request("GET", f"/proxmox-stats/history/{host_id}", options=options)
        return ProxmoxStatsGetHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def start(self, id: str, *, options: RequestOptions | None = None) -> TermixObject:
        """Start Proxmox stats collection

        POST /proxmox-stats/start/{id}
        Source: src/backend/hosts/metrics/proxmox-stats-routes.ts:127
        """
        response = await self._request("POST", f"/proxmox-stats/start/{id}", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def stop(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsStopParams],
    ) -> ProxmoxStatsStopResult:
        """Stop Proxmox stats collection

        POST /proxmox-stats/stop/{id}
        Source: src/backend/hosts/metrics/proxmox-stats-routes.ts:227
        """
        response = await self._request(
            "POST", f"/proxmox-stats/stop/{id}", json_body=dict(params) or None, options=options
        )
        return ProxmoxStatsStopResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def retrieve(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> ProxmoxStatsRetrieveResult:
        """Get cached Proxmox node stats for a host

        GET /proxmox-stats/{id}
        Source: src/backend/hosts/metrics/proxmox-stats-routes.ts:76
        """
        response = await self._request("GET", f"/proxmox-stats/{id}", options=options)
        return ProxmoxStatsRetrieveResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def register_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsRegisterViewerParams],
    ) -> TermixObject:
        """Create proxmox stats register viewer

        POST /proxmox-stats/register-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:132
        """
        response = await self._request(
            "POST",
            "/proxmox-stats/register-viewer",
            json_body=dict(params) or None,
            options=options,
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def unregister_viewer(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsUnregisterViewerParams],
    ) -> ProxmoxStatsUnregisterViewerResult:
        """Create proxmox stats unregister viewer

        POST /proxmox-stats/unregister-viewer
        Source: src/backend/hosts/metrics/viewer-routes.ts:259
        """
        response = await self._request(
            "POST",
            "/proxmox-stats/unregister-viewer",
            json_body=dict(params) or None,
            options=options,
        )
        return ProxmoxStatsUnregisterViewerResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def heartbeat(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[ProxmoxStatsHeartbeatParams],
    ) -> ProxmoxStatsHeartbeatResult:
        """Create proxmox stats heartbeat

        POST /proxmox-stats/heartbeat
        Source: src/backend/hosts/metrics/viewer-routes.ts:73
        """
        response = await self._request(
            "POST", "/proxmox-stats/heartbeat", json_body=dict(params) or None, options=options
        )
        return ProxmoxStatsHeartbeatResult.construct_from(
            response.data if response else None, last_response=response
        )
