# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Snippets: generated resource module."""

from __future__ import annotations

import builtins
from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.snippets import (
    SnippetsBulkImportResult,
    SnippetsCreateFolderResult,
    SnippetsCreateResult,
    SnippetsDeleteFolderResult,
    SnippetsDeleteResult,
    SnippetsExecuteResult,
    SnippetsExportResult,
    SnippetsRenameFolderResult,
    SnippetsReorderResult,
    SnippetsRetrieveResult,
    SnippetsUpdateFolderMetadataResult,
    SnippetsUpdateResult,
)
from ..types.snippets import (
    SnippetsBulkImportParams,
    SnippetsCreateFolderParams,
    SnippetsCreateParams,
    SnippetsExecuteParams,
    SnippetsRenameFolderParams,
    SnippetsReorderParams,
    SnippetsUpdateFolderMetadataParams,
)


class SnippetsService(TermixService):
    service = "database"

    def list(self, *, options: RequestOptions | None = None) -> builtins.list[Any]:
        """Get all snippets

        GET /snippets
        Source: src/backend/database/routes/snippets.ts:932
        """
        response = self._request("GET", "/snippets", options=options)
        return response.data if response else []

    def create(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsCreateParams]
    ) -> SnippetsCreateResult:
        """Create a new snippet

        POST /snippets
        Source: src/backend/database/routes/snippets.ts:1073
        """
        response = self._request(
            "POST", "/snippets", json_body=dict(params) or None, options=options
        )
        return SnippetsCreateResult.construct_from(
            response.data if response else None, last_response=response
        )

    def retrieve(self, id: str, *, options: RequestOptions | None = None) -> SnippetsRetrieveResult:
        """Get a specific snippet

        GET /snippets/{id}
        Source: src/backend/database/routes/snippets.ts:1003
        """
        response = self._request("GET", f"/snippets/{id}", options=options)
        return SnippetsRetrieveResult.construct_from(
            response.data if response else None, last_response=response
        )

    def update(self, id: str, *, options: RequestOptions | None = None) -> SnippetsUpdateResult:
        """Update a snippet

        PUT /snippets/{id}
        Source: src/backend/database/routes/snippets.ts:1183
        """
        response = self._request("PUT", f"/snippets/{id}", options=options)
        return SnippetsUpdateResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete(self, id: str, *, options: RequestOptions | None = None) -> SnippetsDeleteResult:
        """Delete a snippet

        DELETE /snippets/{id}
        Source: src/backend/database/routes/snippets.ts:1261
        """
        response = self._request("DELETE", f"/snippets/{id}", options=options)
        return SnippetsDeleteResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_folders(self, *, options: RequestOptions | None = None) -> builtins.list[Any]:
        """Get all snippet folders

        GET /snippets/folders
        Source: src/backend/database/routes/snippets.ts:90
        """
        response = self._request("GET", "/snippets/folders", options=options)
        return response.data if response else []

    def create_folder(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsCreateFolderParams]
    ) -> SnippetsCreateFolderResult:
        """Create a new snippet folder

        POST /snippets/folders
        Source: src/backend/database/routes/snippets.ts:144
        """
        response = self._request(
            "POST", "/snippets/folders", json_body=dict(params) or None, options=options
        )
        return SnippetsCreateFolderResult.construct_from(
            response.data if response else None, last_response=response
        )

    def update_folder_metadata(
        self,
        name: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[SnippetsUpdateFolderMetadataParams],
    ) -> SnippetsUpdateFolderMetadataResult:
        """Update snippet folder metadata

        PUT /snippets/folders/{name}/metadata
        Source: src/backend/database/routes/snippets.ts:226
        """
        response = self._request(
            "PUT",
            f"/snippets/folders/{name}/metadata",
            json_body=dict(params) or None,
            options=options,
        )
        return SnippetsUpdateFolderMetadataResult.construct_from(
            response.data if response else None, last_response=response
        )

    def rename_folder(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsRenameFolderParams]
    ) -> SnippetsRenameFolderResult:
        """Rename a snippet folder

        PUT /snippets/folders/rename
        Source: src/backend/database/routes/snippets.ts:306
        """
        response = self._request(
            "PUT", "/snippets/folders/rename", json_body=dict(params) or None, options=options
        )
        return SnippetsRenameFolderResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete_folder(
        self, name: str, *, options: RequestOptions | None = None
    ) -> SnippetsDeleteFolderResult:
        """Delete a snippet folder

        DELETE /snippets/folders/{name}
        Source: src/backend/database/routes/snippets.ts:382
        """
        response = self._request("DELETE", f"/snippets/folders/{name}", options=options)
        return SnippetsDeleteFolderResult.construct_from(
            response.data if response else None, last_response=response
        )

    def reorder(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsReorderParams]
    ) -> SnippetsReorderResult:
        """Reorder snippets

        PUT /snippets/reorder
        Source: src/backend/database/routes/snippets.ts:466
        """
        response = self._request(
            "PUT", "/snippets/reorder", json_body=dict(params) or None, options=options
        )
        return SnippetsReorderResult.construct_from(
            response.data if response else None, last_response=response
        )

    def execute(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsExecuteParams]
    ) -> SnippetsExecuteResult:
        """Execute a snippet on a host

        POST /snippets/execute
        Source: src/backend/database/routes/snippets.ts:549
        """
        response = self._request(
            "POST", "/snippets/execute", json_body=dict(params) or None, options=options
        )
        return SnippetsExecuteResult.construct_from(
            response.data if response else None, last_response=response
        )

    def export(self, *, options: RequestOptions | None = None) -> SnippetsExportResult:
        """Export all snippets and folders as JSON

        GET /snippets/export
        Source: src/backend/database/routes/snippets.ts:796
        """
        response = self._request("GET", "/snippets/export", options=options)
        return SnippetsExportResult.construct_from(
            response.data if response else None, last_response=response
        )

    def bulk_import(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsBulkImportParams]
    ) -> SnippetsBulkImportResult:
        """Bulk import snippets and folders from JSON

        POST /snippets/bulk-import
        Source: src/backend/database/routes/snippets.ts:872
        """
        response = self._request(
            "POST", "/snippets/bulk-import", json_body=dict(params) or None, options=options
        )
        return SnippetsBulkImportResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncSnippetsService(AsyncTermixService):
    service = "database"

    async def list(self, *, options: RequestOptions | None = None) -> builtins.list[Any]:
        """Get all snippets

        GET /snippets
        Source: src/backend/database/routes/snippets.ts:932
        """
        response = await self._request("GET", "/snippets", options=options)
        return response.data if response else []

    async def create(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsCreateParams]
    ) -> SnippetsCreateResult:
        """Create a new snippet

        POST /snippets
        Source: src/backend/database/routes/snippets.ts:1073
        """
        response = await self._request(
            "POST", "/snippets", json_body=dict(params) or None, options=options
        )
        return SnippetsCreateResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def retrieve(
        self, id: str, *, options: RequestOptions | None = None
    ) -> SnippetsRetrieveResult:
        """Get a specific snippet

        GET /snippets/{id}
        Source: src/backend/database/routes/snippets.ts:1003
        """
        response = await self._request("GET", f"/snippets/{id}", options=options)
        return SnippetsRetrieveResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def update(
        self, id: str, *, options: RequestOptions | None = None
    ) -> SnippetsUpdateResult:
        """Update a snippet

        PUT /snippets/{id}
        Source: src/backend/database/routes/snippets.ts:1183
        """
        response = await self._request("PUT", f"/snippets/{id}", options=options)
        return SnippetsUpdateResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete(
        self, id: str, *, options: RequestOptions | None = None
    ) -> SnippetsDeleteResult:
        """Delete a snippet

        DELETE /snippets/{id}
        Source: src/backend/database/routes/snippets.ts:1261
        """
        response = await self._request("DELETE", f"/snippets/{id}", options=options)
        return SnippetsDeleteResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_folders(self, *, options: RequestOptions | None = None) -> builtins.list[Any]:
        """Get all snippet folders

        GET /snippets/folders
        Source: src/backend/database/routes/snippets.ts:90
        """
        response = await self._request("GET", "/snippets/folders", options=options)
        return response.data if response else []

    async def create_folder(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsCreateFolderParams]
    ) -> SnippetsCreateFolderResult:
        """Create a new snippet folder

        POST /snippets/folders
        Source: src/backend/database/routes/snippets.ts:144
        """
        response = await self._request(
            "POST", "/snippets/folders", json_body=dict(params) or None, options=options
        )
        return SnippetsCreateFolderResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def update_folder_metadata(
        self,
        name: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[SnippetsUpdateFolderMetadataParams],
    ) -> SnippetsUpdateFolderMetadataResult:
        """Update snippet folder metadata

        PUT /snippets/folders/{name}/metadata
        Source: src/backend/database/routes/snippets.ts:226
        """
        response = await self._request(
            "PUT",
            f"/snippets/folders/{name}/metadata",
            json_body=dict(params) or None,
            options=options,
        )
        return SnippetsUpdateFolderMetadataResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def rename_folder(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsRenameFolderParams]
    ) -> SnippetsRenameFolderResult:
        """Rename a snippet folder

        PUT /snippets/folders/rename
        Source: src/backend/database/routes/snippets.ts:306
        """
        response = await self._request(
            "PUT", "/snippets/folders/rename", json_body=dict(params) or None, options=options
        )
        return SnippetsRenameFolderResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete_folder(
        self, name: str, *, options: RequestOptions | None = None
    ) -> SnippetsDeleteFolderResult:
        """Delete a snippet folder

        DELETE /snippets/folders/{name}
        Source: src/backend/database/routes/snippets.ts:382
        """
        response = await self._request("DELETE", f"/snippets/folders/{name}", options=options)
        return SnippetsDeleteFolderResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def reorder(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsReorderParams]
    ) -> SnippetsReorderResult:
        """Reorder snippets

        PUT /snippets/reorder
        Source: src/backend/database/routes/snippets.ts:466
        """
        response = await self._request(
            "PUT", "/snippets/reorder", json_body=dict(params) or None, options=options
        )
        return SnippetsReorderResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def execute(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsExecuteParams]
    ) -> SnippetsExecuteResult:
        """Execute a snippet on a host

        POST /snippets/execute
        Source: src/backend/database/routes/snippets.ts:549
        """
        response = await self._request(
            "POST", "/snippets/execute", json_body=dict(params) or None, options=options
        )
        return SnippetsExecuteResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def export(self, *, options: RequestOptions | None = None) -> SnippetsExportResult:
        """Export all snippets and folders as JSON

        GET /snippets/export
        Source: src/backend/database/routes/snippets.ts:796
        """
        response = await self._request("GET", "/snippets/export", options=options)
        return SnippetsExportResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def bulk_import(
        self, *, options: RequestOptions | None = None, **params: Unpack[SnippetsBulkImportParams]
    ) -> SnippetsBulkImportResult:
        """Bulk import snippets and folders from JSON

        POST /snippets/bulk-import
        Source: src/backend/database/routes/snippets.ts:872
        """
        response = await self._request(
            "POST", "/snippets/bulk-import", json_body=dict(params) or None, options=options
        )
        return SnippetsBulkImportResult.construct_from(
            response.data if response else None, last_response=response
        )
