# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Terminal: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._object import TermixObject
from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.terminal import (
    TerminalClearCommandHistoryResult,
    TerminalDeleteCommandHistoryEntriesResult,
    TerminalGetSessionSettingsResult,
    TerminalSetSessionSettingsResult,
)
from ..types.terminal import (
    TerminalDeleteCommandHistoryEntriesParams,
    TerminalImageUploadParams,
    TerminalLogCommandParams,
    TerminalSetSessionSettingsParams,
)


class TerminalService(TermixService):
    service = "database"

    def image_upload(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalImageUploadParams],
    ) -> TermixObject:
        """Create terminal image upload

        POST /terminal/image-upload
        Source: src/backend/database/routes/terminal.ts:120
        """
        response = self._request(
            "POST", "/terminal/image-upload", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def log_command(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalLogCommandParams],
    ) -> TermixObject:
        """Save command to history

        POST /terminal/command_history
        Source: src/backend/database/routes/terminal.ts:358
        """
        response = self._request(
            "POST", "/terminal/command_history", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def list_command_history(
        self,
        host_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> list[Any]:
        """Get command history

        GET /terminal/command_history/{hostId}
        Source: src/backend/database/routes/terminal.ts:470
        """
        response = self._request("GET", f"/terminal/command_history/{host_id}", options=options)
        return response.data if response else []

    def clear_command_history(
        self,
        host_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> TerminalClearCommandHistoryResult:
        """Clear command history

        DELETE /terminal/command_history/{hostId}
        Source: src/backend/database/routes/terminal.ts:592
        """
        response = self._request("DELETE", f"/terminal/command_history/{host_id}", options=options)
        return TerminalClearCommandHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete_command_history_entries(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalDeleteCommandHistoryEntriesParams],
    ) -> TerminalDeleteCommandHistoryEntriesResult:
        """Delete a specific command from history

        POST /terminal/command_history/delete
        Source: src/backend/database/routes/terminal.ts:533
        """
        response = self._request(
            "POST",
            "/terminal/command_history/delete",
            json_body=dict(params) or None,
            options=options,
        )
        return TerminalDeleteCommandHistoryEntriesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_session_settings(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> TerminalGetSessionSettingsResult:
        """Get session persistence settings

        GET /terminal/session_settings
        Source: src/backend/database/routes/terminal.ts:643
        """
        response = self._request("GET", "/terminal/session_settings", options=options)
        return TerminalGetSessionSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_session_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalSetSessionSettingsParams],
    ) -> TerminalSetSessionSettingsResult:
        """Update session persistence settings

        POST /terminal/session_settings
        Source: src/backend/database/routes/terminal.ts:697
        """
        response = self._request(
            "POST", "/terminal/session_settings", json_body=dict(params) or None, options=options
        )
        return TerminalSetSessionSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncTerminalService(AsyncTermixService):
    service = "database"

    async def image_upload(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalImageUploadParams],
    ) -> TermixObject:
        """Create terminal image upload

        POST /terminal/image-upload
        Source: src/backend/database/routes/terminal.ts:120
        """
        response = await self._request(
            "POST", "/terminal/image-upload", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def log_command(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalLogCommandParams],
    ) -> TermixObject:
        """Save command to history

        POST /terminal/command_history
        Source: src/backend/database/routes/terminal.ts:358
        """
        response = await self._request(
            "POST", "/terminal/command_history", json_body=dict(params) or None, options=options
        )
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_command_history(
        self,
        host_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> list[Any]:
        """Get command history

        GET /terminal/command_history/{hostId}
        Source: src/backend/database/routes/terminal.ts:470
        """
        response = await self._request(
            "GET", f"/terminal/command_history/{host_id}", options=options
        )
        return response.data if response else []

    async def clear_command_history(
        self,
        host_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> TerminalClearCommandHistoryResult:
        """Clear command history

        DELETE /terminal/command_history/{hostId}
        Source: src/backend/database/routes/terminal.ts:592
        """
        response = await self._request(
            "DELETE", f"/terminal/command_history/{host_id}", options=options
        )
        return TerminalClearCommandHistoryResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete_command_history_entries(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalDeleteCommandHistoryEntriesParams],
    ) -> TerminalDeleteCommandHistoryEntriesResult:
        """Delete a specific command from history

        POST /terminal/command_history/delete
        Source: src/backend/database/routes/terminal.ts:533
        """
        response = await self._request(
            "POST",
            "/terminal/command_history/delete",
            json_body=dict(params) or None,
            options=options,
        )
        return TerminalDeleteCommandHistoryEntriesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_session_settings(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> TerminalGetSessionSettingsResult:
        """Get session persistence settings

        GET /terminal/session_settings
        Source: src/backend/database/routes/terminal.ts:643
        """
        response = await self._request("GET", "/terminal/session_settings", options=options)
        return TerminalGetSessionSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_session_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[TerminalSetSessionSettingsParams],
    ) -> TerminalSetSessionSettingsResult:
        """Update session persistence settings

        POST /terminal/session_settings
        Source: src/backend/database/routes/terminal.ts:697
        """
        response = await self._request(
            "POST", "/terminal/session_settings", json_body=dict(params) or None, options=options
        )
        return TerminalSetSessionSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )
