# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.7.1-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Users: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._object import TermixObject
from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.users import (
    UsersChangePasswordResult,
    UsersCompleteResetResult,
    UsersDeleteAccountResult,
    UsersDisableTotpResult,
    UsersDismissDonationModalResult,
    UsersEnableTotpResult,
    UsersGetDataStatusResult,
    UsersGetMeResult,
    UsersGetTerminalImageStorageSettingsResult,
    UsersGetTokenResult,
    UsersGetTotpBackupCodesResult,
    UsersInitiateResetResult,
    UsersLinkOidcToPasswordResult,
    UsersListSessionsResult,
    UsersLogoutResult,
    UsersRegisterResult,
    UsersRevokeAllSessionsResult,
    UsersRevokeSessionResult,
    UsersSetupTotpResult,
    UsersTestTerminalImageStorageSettingsResult,
    UsersUnlinkOidcFromPasswordResult,
    UsersUnlockDataResult,
    UsersUpdateTerminalImageStorageSettingsResult,
    UsersVerifyResetCodeResult,
)
from ..types.users import (
    UsersChangePasswordParams,
    UsersCompleteResetParams,
    UsersDisableTotpParams,
    UsersEnableTotpParams,
    UsersGetTotpBackupCodesParams,
    UsersInitiateResetParams,
    UsersLinkOidcToPasswordParams,
    UsersRegisterParams,
    UsersRevokeAllSessionsParams,
    UsersTestTerminalImageStorageSettingsParams,
    UsersUnlinkOidcFromPasswordParams,
    UsersUnlockDataParams,
    UsersUpdateTerminalImageStorageSettingsParams,
    UsersVerifyResetCodeParams,
)


class UsersService(TermixService):
    service = "database"

    def get_me(self, *, options: RequestOptions | None = None) -> UsersGetMeResult:
        """Get current user's info

        GET /users/me
        Source: src/backend/database/routes/users.ts:2086
        """
        response = self._request("GET", "/users/me", options=options)
        return UsersGetMeResult.construct_from(
            response.data if response else None, last_response=response
        )

    def logout(self, *, options: RequestOptions | None = None) -> UsersLogoutResult:
        """User logout

        POST /users/logout
        Source: src/backend/database/routes/users.ts:1967
        """
        response = self._request("POST", "/users/logout", options=options)
        return UsersLogoutResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_token(self, *, options: RequestOptions | None = None) -> UsersGetTokenResult:
        """Get current session token

        GET /users/me/token
        Source: src/backend/database/routes/users.ts:2187
        """
        response = self._request("GET", "/users/me/token", options=options)
        return UsersGetTokenResult.construct_from(
            response.data if response else None, last_response=response
        )

    def dismiss_donation_modal(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersDismissDonationModalResult:
        """Permanently dismiss the donation reminder modal

        POST /users/me/dismiss-donation-modal
        Source: src/backend/database/routes/users.ts:2140
        """
        response = self._request("POST", "/users/me/dismiss-donation-modal", options=options)
        return UsersDismissDonationModalResult.construct_from(
            response.data if response else None, last_response=response
        )

    def change_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersChangePasswordParams],
    ) -> UsersChangePasswordResult:
        """Change user password

        POST /users/change-password
        Source: src/backend/database/routes/users.ts:2827
        """
        response = self._request(
            "POST", "/users/change-password", json_body=dict(params) or None, options=options
        )
        return UsersChangePasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete_account(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersDeleteAccountResult:
        """Delete user account

        DELETE /users/delete-account
        Source: src/backend/database/routes/users.ts:2746
        """
        response = self._request("DELETE", "/users/delete-account", options=options)
        return UsersDeleteAccountResult.construct_from(
            response.data if response else None, last_response=response
        )

    def unlock_data(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersUnlockDataParams],
    ) -> UsersUnlockDataResult:
        """Unlock user data

        POST /users/unlock-data
        Source: src/backend/database/routes/user-data-access-routes.ts:42
        """
        response = self._request(
            "POST", "/users/unlock-data", json_body=dict(params) or None, options=options
        )
        return UsersUnlockDataResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_data_status(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersGetDataStatusResult:
        """Check user data unlock status

        GET /users/data-status
        Source: src/backend/database/routes/user-data-access-routes.ts:105
        """
        response = self._request("GET", "/users/data-status", options=options)
        return UsersGetDataStatusResult.construct_from(
            response.data if response else None, last_response=response
        )

    def setup_totp(self, *, options: RequestOptions | None = None) -> UsersSetupTotpResult:
        """Setup TOTP

        POST /users/totp/setup
        Source: src/backend/database/routes/user-totp-routes.ts:123
        """
        response = self._request("POST", "/users/totp/setup", options=options)
        return UsersSetupTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    def enable_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersEnableTotpParams],
    ) -> UsersEnableTotpResult:
        """Enable TOTP

        POST /users/totp/enable
        Source: src/backend/database/routes/user-totp-routes.ts:186
        """
        response = self._request(
            "POST", "/users/totp/enable", json_body=dict(params) or None, options=options
        )
        return UsersEnableTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    def disable_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersDisableTotpParams],
    ) -> UsersDisableTotpResult:
        """Disable TOTP

        POST /users/totp/disable
        Source: src/backend/database/routes/user-totp-routes.ts:326
        """
        response = self._request(
            "POST", "/users/totp/disable", json_body=dict(params) or None, options=options
        )
        return UsersDisableTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_totp_backup_codes(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersGetTotpBackupCodesParams],
    ) -> UsersGetTotpBackupCodesResult:
        """Generate new backup codes

        POST /users/totp/backup-codes
        Source: src/backend/database/routes/user-totp-routes.ts:418
        """
        response = self._request(
            "POST", "/users/totp/backup-codes", json_body=dict(params) or None, options=options
        )
        return UsersGetTotpBackupCodesResult.construct_from(
            response.data if response else None, last_response=response
        )

    def proxy_login(self, *, options: RequestOptions | None = None) -> TermixObject:
        """Create users proxy login

        POST /users/proxy-login
        Source: src/backend/database/routes/users.ts:1584
        """
        response = self._request("POST", "/users/proxy-login", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    def unlink_oidc_from_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersUnlinkOidcFromPasswordParams],
    ) -> UsersUnlinkOidcFromPasswordResult:
        """Unlink OIDC from password account

        POST /users/unlink-oidc-from-password
        Source: src/backend/database/routes/user-oidc-account-routes.ts:201
        """
        response = self._request(
            "POST",
            "/users/unlink-oidc-from-password",
            json_body=dict(params) or None,
            options=options,
        )
        return UsersUnlinkOidcFromPasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    def link_oidc_to_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersLinkOidcToPasswordParams],
    ) -> UsersLinkOidcToPasswordResult:
        """Link OIDC user to password account

        POST /users/link-oidc-to-password
        Source: src/backend/database/routes/user-oidc-account-routes.ts:54
        """
        response = self._request(
            "POST", "/users/link-oidc-to-password", json_body=dict(params) or None, options=options
        )
        return UsersLinkOidcToPasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    def initiate_reset(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersInitiateResetParams],
    ) -> UsersInitiateResetResult:
        """Initiate password reset

        POST /users/initiate-reset
        Source: src/backend/database/routes/user-password-reset-routes.ts:137
        """
        response = self._request(
            "POST", "/users/initiate-reset", json_body=dict(params) or None, options=options
        )
        return UsersInitiateResetResult.construct_from(
            response.data if response else None, last_response=response
        )

    def verify_reset_code(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersVerifyResetCodeParams],
    ) -> UsersVerifyResetCodeResult:
        """Verify reset code

        POST /users/verify-reset-code
        Source: src/backend/database/routes/user-password-reset-routes.ts:237
        """
        response = self._request(
            "POST", "/users/verify-reset-code", json_body=dict(params) or None, options=options
        )
        return UsersVerifyResetCodeResult.construct_from(
            response.data if response else None, last_response=response
        )

    def complete_reset(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersCompleteResetParams],
    ) -> UsersCompleteResetResult:
        """Complete password reset

        POST /users/complete-reset
        Source: src/backend/database/routes/user-password-reset-routes.ts:369
        """
        response = self._request(
            "POST", "/users/complete-reset", json_body=dict(params) or None, options=options
        )
        return UsersCompleteResetResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list_sessions(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersListSessionsResult:
        """Get sessions

        GET /users/sessions
        Source: src/backend/database/routes/user-session-routes.ts:36
        """
        response = self._request("GET", "/users/sessions", options=options)
        return UsersListSessionsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def revoke_session(
        self,
        session_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> UsersRevokeSessionResult:
        """Revoke a specific session

        DELETE /users/sessions/{sessionId}
        Source: src/backend/database/routes/user-session-routes.ts:125
        """
        response = self._request("DELETE", f"/users/sessions/{session_id}", options=options)
        return UsersRevokeSessionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def revoke_all_sessions(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersRevokeAllSessionsParams],
    ) -> UsersRevokeAllSessionsResult:
        """Revoke all sessions for a user

        POST /users/sessions/revoke-all
        Source: src/backend/database/routes/user-session-routes.ts:217
        """
        response = self._request(
            "POST", "/users/sessions/revoke-all", json_body=dict(params) or None, options=options
        )
        return UsersRevokeAllSessionsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_terminal_image_storage_settings(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersGetTerminalImageStorageSettingsResult:
        """Get terminal image storage settings (admin only)

        GET /users/terminal-image-storage-settings
        Source: src/backend/database/routes/user-image-storage-routes.ts:197
        """
        response = self._request("GET", "/users/terminal-image-storage-settings", options=options)
        return UsersGetTerminalImageStorageSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def update_terminal_image_storage_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersUpdateTerminalImageStorageSettingsParams],
    ) -> UsersUpdateTerminalImageStorageSettingsResult:
        """Update terminal image storage settings (admin only)

        PATCH /users/terminal-image-storage-settings
        Source: src/backend/database/routes/user-image-storage-routes.ts:235
        """
        response = self._request(
            "PATCH",
            "/users/terminal-image-storage-settings",
            json_body=dict(params) or None,
            options=options,
        )
        return UsersUpdateTerminalImageStorageSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def test_terminal_image_storage_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersTestTerminalImageStorageSettingsParams],
    ) -> UsersTestTerminalImageStorageSettingsResult:
        """Test image storage visibility (admin only)

        POST /users/terminal-image-storage-settings/test
        Source: src/backend/database/routes/user-image-storage-routes.ts:279
        """
        response = self._request(
            "POST",
            "/users/terminal-image-storage-settings/test",
            json_body=dict(params) or None,
            options=options,
        )
        return UsersTestTerminalImageStorageSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    def register(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersRegisterParams],
    ) -> UsersRegisterResult:
        """Create a new user

        POST /users/create
        Source: src/backend/database/routes/users.ts:215
        """
        response = self._request(
            "POST", "/users/create", json_body=dict(params) or None, options=options
        )
        return UsersRegisterResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncUsersService(AsyncTermixService):
    service = "database"

    async def get_me(self, *, options: RequestOptions | None = None) -> UsersGetMeResult:
        """Get current user's info

        GET /users/me
        Source: src/backend/database/routes/users.ts:2086
        """
        response = await self._request("GET", "/users/me", options=options)
        return UsersGetMeResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def logout(self, *, options: RequestOptions | None = None) -> UsersLogoutResult:
        """User logout

        POST /users/logout
        Source: src/backend/database/routes/users.ts:1967
        """
        response = await self._request("POST", "/users/logout", options=options)
        return UsersLogoutResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_token(self, *, options: RequestOptions | None = None) -> UsersGetTokenResult:
        """Get current session token

        GET /users/me/token
        Source: src/backend/database/routes/users.ts:2187
        """
        response = await self._request("GET", "/users/me/token", options=options)
        return UsersGetTokenResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def dismiss_donation_modal(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersDismissDonationModalResult:
        """Permanently dismiss the donation reminder modal

        POST /users/me/dismiss-donation-modal
        Source: src/backend/database/routes/users.ts:2140
        """
        response = await self._request("POST", "/users/me/dismiss-donation-modal", options=options)
        return UsersDismissDonationModalResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def change_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersChangePasswordParams],
    ) -> UsersChangePasswordResult:
        """Change user password

        POST /users/change-password
        Source: src/backend/database/routes/users.ts:2827
        """
        response = await self._request(
            "POST", "/users/change-password", json_body=dict(params) or None, options=options
        )
        return UsersChangePasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete_account(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersDeleteAccountResult:
        """Delete user account

        DELETE /users/delete-account
        Source: src/backend/database/routes/users.ts:2746
        """
        response = await self._request("DELETE", "/users/delete-account", options=options)
        return UsersDeleteAccountResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def unlock_data(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersUnlockDataParams],
    ) -> UsersUnlockDataResult:
        """Unlock user data

        POST /users/unlock-data
        Source: src/backend/database/routes/user-data-access-routes.ts:42
        """
        response = await self._request(
            "POST", "/users/unlock-data", json_body=dict(params) or None, options=options
        )
        return UsersUnlockDataResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_data_status(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersGetDataStatusResult:
        """Check user data unlock status

        GET /users/data-status
        Source: src/backend/database/routes/user-data-access-routes.ts:105
        """
        response = await self._request("GET", "/users/data-status", options=options)
        return UsersGetDataStatusResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def setup_totp(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersSetupTotpResult:
        """Setup TOTP

        POST /users/totp/setup
        Source: src/backend/database/routes/user-totp-routes.ts:123
        """
        response = await self._request("POST", "/users/totp/setup", options=options)
        return UsersSetupTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def enable_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersEnableTotpParams],
    ) -> UsersEnableTotpResult:
        """Enable TOTP

        POST /users/totp/enable
        Source: src/backend/database/routes/user-totp-routes.ts:186
        """
        response = await self._request(
            "POST", "/users/totp/enable", json_body=dict(params) or None, options=options
        )
        return UsersEnableTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def disable_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersDisableTotpParams],
    ) -> UsersDisableTotpResult:
        """Disable TOTP

        POST /users/totp/disable
        Source: src/backend/database/routes/user-totp-routes.ts:326
        """
        response = await self._request(
            "POST", "/users/totp/disable", json_body=dict(params) or None, options=options
        )
        return UsersDisableTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_totp_backup_codes(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersGetTotpBackupCodesParams],
    ) -> UsersGetTotpBackupCodesResult:
        """Generate new backup codes

        POST /users/totp/backup-codes
        Source: src/backend/database/routes/user-totp-routes.ts:418
        """
        response = await self._request(
            "POST", "/users/totp/backup-codes", json_body=dict(params) or None, options=options
        )
        return UsersGetTotpBackupCodesResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def proxy_login(self, *, options: RequestOptions | None = None) -> TermixObject:
        """Create users proxy login

        POST /users/proxy-login
        Source: src/backend/database/routes/users.ts:1584
        """
        response = await self._request("POST", "/users/proxy-login", options=options)
        return TermixObject.construct_from(
            response.data if response else None, last_response=response
        )

    async def unlink_oidc_from_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersUnlinkOidcFromPasswordParams],
    ) -> UsersUnlinkOidcFromPasswordResult:
        """Unlink OIDC from password account

        POST /users/unlink-oidc-from-password
        Source: src/backend/database/routes/user-oidc-account-routes.ts:201
        """
        response = await self._request(
            "POST",
            "/users/unlink-oidc-from-password",
            json_body=dict(params) or None,
            options=options,
        )
        return UsersUnlinkOidcFromPasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def link_oidc_to_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersLinkOidcToPasswordParams],
    ) -> UsersLinkOidcToPasswordResult:
        """Link OIDC user to password account

        POST /users/link-oidc-to-password
        Source: src/backend/database/routes/user-oidc-account-routes.ts:54
        """
        response = await self._request(
            "POST", "/users/link-oidc-to-password", json_body=dict(params) or None, options=options
        )
        return UsersLinkOidcToPasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def initiate_reset(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersInitiateResetParams],
    ) -> UsersInitiateResetResult:
        """Initiate password reset

        POST /users/initiate-reset
        Source: src/backend/database/routes/user-password-reset-routes.ts:137
        """
        response = await self._request(
            "POST", "/users/initiate-reset", json_body=dict(params) or None, options=options
        )
        return UsersInitiateResetResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def verify_reset_code(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersVerifyResetCodeParams],
    ) -> UsersVerifyResetCodeResult:
        """Verify reset code

        POST /users/verify-reset-code
        Source: src/backend/database/routes/user-password-reset-routes.ts:237
        """
        response = await self._request(
            "POST", "/users/verify-reset-code", json_body=dict(params) or None, options=options
        )
        return UsersVerifyResetCodeResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def complete_reset(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersCompleteResetParams],
    ) -> UsersCompleteResetResult:
        """Complete password reset

        POST /users/complete-reset
        Source: src/backend/database/routes/user-password-reset-routes.ts:369
        """
        response = await self._request(
            "POST", "/users/complete-reset", json_body=dict(params) or None, options=options
        )
        return UsersCompleteResetResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list_sessions(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersListSessionsResult:
        """Get sessions

        GET /users/sessions
        Source: src/backend/database/routes/user-session-routes.ts:36
        """
        response = await self._request("GET", "/users/sessions", options=options)
        return UsersListSessionsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def revoke_session(
        self,
        session_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> UsersRevokeSessionResult:
        """Revoke a specific session

        DELETE /users/sessions/{sessionId}
        Source: src/backend/database/routes/user-session-routes.ts:125
        """
        response = await self._request("DELETE", f"/users/sessions/{session_id}", options=options)
        return UsersRevokeSessionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def revoke_all_sessions(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersRevokeAllSessionsParams],
    ) -> UsersRevokeAllSessionsResult:
        """Revoke all sessions for a user

        POST /users/sessions/revoke-all
        Source: src/backend/database/routes/user-session-routes.ts:217
        """
        response = await self._request(
            "POST", "/users/sessions/revoke-all", json_body=dict(params) or None, options=options
        )
        return UsersRevokeAllSessionsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_terminal_image_storage_settings(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UsersGetTerminalImageStorageSettingsResult:
        """Get terminal image storage settings (admin only)

        GET /users/terminal-image-storage-settings
        Source: src/backend/database/routes/user-image-storage-routes.ts:197
        """
        response = await self._request(
            "GET", "/users/terminal-image-storage-settings", options=options
        )
        return UsersGetTerminalImageStorageSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def update_terminal_image_storage_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersUpdateTerminalImageStorageSettingsParams],
    ) -> UsersUpdateTerminalImageStorageSettingsResult:
        """Update terminal image storage settings (admin only)

        PATCH /users/terminal-image-storage-settings
        Source: src/backend/database/routes/user-image-storage-routes.ts:235
        """
        response = await self._request(
            "PATCH",
            "/users/terminal-image-storage-settings",
            json_body=dict(params) or None,
            options=options,
        )
        return UsersUpdateTerminalImageStorageSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def test_terminal_image_storage_settings(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersTestTerminalImageStorageSettingsParams],
    ) -> UsersTestTerminalImageStorageSettingsResult:
        """Test image storage visibility (admin only)

        POST /users/terminal-image-storage-settings/test
        Source: src/backend/database/routes/user-image-storage-routes.ts:279
        """
        response = await self._request(
            "POST",
            "/users/terminal-image-storage-settings/test",
            json_body=dict(params) or None,
            options=options,
        )
        return UsersTestTerminalImageStorageSettingsResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def register(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UsersRegisterParams],
    ) -> UsersRegisterResult:
        """Create a new user

        POST /users/create
        Source: src/backend/database/routes/users.ts:215
        """
        response = await self._request(
            "POST", "/users/create", json_body=dict(params) or None, options=options
        )
        return UsersRegisterResult.construct_from(
            response.data if response else None, last_response=response
        )
