# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""UserAdmin: generated resource module."""

from __future__ import annotations

from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.user_admin import (
    UserAdminCountResult,
    UserAdminCreateUserResult,
    UserAdminDeleteUserResult,
    UserAdminDisableUserTotpResult,
    UserAdminExportUserResult,
    UserAdminGetDbHealthResult,
    UserAdminListResult,
    UserAdminMakeAdminResult,
    UserAdminRemoveAdminResult,
    UserAdminResetUserPasswordResult,
)
from ..types.user_admin import (
    UserAdminCreateUserParams,
    UserAdminDeleteUserParams,
    UserAdminDisableUserTotpParams,
    UserAdminMakeAdminParams,
    UserAdminRemoveAdminParams,
    UserAdminResetUserPasswordParams,
)


class UserAdminService(TermixService):
    service = "database"

    def make_admin(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminMakeAdminParams],
    ) -> UserAdminMakeAdminResult:
        """Make user admin

        POST /users/make-admin
        Source: src/backend/database/routes/user-admin-routes.ts:168
        """
        response = self._request(
            "POST", "/users/make-admin", json_body=dict(params) or None, options=options
        )
        return UserAdminMakeAdminResult.construct_from(
            response.data if response else None, last_response=response
        )

    def remove_admin(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminRemoveAdminParams],
    ) -> UserAdminRemoveAdminResult:
        """Remove admin status

        POST /users/remove-admin
        Source: src/backend/database/routes/user-admin-routes.ts:292
        """
        response = self._request(
            "POST", "/users/remove-admin", json_body=dict(params) or None, options=options
        )
        return UserAdminRemoveAdminResult.construct_from(
            response.data if response else None, last_response=response
        )

    def create_user(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminCreateUserParams],
    ) -> UserAdminCreateUserResult:
        """Admin create user

        POST /users/admin-create
        Source: src/backend/database/routes/user-admin-routes.ts:425
        """
        response = self._request(
            "POST", "/users/admin-create", json_body=dict(params) or None, options=options
        )
        return UserAdminCreateUserResult.construct_from(
            response.data if response else None, last_response=response
        )

    def reset_user_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminResetUserPasswordParams],
    ) -> UserAdminResetUserPasswordResult:
        """Reset a user's password (admin only)

        POST /users/admin/reset-password
        Source: src/backend/database/routes/user-admin-routes.ts:594
        """
        response = self._request(
            "POST", "/users/admin/reset-password", json_body=dict(params) or None, options=options
        )
        return UserAdminResetUserPasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    def disable_user_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminDisableUserTotpParams],
    ) -> UserAdminDisableUserTotpResult:
        """Disable a user's TOTP (admin only)

        POST /users/admin/totp/disable
        Source: src/backend/database/routes/user-admin-routes.ts:703
        """
        response = self._request(
            "POST", "/users/admin/totp/disable", json_body=dict(params) or None, options=options
        )
        return UserAdminDisableUserTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list(self, *, options: RequestOptions | None = None) -> UserAdminListResult:
        """List users

        GET /users/list
        Source: src/backend/database/routes/user-admin-routes.ts:76
        """
        response = self._request("GET", "/users/list", options=options)
        return UserAdminListResult.construct_from(
            response.data if response else None, last_response=response
        )

    def export_user(
        self,
        user_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> UserAdminExportUserResult:
        """Export a user's data (admin only)

        GET /users/admin/export/{userId}
        Source: src/backend/database/routes/user-admin-routes.ts:789
        """
        response = self._request("GET", f"/users/admin/export/{user_id}", options=options)
        return UserAdminExportUserResult.construct_from(
            response.data if response else None, last_response=response
        )

    def count(self, *, options: RequestOptions | None = None) -> UserAdminCountResult:
        """Count users

        GET /users/count
        Source: src/backend/database/routes/users.ts:2329
        """
        response = self._request("GET", "/users/count", options=options)
        return UserAdminCountResult.construct_from(
            response.data if response else None, last_response=response
        )

    def get_db_health(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UserAdminGetDbHealthResult:
        """Database health check

        GET /users/db-health
        Source: src/backend/database/routes/users.ts:2359
        """
        response = self._request("GET", "/users/db-health", options=options)
        return UserAdminGetDbHealthResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete_user(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminDeleteUserParams],
    ) -> UserAdminDeleteUserResult:
        """Delete user (admin only)

        DELETE /users/delete-user
        Source: src/backend/database/routes/users.ts:2955
        """
        response = self._request(
            "DELETE", "/users/delete-user", json_body=dict(params) or None, options=options
        )
        return UserAdminDeleteUserResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncUserAdminService(AsyncTermixService):
    service = "database"

    async def make_admin(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminMakeAdminParams],
    ) -> UserAdminMakeAdminResult:
        """Make user admin

        POST /users/make-admin
        Source: src/backend/database/routes/user-admin-routes.ts:168
        """
        response = await self._request(
            "POST", "/users/make-admin", json_body=dict(params) or None, options=options
        )
        return UserAdminMakeAdminResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def remove_admin(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminRemoveAdminParams],
    ) -> UserAdminRemoveAdminResult:
        """Remove admin status

        POST /users/remove-admin
        Source: src/backend/database/routes/user-admin-routes.ts:292
        """
        response = await self._request(
            "POST", "/users/remove-admin", json_body=dict(params) or None, options=options
        )
        return UserAdminRemoveAdminResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def create_user(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminCreateUserParams],
    ) -> UserAdminCreateUserResult:
        """Admin create user

        POST /users/admin-create
        Source: src/backend/database/routes/user-admin-routes.ts:425
        """
        response = await self._request(
            "POST", "/users/admin-create", json_body=dict(params) or None, options=options
        )
        return UserAdminCreateUserResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def reset_user_password(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminResetUserPasswordParams],
    ) -> UserAdminResetUserPasswordResult:
        """Reset a user's password (admin only)

        POST /users/admin/reset-password
        Source: src/backend/database/routes/user-admin-routes.ts:594
        """
        response = await self._request(
            "POST", "/users/admin/reset-password", json_body=dict(params) or None, options=options
        )
        return UserAdminResetUserPasswordResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def disable_user_totp(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminDisableUserTotpParams],
    ) -> UserAdminDisableUserTotpResult:
        """Disable a user's TOTP (admin only)

        POST /users/admin/totp/disable
        Source: src/backend/database/routes/user-admin-routes.ts:703
        """
        response = await self._request(
            "POST", "/users/admin/totp/disable", json_body=dict(params) or None, options=options
        )
        return UserAdminDisableUserTotpResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list(self, *, options: RequestOptions | None = None) -> UserAdminListResult:
        """List users

        GET /users/list
        Source: src/backend/database/routes/user-admin-routes.ts:76
        """
        response = await self._request("GET", "/users/list", options=options)
        return UserAdminListResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def export_user(
        self,
        user_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> UserAdminExportUserResult:
        """Export a user's data (admin only)

        GET /users/admin/export/{userId}
        Source: src/backend/database/routes/user-admin-routes.ts:789
        """
        response = await self._request("GET", f"/users/admin/export/{user_id}", options=options)
        return UserAdminExportUserResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def count(self, *, options: RequestOptions | None = None) -> UserAdminCountResult:
        """Count users

        GET /users/count
        Source: src/backend/database/routes/users.ts:2329
        """
        response = await self._request("GET", "/users/count", options=options)
        return UserAdminCountResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def get_db_health(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> UserAdminGetDbHealthResult:
        """Database health check

        GET /users/db-health
        Source: src/backend/database/routes/users.ts:2359
        """
        response = await self._request("GET", "/users/db-health", options=options)
        return UserAdminGetDbHealthResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete_user(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[UserAdminDeleteUserParams],
    ) -> UserAdminDeleteUserResult:
        """Delete user (admin only)

        DELETE /users/delete-user
        Source: src/backend/database/routes/users.ts:2955
        """
        response = await self._request(
            "DELETE", "/users/delete-user", json_body=dict(params) or None, options=options
        )
        return UserAdminDeleteUserResult.construct_from(
            response.data if response else None, last_response=response
        )
