# Generated by tools/sdk-gen/generate.py from spec/termix-openapi.json
# (release-2.8.0-tag). Do not edit by hand — see docs/sdk-plan.md phases F3/F4.

"""Workspaces: generated resource module."""

from __future__ import annotations

import builtins
from typing import Any, Dict, List, Literal  # noqa: F401, UP035

from typing_extensions import Unpack

from .._request_options import RequestOptions
from .._service import AsyncTermixService, TermixService
from ..models.workspaces import (
    WorkspacesApplyResult,
    WorkspacesCreateResult,
    WorkspacesDeleteResult,
    WorkspacesDuplicateResult,
    WorkspacesGetLastSessionResult,
    WorkspacesSaveLastSessionResult,
    WorkspacesSetContentResult,
    WorkspacesSetDefaultResult,
    WorkspacesUnsetDefaultResult,
    WorkspacesUpdateResult,
)
from ..types.workspaces import (
    WorkspacesCreateParams,
    WorkspacesDuplicateParams,
    WorkspacesSaveLastSessionParams,
    WorkspacesSetContentParams,
    WorkspacesUpdateParams,
)


class WorkspacesService(TermixService):
    service = "database"

    def create(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesCreateParams],
    ) -> WorkspacesCreateResult:
        """Save the current tab arrangement as a new named workspace

        POST /workspaces
        Source: src/backend/database/routes/workspaces.ts:110
        """
        response = self._request(
            "POST", "/workspaces", json_body=dict(params) or None, options=options
        )
        return WorkspacesCreateResult.construct_from(
            response.data if response else None, last_response=response
        )

    def list(self, *, options: RequestOptions | None = None) -> builtins.list[Any]:
        """List the current user's saved workspaces

        GET /workspaces
        Source: src/backend/database/routes/workspaces.ts:61
        """
        response = self._request("GET", "/workspaces", options=options)
        return response.data if response else []

    def get_last_session(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesGetLastSessionResult:
        """Fetch the auto-maintained "Last Session" workspace

        GET /workspaces/last-session
        Source: src/backend/database/routes/workspaces.ts:157
        """
        response = self._request("GET", "/workspaces/last-session", options=options)
        return WorkspacesGetLastSessionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def save_last_session(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesSaveLastSessionParams],
    ) -> WorkspacesSaveLastSessionResult:
        """Upsert the auto-maintained "Last Session" workspace

        PUT /workspaces/last-session
        Source: src/backend/database/routes/workspaces.ts:201
        """
        response = self._request(
            "PUT", "/workspaces/last-session", json_body=dict(params) or None, options=options
        )
        return WorkspacesSaveLastSessionResult.construct_from(
            response.data if response else None, last_response=response
        )

    def update(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesUpdateParams],
    ) -> WorkspacesUpdateResult:
        """Rename or recolor a workspace

        PATCH /workspaces/{id}
        Source: src/backend/database/routes/workspaces.ts:253
        """
        response = self._request(
            "PATCH", f"/workspaces/{id}", json_body=dict(params) or None, options=options
        )
        return WorkspacesUpdateResult.construct_from(
            response.data if response else None, last_response=response
        )

    def delete(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesDeleteResult:
        """Delete a workspace

        DELETE /workspaces/{id}
        Source: src/backend/database/routes/workspaces.ts:607
        """
        response = self._request("DELETE", f"/workspaces/{id}", options=options)
        return WorkspacesDeleteResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_content(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesSetContentParams],
    ) -> WorkspacesSetContentResult:
        """Overwrite a workspace's saved tab arrangement with a new payload

        PUT /workspaces/{id}/content
        Source: src/backend/database/routes/workspaces.ts:326
        """
        response = self._request(
            "PUT", f"/workspaces/{id}/content", json_body=dict(params) or None, options=options
        )
        return WorkspacesSetContentResult.construct_from(
            response.data if response else None, last_response=response
        )

    def duplicate(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesDuplicateParams],
    ) -> WorkspacesDuplicateResult:
        """Duplicate a workspace's content and color/icon under a new name

        POST /workspaces/{id}/duplicate
        Source: src/backend/database/routes/workspaces.ts:394
        """
        response = self._request(
            "POST", f"/workspaces/{id}/duplicate", json_body=dict(params) or None, options=options
        )
        return WorkspacesDuplicateResult.construct_from(
            response.data if response else None, last_response=response
        )

    def set_default(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesSetDefaultResult:
        """Mark a workspace as the restore-on-login default

        POST /workspaces/{id}/set-default
        Source: src/backend/database/routes/workspaces.ts:454
        """
        response = self._request("POST", f"/workspaces/{id}/set-default", options=options)
        return WorkspacesSetDefaultResult.construct_from(
            response.data if response else None, last_response=response
        )

    def unset_default(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesUnsetDefaultResult:
        """Remove a workspace as the restore-on-login default

        POST /workspaces/{id}/unset-default
        Source: src/backend/database/routes/workspaces.ts:505
        """
        response = self._request("POST", f"/workspaces/{id}/unset-default", options=options)
        return WorkspacesUnsetDefaultResult.construct_from(
            response.data if response else None, last_response=response
        )

    def apply(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesApplyResult:
        """Fetch a workspace to apply and mark it as just used

        POST /workspaces/{id}/apply
        Source: src/backend/database/routes/workspaces.ts:556
        """
        response = self._request("POST", f"/workspaces/{id}/apply", options=options)
        return WorkspacesApplyResult.construct_from(
            response.data if response else None, last_response=response
        )


class AsyncWorkspacesService(AsyncTermixService):
    service = "database"

    async def create(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesCreateParams],
    ) -> WorkspacesCreateResult:
        """Save the current tab arrangement as a new named workspace

        POST /workspaces
        Source: src/backend/database/routes/workspaces.ts:110
        """
        response = await self._request(
            "POST", "/workspaces", json_body=dict(params) or None, options=options
        )
        return WorkspacesCreateResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def list(self, *, options: RequestOptions | None = None) -> builtins.list[Any]:
        """List the current user's saved workspaces

        GET /workspaces
        Source: src/backend/database/routes/workspaces.ts:61
        """
        response = await self._request("GET", "/workspaces", options=options)
        return response.data if response else []

    async def get_last_session(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesGetLastSessionResult:
        """Fetch the auto-maintained "Last Session" workspace

        GET /workspaces/last-session
        Source: src/backend/database/routes/workspaces.ts:157
        """
        response = await self._request("GET", "/workspaces/last-session", options=options)
        return WorkspacesGetLastSessionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def save_last_session(
        self,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesSaveLastSessionParams],
    ) -> WorkspacesSaveLastSessionResult:
        """Upsert the auto-maintained "Last Session" workspace

        PUT /workspaces/last-session
        Source: src/backend/database/routes/workspaces.ts:201
        """
        response = await self._request(
            "PUT", "/workspaces/last-session", json_body=dict(params) or None, options=options
        )
        return WorkspacesSaveLastSessionResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def update(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesUpdateParams],
    ) -> WorkspacesUpdateResult:
        """Rename or recolor a workspace

        PATCH /workspaces/{id}
        Source: src/backend/database/routes/workspaces.ts:253
        """
        response = await self._request(
            "PATCH", f"/workspaces/{id}", json_body=dict(params) or None, options=options
        )
        return WorkspacesUpdateResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def delete(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesDeleteResult:
        """Delete a workspace

        DELETE /workspaces/{id}
        Source: src/backend/database/routes/workspaces.ts:607
        """
        response = await self._request("DELETE", f"/workspaces/{id}", options=options)
        return WorkspacesDeleteResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_content(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesSetContentParams],
    ) -> WorkspacesSetContentResult:
        """Overwrite a workspace's saved tab arrangement with a new payload

        PUT /workspaces/{id}/content
        Source: src/backend/database/routes/workspaces.ts:326
        """
        response = await self._request(
            "PUT", f"/workspaces/{id}/content", json_body=dict(params) or None, options=options
        )
        return WorkspacesSetContentResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def duplicate(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
        **params: Unpack[WorkspacesDuplicateParams],
    ) -> WorkspacesDuplicateResult:
        """Duplicate a workspace's content and color/icon under a new name

        POST /workspaces/{id}/duplicate
        Source: src/backend/database/routes/workspaces.ts:394
        """
        response = await self._request(
            "POST", f"/workspaces/{id}/duplicate", json_body=dict(params) or None, options=options
        )
        return WorkspacesDuplicateResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def set_default(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesSetDefaultResult:
        """Mark a workspace as the restore-on-login default

        POST /workspaces/{id}/set-default
        Source: src/backend/database/routes/workspaces.ts:454
        """
        response = await self._request("POST", f"/workspaces/{id}/set-default", options=options)
        return WorkspacesSetDefaultResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def unset_default(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesUnsetDefaultResult:
        """Remove a workspace as the restore-on-login default

        POST /workspaces/{id}/unset-default
        Source: src/backend/database/routes/workspaces.ts:505
        """
        response = await self._request("POST", f"/workspaces/{id}/unset-default", options=options)
        return WorkspacesUnsetDefaultResult.construct_from(
            response.data if response else None, last_response=response
        )

    async def apply(
        self,
        id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WorkspacesApplyResult:
        """Fetch a workspace to apply and mark it as just used

        POST /workspaces/{id}/apply
        Source: src/backend/database/routes/workspaces.ts:556
        """
        response = await self._request("POST", f"/workspaces/{id}/apply", options=options)
        return WorkspacesApplyResult.construct_from(
            response.data if response else None, last_response=response
        )
